### ISSUE TITLE
Setting Show the topper is ignored in a full import

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#3052] opened 2024-09-25 14:56 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When doing a full import for computer A to computer B the Settings Wizard ask for a number of settings but not "Do you want the topper displayed on all buttons Yes/No". It was set on Computer A but it is not set at Computer B. (OK, can do it manually)

### Usecases

When distributing a full export (through the Companion User Group) I want the Show Topbar on each button to be disabled as I  designed the PNGs on the button as 72x72, not the smaller version.As a result the buttons look terrible.

**Comment by Julusian** [comment] 2024-09-25 16:35
Duplicate of #2688

**Closed by Julusian** 2024-09-25 16:35 UTC
