### ISSUE TITLE
Import Full config not restoring button actions.

### ISSUE THREAD

**Issue by apullinger** [bitfocus/companion#1161] opened 2020-07-13 12:06 UTC
Hi, When I import an exported config from one mac, and import it to another, all the button actions are missing

Both Macs on 10.15.4

Companion version:
1.4.0 (backport-b402e70-1559)

[full-config_20200713-1303.json.zip](https://github.com/bitfocus/companion/files/4912284/full-config_20200713-1303.json.zip)

Any Help appreciated.

**Comment by josephdadams** [comment] 2020-07-16 16:04
Duplicate of #1145 

Try using Companion 2.0.

**Closed by josephdadams** 2020-07-16 16:04 UTC
Labels: BUG
