### ISSUE TITLE
Bug: List of Modules is too long

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#122] opened 2018-06-25 14:11 UTC
Lastet build, Timestamp: 2018-Jun-25 13:04

The list of Modules is getting too long and can´t be scrolled in Firefox.

![companion_gui_bug](https://user-images.githubusercontent.com/15065206/41855195-5195c540-7892-11e8-9f9d-a7425e51a6f8.PNG)

**Comment by haakonnessjoen** [comment] 2018-06-25 15:36
Duplicate of #115

**Closed** 2018-06-26 23:22 UTC
