### ISSUE TITLE
[BUG] 3.2 beta bugs - 

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#2658] opened 2023-11-22 15:16 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A few bugs and recommendations for 3.2: 

### **1. Feedback: "internal: Button: Use another buttons style" doesn't import to 3.2**

In Companion 3.1, the feedback could reference the same button on a different page, but this doesn't import into v3.2.

The Feedback either misses the whole page reference, and reverts to "this button", which makes the button black, 
Or it sets it to text with row and column reference, but misses the page number reference:

<img width="799" alt="Screenshot 2023-11-22 at 9 35 06 AM" src="https://github.com/bitfocus/companion/assets/76959770/21803dc5-c04e-440f-bbc4-d024dfb02dc3">

<img width="809" alt="Screenshot 2023-11-22 at 9 46 53 AM" src="https://github.com/bitfocus/companion/assets/76959770/5e18ae6a-93bc-4939-835f-d843e1b755bc">

### **2. Slow interface**
I'm finding emulator and Stream Deck surfaces very slow in 3.2. 
It fails to load most page buttons. 
Running 3.2 beta6546, on M1 Max.
Curious to know if other people are experiencing this too, since my surfaces were very responsive running 3.1.2 on the same system.

### **3. Connection Order Jumbled on Import**
When a config file is imported, it does not retain the connection order that was exported. The order of the connections appears to be arranged in the order in which they were added/created in the original profile. 

The problem is when you have many connections (ie 3 atems, 8 hyperdecks, 6 ptz cameras etc) you want to group these for easy viewing and editing. But currently they are a jumbled mess. 

Request1: exported configurations would remember the order of the connections. 
Request2: even better would be the ability to group connections into folders, and to enable/disable all connections in that folder (like you can with layers in a Photoshop folder).

<img width="562" alt="Screenshot 2023-11-22 at 9 53 16 AM" src="https://github.com/bitfocus/companion/assets/76959770/df1a21d6-1201-4963-9780-7659f82f5d3d">

### **4. Save Top Bar Preference in Config Export**
Currently the setting "Show the topbar on each button. This can be overridden per-button" in the Settings > Buttons is not saved as a preference when a configuration is exported. 

For my purposes, I design buttons to use the full 72x72, but I notice many people fail to change this top bar setting on export, resulting in jumbled and even missing text display when pushed off-screen. 

It would make importing faster to remember if the top bar was enabled or disabled in the design of the original configuration export. 

<img width="947" alt="Screenshot 2023-11-22 at 9 25 58 AM" src="https://github.com/bitfocus/companion/assets/76959770/9a15d38f-6d5b-483b-a1f1-eccca748ce8f">

Also a thank you - I noticed earlier versions of 3.2 had unpredictable resizing of text that would push it offscreen, but it appears now that the original sizes of text in 3.1.2 is now replicated in 3.2 – this is important to avoid a lot of reworking of button text display on large profiles.

### Environment (please complete the following information)

```markdown
- OS: M1 Max Sonoma
- Browser: Chrome
- Companion Version: 3.2 beta6545
```

**Comment by Julusian** [comment] 2023-11-24 00:48
1) This is an oversight, some fixup being done for actions wasnt done for feedbacks. I think I have a fix, I need to test it before pushing

2) Well, it is kind of expected to be a bit slower due to the change of how the images are being drawn (4x the previous size) and then downscale then when they are displayed. But after making some fixes the other week nothing has felt slow to me

3) keeping the order should be possible for a full import, I guess a page import might be able to keep the order of the new connections, but place them at the end?  
There is an issue to be able to group them into folders already

4) I wouldn't call this a bug, this is simply something we never implemented. The needed info isnt being exported currently

**Comment by davidjoshuaford** [comment] 2023-11-24 02:14
Thanks Julian!

I’ll look into my slow surfaces a bit more and try to figure out what’s going on. 

3. Yes, keeping order for the full import, and adding at the end for individual pages would be great

**Comment by Julusian** [comment] 2023-11-26 11:41
1 and 3 are now fixed.

I think we have been not including the sort order in exports for a while, but it is included now and will be used if found. If the order is missing, it will sort by label instead, to make it predictable

**Comment by davidjoshuaford** [comment] 2023-11-26 12:49
Wonderful, thank you! 

Any chance the top bar on/off preference could be saved on export?

**Comment by davidjoshuaford** [comment] 2023-11-28 02:38
Adding 2 more v3.2 beta6562 bugs that I've found:

### 1. Text color often does not import

- Seems to default to nothing, which makes it invisible. 
- When you open up the color palette, it shows as black, even though the actual text is invisible/ not there
- When you then select a color, the text reappears.
- Invisible button text seems to be inconsistent – some text has imported with correct colors; others have not
- This also applies to feedback text colors – some text colors in Feedbacks are missing/ invisible.

Examples: 

Example of how it should look with original white text: 
<img width="1372" alt="Screenshot 2023-11-27 at 9 22 23 PM" src="https://github.com/bitfocus/companion/assets/76959770/1d77faf5-2d8c-4d2a-ba29-18fc40ab0497">

How it looks when 3.1.1 config file is imported into 3.2 beta6562:
<img width="1367" alt="Screenshot 2023-11-27 at 9 25 02 PM" src="https://github.com/bitfocus/companion/assets/76959770/91ed3aa1-8580-46ef-abcd-1ec073efc8aa">
_(77/1/3 is an example of missing text; 77/1/2 is an example of text that was missing, but then was manually re-selected as black)_


### 2. All Pages are selected in menu dropdown

- Can't mouse click to select a page
- Typing in a page name or number does short list, but cannot select via mouse click or tab or enter

<img width="1360" alt="Screenshot 2023-11-27 at 9 23 53 PM" src="https://github.com/bitfocus/companion/assets/76959770/732c4070-a989-43ca-b6b7-52e5ce377f5d">

**Comment by Julusian** [comment] 2023-11-28 18:40
5) can you send me an export of a page which does that? I am not able to reproduce going from 3.1.2 -> beta

6) fixed

**Comment by davidjoshuaford** [comment] 2023-11-28 19:06
Thanks - will slack you the config page

**Comment by Julusian** [comment] 2023-12-08 00:20
@davidjoshuaford do you have any more info on the slowness?

**Comment by Julusian** [comment] 2024-01-06 19:19
I'm going to close this for now, as it isnt tracking any bugs that can be addressed currently.
Once you have more details on slowness open a new issue and that can be looked into.

If you still want 4) to be done, could you open a new feature request issue too

**Closed by Julusian** 2024-01-06 19:19 UTC
Labels: BUG

**Comment by davidjoshuaford** [comment] 2024-01-06 19:26
Sounds good - whatever the slowness was it seems to have gone in the recent builds I was using
