### ISSUE TITLE
Add copy for steps

### ISSUE THREAD

**Issue by MathiasGIZ** [bitfocus/companion#2383] opened 2023-03-21 10:44 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Sometimes you have programmed a batch of perfectly delayed actions on one button, but you want to do nearly the same with the next step of a button.
In the actual Beta you can only start programming a step from the very beginning. The workflow will be much easier, if there would be a copy function for steps.

### Usecases

In my case, I have programmed a batch of delayed actions.
Step 1:
PTZ 1 on preset 1 (Person 1)
wait some seconds
autotransition on Atem
show an H2R lower third
change picture in Atem MP to logo of persons organisation
activate keyer for that logo
wait some seconds
hide H2R lower third

Step 2:
same as step one for Person 2...

**Comment by Julusian** [comment] 2023-03-25 19:33
Related #2358 or #2337

**Comment by Julusian** [comment] 2023-12-22 20:11
Duplicate of #2584

**Closed by Julusian** 2023-12-22 20:11 UTC
Labels: Enhancement, area/gui
