### ISSUE TITLE
"Menu Tree" for Action menu

### ISSUE THREAD

**Issue by officialmattsnyder** [bitfocus/companion#1260] opened 2020-10-25 16:15 UTC
**Describe the feature**
I'd love to not have to scroll through all possible actions for all instances in order to find an action. Ideally, the menu to choose an action would open to a list of all instances, then the desired instance selected which would in turn display all of the relevant actions for that instance

**Is this platform dependent (windows, mac, ..)?**
Explain.

**Comment by dnmeid** [comment] 2020-11-23 22:15
You do not have to scroll through the whole list. You can use the search function to narrow the list. Try it with either the instance name or an action name.

**Comment by Julusian** [comment] 2022-02-25 00:50
Duplicate of #510 or #89

**Closed by Julusian** 2022-02-25 00:50 UTC
Labels: Enhancement, WONTFIX
