### ISSUE TITLE
Triggers not firing reliably [BUG]

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion#2334] opened 2023-02-15 21:27 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Building a Companion solution for ZoomOSC/ISO.

Built the following trigger:

Events:

> On condition becoming true

Condition:

> OSC___ISO_module: Gallery based feedback
>> Gallery Position: 2
>> Type of feedback: Hand Raised

Actions:

> OSC___ISO_module: Preselect user by Gallery Position
>> Position: 2
>> Option: Select

> OSC___ISO_module: Chat Via DM
>> Single Username (keep blank when you pre-select): <blank>
>> Message: This is a test message.

If I start fresh by launching Companion or when I finish creating the trigger, it works just fine. It's when I leave my office overnight and come back in the morning. With Companion still running from the previous day is when this trigger will not fire on the event.

If I change a value in the condition, or remove and replace the condition to the same values as originally configured, then the Trigger will fire as expected. i've confirmed this behavior for 3-days, now. Each morning I have to go through the same changes in order to get the trigger to react, again.

### Environment (please complete the following information)

```markdown
- OS: Mac Ventura 13.1
- Browser: Chrome Version 110.0.5481.100 
- Companion Version: 3.0.0+5666-beta-07c68547
```

**Comment by Julusian** [comment] 2023-02-15 21:42
Could you try putting the same condition as a feedback on a button? I'm curious if that behaves correctly, or has the same problem

**Comment by ZoomTestKitchen** [comment] 2023-02-15 21:55
I have added the condition as feedback on a button. I have the background color change to green when this event triggers.

Currently it changing to green background. But, currently I'm not experiencing the trigger issue, because I've already come into the office, and manipulated the trigger slightly, which means flip a current value to a different value, and then flip it right back to its original value. This is working and remain working all day, unless I step away for an extended period of time. I'm not sure what that extended time minimum value is.

**Comment by noiseboi** [comment] 2023-02-17 19:54
I'm seeing some triggers not firing reliably too. Sorry, I can't find a pattern to reproduce it. Using condition $variable >0 it would may be work once then stop working, it now seems to be working reliably with $variable =! 0. I also have a second trigger on the same $variable=0. Action is changing button background colour.
I've gone back to testing $variable >0 and it now seems to be working again.

**Comment by Julusian** [comment] 2023-02-21 20:37
@ZoomTestKitchen how did the feedback on the button behave when the trigger got back into the broken state?

And when it doesn't execute, I assume there is nothing shown in the log indicating it thought it did work?

When in the broken state, does restarting the module fix it?

Im not sure where to begin on this currently, as it could be a bug in such a wide range of places. Perhaps the module, the feedback logic, the trigger (lifecycle, or execution) or something else.

**Comment by ZoomTestKitchen** [comment] 2023-02-21 22:09
> @ZoomTestKitchen how did the feedback on the button behave when the trigger got back into the broken state?
> 
> And when it doesn't execute, I assume there is nothing shown in the log indicating it thought it did work?
> 
> When in the broken state, does restarting the module fix it?
> 
> Im not sure where to begin on this currently, as it could be a bug in such a wide range of places. Perhaps the module, the feedback logic, the trigger (lifecycle, or execution) or something else.

@Julusian ,

I'm using this with ZoomOSC/ISO module. 

  •  The trigger condition is meant to fire when there is a Zoom Raised Hand in Gallery Position #1. 
  •  I just got back to my office, Companion 3.0.0+5675 has been running all day, but this is my first time in the office today. 
  •  So, I just fired-up a Zoom meeting with 6 attendees, and raised the hand of one of them. 
  •  The trigger did not fire, which is supposed to send a DM via Zoom Chat, it did not send that message
  •  The button where I inserted the condition into the feedback did react to the hand-raised event by changing the background and text color.

You're correct, the log is not showing anything regarding success or failure.

Restarting the module does not fix this issue of the trigger not firing. I just did this and had the same result. No DM Chat Message sent. Condition Feedback on button did change background/text color.

If I go to the triggers condition and change the type of feedback to a different value and then flip it back to the Hand Raised value, the trigger will start working again. Also, if I delete the condition and re-apply it, the trigger will start working again.

But over an unknown amount of idle-time this trigger will stop working. But, if I were in a Zoom meeting all day activating this trigger, it doesn't seem to stop working.

That extended period of idle time seems to cause the issue.

======

BTW: I have another trigger that works reliably without issue. It is the first trigger in the list, whereas the troubled trigger is the 2nd trigger in the list. Those are the only two triggers.

**Events**:
    On variable change | Variable to watch | Active Speaking (OSC___ISO_module:activeSpeaker)

**Condition**
    <blank>

**Actions**
    OSC___ISO_module: Clear Selections
    OSC___ISO_module: Preselect user by name
    OSC___ISO_module: Preselect user by name

**Comment by Julusian** [comment] 2023-02-21 23:54
Thanks for the details, with those I found that restarting a module would get into this same state. While the zoom osc module shouldn't be crashing, it is possible that it is overnight and causing it to auto-restart itself and end up in this state.

I have pushed a fix in 3.0 build 5681. Please give it a try and let me know if it solves the issue for you.

**Comment by ZoomTestKitchen** [comment] 2023-02-22 01:18
I definitely will give it the test. Thanks for you attention and help with this.

**Comment by ZoomTestKitchen** [comment] 2023-02-22 12:58
Just jumped back into my studio and the trigger worked as designed, after sitting idle all night. It has not done this before. Looks like you've got it fixed, Julusian. Thanks

**Comment by Julusian** [comment] 2023-02-22 22:07
glad to hear!

**Closed by Julusian** 2023-02-22 22:07 UTC
Labels: BUG, area/triggers
