### ISSUE TITLE
Hide Buttons

### ISSUE THREAD

**Issue by IanPurpose** [bitfocus/companion#2141] opened 2022-10-05 19:24 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Button option to hide button. When selected appears as blank button but when unselected the said button will appear as normal. Essentially locks button uses and blacks it out.

### Usecases

Can be used when one button on a page is only used for editing purposes or periodically. Can be utilized so a page can be used for editing and show run scenarios without copying page. This way a second page is not used with 90% the same buttons and don't have to copy over commands or buttons multiple times from page to page for production vs show use.

**Comment by Julusian** [comment] 2022-10-05 19:39
Duplicate of #1411

**Closed by Julusian** 2022-10-05 19:39 UTC
