### ISSUE TITLE
grandMA Dot2 Control

### ISSUE THREAD

**Issue by AlexWHughes** [bitfocus/companion#291] opened 2018-10-14 23:06 UTC
It would be great to see the same level of control that we have in MA2 (if not a bit more) other applications are talking to grandMA2 and Dot2 via the web remote rather than telnet but both have telnet support for basic commands as well. 

In theory you should be able to just clone the grandMA2 one.

**Comment by AlexWHughes** [comment] 2018-10-14 23:07
While it could be said just configuring the grandMA2 one to a Dot2 console would work many users may not be aware of that.

**Comment by willosof** [comment] 2018-10-28 01:06
But does it work? Using the MA2 one on dot2 :)

**Comment by AlexWHughes** [comment] 2018-11-12 02:16
I was wrong. Dot2 doesn't have a telnet option (only web remote) so implementing it would have to via http commands

**Comment by willosof** [comment] 2018-11-12 07:30
Any docs for the http?

**Comment by josephdadams** [comment] 2019-08-22 00:02
Closing this one since it is a duplicate of #726 and it looks like someone is working on it over there.

**Closed by josephdadams** 2019-08-22 00:02 UTC
Labels: Module, Question, Request, Solution needed
