### ISSUE TITLE
[BUG] Cannot see full manufacturer list in Firefox

### ISSUE THREAD

**Issue by mrowwy** [bitfocus/companion#1239] opened 2020-09-29 18:05 UTC
Manufacturer drop-down exceeds page length and cannot be scrolled to view entire list.

1. Go to the browser page
2. Click on Device by Manufacturer
3. Try to scroll down
4. See that you can't see the bottom of the list.

**Expected behavior**
Be able to see all devices.

![8zTFJXy6in](https://user-images.githubusercontent.com/1996611/94597836-ed769200-0242-11eb-8946-a0bf895ecd88.gif)

 - OS: Windows 10 Pro for Workstations 1909 
 - Browser: Firefox 81.0
 - Companion Version: v2.1.0 

I can also confirm this behavior in Microsoft Edge, Vivaldi, and Brave.

**Comment by josephdadams** [comment] 2020-09-29 19:28
Duplicate of #362

**Closed by josephdadams** 2020-09-29 19:28 UTC
Labels: BUG
