### ISSUE TITLE
unable to add instances 

### ISSUE THREAD

**Issue by liquidsky1001** [bitfocus/companion#1732] opened 2021-09-25 20:06 UTC
**Describe the bug**
when clicking the "add by category" or "add by manufacturer" button no response 
Also when use the search tool, no response...

**Expected behavior**
to add a generic osc

**Desktop (please complete the following information):**

- OS: [windows 7 pro SP1]
- Browser [explorer]
- Companion Version [2.1.3]

**Comment by Julusian** [comment] 2021-10-04 20:20
Duplicate of #1740

**Closed by Julusian** 2021-10-04 20:20 UTC
Labels: BUG
