### ISSUE TITLE
Output Webpage that could built via Tiles 

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#1827] opened 2021-12-22 15:09 UTC
**Describe the feature**
Output Webpage that could be built via Tiles. This could give feedback on Items you want to monitor elsewhere. 

These could be built like presets or buttons but just display what your boxes are going with a variable.

Countdown from Mitti as 2 Tiles big. What camera your ATEM is on and what Preview. Logs from Companion. Time. Countdown clocks from Iris down. Something that can be Master for the Show and people can easily get all the information from all the devices on one screen.

**Comment by Julusian** [comment] 2021-12-22 15:29
Duplicate of #1429 

I intend to look at doing this as part of supporting other panel types, but it will not be a quick thing to do

**Closed by Julusian** 2021-12-22 15:29 UTC
