### ISSUE TITLE
Old latch button border

### ISSUE THREAD

**Issue by DanielBaulig** [bitfocus/companion#2354] opened 2023-03-03 23:45 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

In Companion 2.x, when setting up a latch button, the button would show a yellow "border" around the button when the button was latched. While stepped buttons in Companion 3.x are more powerful than latch buttons it appears the ability to easily create simple latch buttons that indicate their state using the yellow border has disappeared.

I think it might be useful to bring the yellow border feature back for a quick and simple way to reflect state on a button. Maybe even as a more powerful feedback option. The button border could be it's own feedback style that could be hidden or shown and maybe even have a customizable color.

### Usecases

Enables 2.x style latch buttons to be fully replicated in Companion 3.0

A fully featured button style property would also integrate well with the new button Step system while allowing users to quickly and simply show latch or step state on a button, without having to (e.g.) create multiple variations of a button image.

**Comment by dnmeid** [comment] 2023-03-03 23:57
this is a duplicate of #2245

**Closed by dnmeid** 2023-03-03 23:57 UTC
Labels: DUPLICATE
