### ISSUE TITLE
Feature Request: Web UI Surface Resizing

### ISSUE THREAD

**Issue by CheekiSkrub** [bitfocus/companion#2673] opened 2023-12-09 16:15 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Ability to change the surface sizing in the web ui depending on the streamdeck surface being used, or the web button layout being used. 

Eg
Stream Deck Mini - 3x2
Stream Deck Classic - 5x3
Stream Deck XL - 8x4

Also a custom sizing. This allows those using stream deck mobile to have custom sizing natively in the app, similar to using the web buttons. 
Allows for button programming without having to keep changing pages or work out where a button needs to be for a surface

### Usecases

Used when using stream deck mobile, or web buttons on a surface with large surface area resulting in the ability to have a large amount of buttons.

**Comment by Julusian** [comment] 2023-12-17 20:34
This is either asking for #2531 or #2189. I am closing this as a duplicate of one of those

**Closed by Julusian** 2023-12-17 20:34 UTC
Labels: Enhancement, area/gui
