### ISSUE TITLE
Grouping stream decks

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#330] opened 2018-11-12 07:42 UTC
Having one streamdeck as a master and when you move up a page it moves all the other stream decks to that page.

This could release the extra buttons on the slave stream decks

**Comment by goblynn93** [comment] 2018-11-16 18:14
This would be really nice combined with the ability to load unique page sets into each deck.

**Comment by Julusian** [comment] 2022-09-29 21:27
Duplicate of #570

**Closed by Julusian** 2022-09-29 21:27 UTC
Labels: Enhancement, Solution needed, Internal, Nice to have, Needs beer!
