### ISSUE TITLE
JS Error when renaming an ATEM instance label

### ISSUE THREAD

**Issue by cxselph** [bitfocus/companion#219] opened 2018-09-06 02:09 UTC
**Describe the bug**
Companion throws a JS error when renaming the instance label only when the instance is connected. You also lose connection until Companion is closed and reopened or disabling and reenabling the instance .

**Desktop (please complete the following information):**
OSX 10.13.2 and 10.12.6
Version 68.0.3440.106 (Official Build) (64-bit)
Companion-9ef8ffd

<img width="420" alt="renaming error" src="https://user-images.githubusercontent.com/14942903/45130881-96cc2600-b158-11e8-86cf-090693b859e6.png">

**Comment by haakonnessjoen** [comment] 2018-11-25 14:33
Unable to reproduce. Please test on current development build and reopen this issue if it is still a problem. I tested with an atem instance and renamed it while it was connected, without problems. It might have been fixed by the atem-library update earlier.

**Closed by haakonnessjoen** 2018-11-25 14:33 UTC
Labels: bug, module

**Comment by cxselph** [comment] 2018-11-26 02:41
I tried a current build and it seems to be working correctly now. Thanks
