### ISSUE TITLE
Grouping of triggers

### ISSUE THREAD

**Issue by DVEntertainment** [bitfocus/companion#2359] opened 2023-03-07 08:55 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I have about 120 triggers that i switch between on different jobs and scenarios. I turn them on and off if i don't need them for the job. I'd love to place them in a group, so i can keep track of the different triggers and where to find the correct trigger for the right job. This group doesn't have to have any feature other than showing in the GUI, although it would be nice to enable or disable all triggers in a group.

### Usecases

For sorting triggers if you have a ton of them

**Comment by Julusian** [comment] 2023-03-07 20:26
duplicate of #2065

**Closed by Julusian** 2023-03-07 20:26 UTC
