### ISSUE TITLE
UTF8 characters in presets not rendering correctly on M1 macOS, v3.2.x

### ISSUE THREAD

**Issue by phuvf** [bitfocus/companion#2647] opened 2023-11-13 11:16 UTC
![370126300_718255500201450_4829638856343972288_n](https://github.com/bitfocus/companion-module-zinc-oscpoint/assets/3513020/8f9c1a7e-d38c-4521-a2f1-edbdfc20a92c)

**Comment by phuvf** [comment] 2023-11-14 21:13
This was reported to me by another user who was giving OSCPoint a spin during an event yesterday. All my testing has been on Windows and Intel macOS - but I'll spin this up on an M1 MacBook tomorrow and see what happens.

Assuming my wife lets me borrow her machine.

**Comment by Julusian** [comment] 2023-11-14 21:30
I can confirm that chrome and safari on both m1 mac and chrome and companion on ubuntu are unable to render those characters.

My first thought was maybe the characters are missing from the font files we are using, but they are present in NotoSansSymbols2-Regular.ttf.

**Comment by Julusian** [comment] 2023-11-14 22:48
Oh right ok, so the canvas will only use the first font that we tell it to use and if the character is not in that font it will show the empty box (or similar depending on platform?) https://github.com/mono/SkiaSharp/issues/232#issuecomment-277459442

So I suspect that a font is bleeding through from the OS to fill the characters not available in the font we are drawing with.
It looks like changing that behaviour is going to require fiddling with something either in the rust skia wrapping, or perhaps inside skia itself.

I'm going to look into whether this is fixed by a different canvas library (as well as fixing the 'problem' that `skia-canvas` does not appear to be maintained, causing us to use a fork that I have published)

**Comment by dnmeid** [comment] 2023-11-15 00:32
It seemd to me that this was an old issue. I did try a lot of different fonts and combinations of fonts and on the intel mac the font fallback is working. First our built in fonts are used in the given order and then there is a fallback to the system fonts.
I just saw that I forgot to include all internal fonts, in fact only the sans serif and the color emoji is used and the symbols font is unused. So maybe only the fallback to the system font doesn't work.
Can you please check on the arm macOS the © char. On the button you should see the two straight lines from the c are not parallel, that is our sans font. If you see a colored ©, it will come from our color emoji font and if the two lines are parallel it is from the system font. If you then check the  ⚾ char, you should see the ball on the button colored and symmetrical. If the system font bleeds thru, the seams of the ball would be slightly tilted. If you see a colored ball, it means that fallback within skia-canvas is working as this char is not present in the sans font.
Then it is enough to just include the symbols.

**Comment by Julusian** [comment] 2023-11-18 19:17
I'm not 100% happy with how the code looks, but I am happy with how that #2648 behaves.
I think the code is unavoidable though, as I need to break out the symbol font into multiple font to make it work on my linux machine.

I've merged it into beta now, let me know if it doesn't work for you

**Closed by Julusian** 2023-11-18 19:17 UTC
Labels: BUG, os/mac, area/graphics
