### ISSUE TITLE
[BUG] Trigger incorrectly fires when enabled by action

### ISSUE THREAD

**Issue by otelom** [bitfocus/companion#2626] opened 2023-10-29 18:13 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a button with the action to toggle a trigger state and sometimes, when I press the button to enable it, it also executes the actions on the trigger and that should not happen.

I would show you the logs but apparently by restarting companion it deletes the logs, and in an attempt to reproduce this, I restarted companion and lost them...

The logs were something like:
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Pressed
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Released
Controls/ControlTypes/Triggers: Execute [name of my trigger]

Then I tried again and again and logs were just:
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Pressed
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Released
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Pressed
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Released
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Pressed
Surface/Handler/streamdeck:A00xxxxx: Button 1.4 Released

Since I don't have the logs anymore I cannot confirm for sure that "Controls/ControlTypes/Triggers" was what it said but was somethiing like it followed by "Execute" and the name of the trigger.
Also, "A00xxxxx" is my streamdeck serial number but redacted for safety.

### Steps To Reproduce

Cannot tell you exactly how to reproduce as it happens randomly but I can show you all my configurations.

Trigger Settings:

Events and Conditions:
![image](https://github.com/bitfocus/companion/assets/12788894/bb1f635f-7e84-442a-9ef7-43cc63b12ec8)

Actions:
![trigger actions](https://github.com/bitfocus/companion/assets/12788894/0570f1e0-95df-4e76-a03a-a0849b83391c)

Button to toggle trigger status:
![button settings to toggle](https://github.com/bitfocus/companion/assets/12788894/4312f82f-578e-4713-9286-d8c0fde6fb3f)

### Expected Behavior

The trigger should only be enabled and not executed.
Trigger should only execute when the events (and possible conditions) were met.

### Environment (please complete the following information)

```markdown
- OS:
- Browser: Chrome: 118.0.5993.118
- Companion Version: Build 3.1.1+6229-stable-4593dd7f
```

### Additional context

I would export the support bundle but I don't know where to upload it to or who to give it to!
You mention "It is not recommended to post this publicly, rather you should send it privately to the necessary party."
Let me know if you need it or who should I send it to should it be necessary.

Maybe related or can help to get some idea of what's wrong is #2566.

**Comment by Julusian** [comment] 2023-10-30 23:32
The screenshots were enough to be able to reproduce this.

As a reminder to my future self or anyone wondering what the problem was:

1) Create a trigger with a 'time of day' event set 1 minute in the future
2) Briefly enable then disable the trigger
3) Wait until the time specified has past (another couple of minutes is good for clarity)
4) enable the trigger, and it will execute

This was a bug in how we were tracking when the next execution time of the trigger was. Because it was disabled, we didnt perform the proper flow for keeping the 'nextExecutionTime' updated, so after the time had passed it was still pointing to when the skipped execution should have been done. This meant that once it was enabled, it saw that it should have executed and did so, assuming it was late (caused by clock drift, or high cpu usage or something).

The fix is easy, always update the 'nextExecutionTime' updated, even when the trigger is disabled

This is fixed in beta, and will be in 3.1.2 due to be released this week.

**Closed by Julusian** 2023-10-30 23:32 UTC
Labels: BUG
