### ISSUE TITLE
[BUG] Triggers page and modeal window

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2331] opened 2023-02-14 12:07 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a window open to create or edit a TRIGGER. If I accidentally click outside the window area, the window closes without warning. All edits are lost.

Please modify it so that the window can only be closed with buttons or "x".

### Steps To Reproduce

1. open trigger an try to edit
2. click outside the trigger's window

### Environment (please complete the following information)

```markdown
- OS: Win10
- Browser: Chrome
- Companion Version: 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)
```

**Comment by Julusian** [comment] 2023-02-14 13:10
duplicate of #2155

This is no longer an issue in v3.0. See https://github.com/bitfocus/companion/pull/2165

**Closed by Julusian** 2023-02-14 13:10 UTC
Labels: BUG
