### ISSUE TITLE
Main/ backup modules quick setup

### ISSUE THREAD

**Issue by Hakolsound** [bitfocus/companion#2596] opened 2023-10-06 19:09 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

The ability to duplicate an instance with its entire commands, OR choose another instance from the same type after duplicating a command (change from main Arena instance @ the duplicated command to backup Arena instance) would make the workflow much faster and error free.
Thanks!
     

### Usecases

We often set up main and backup machine to run Resolume Arena.
The Companion setup is a bit complex and includes at least 200 - 300 buttons with multiple commands in each.
After finishing programming a show to act for our satisfaction, we usually duplicate the Resolume Arena instance, change the target machine's IP and tediously go button after button, manually adding same command for the new backup instance, one by one.

Needless to say it is a very time consuming task but more important errors may and does occur because of the manual commands duplication.

**Comment by Julusian** [comment] 2023-10-06 19:21
I think this is a duplicate of #268, but perhaps proposing a different solution to the problem? It would be good to add this there instead of having multiple issues for the same thing

**Closed by Julusian** 2023-10-06 19:21 UTC
