### ISSUE TITLE
Logic based options on buttons

### ISSUE THREAD

**Issue by reidwwall** [bitfocus/companion#2861] opened 2024-05-09 00:29 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to have logic based options on a button.  

IF button pressed and A,B, and C = True, then do XYZ actions....
IF Botton pressed and D and E are true, then do "V" actions....

I have about 60 triggers, and about half of them are just creative variables so the action of a button does something depending on the state of a variable.....

### Usecases

It would save creating so many triggers........
it would mean we could essential create toggle buttons based upon feedback.  

If feedback says status = off, then button press turns "thing" on
if feedback says status = on, then button press turn "thing" off". 

steps don't really allow for actions based upon status of a device's state.

**Comment by Julusian** [comment] 2024-05-09 09:01
Duplicate of #1052 and #372

**Closed by Julusian** 2024-05-09 09:01 UTC
