### ISSUE TITLE
Swap Pages simultaniously on multiple Streamdecks

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#355] opened 2018-11-25 16:12 UTC
It would be great if it´s possible to swap pages on multiple streamdecks at once when swapping the page on the "Master" Streamdeck.
When extending one Streamdeck with another you have to change each page individually.  So any kind of "Streamdeck-linking" would be great.

**Comment by willosof** [comment] 2018-11-25 16:40
Duplicate of #330

**Closed by willosof** 2018-11-25 16:40 UTC
Labels: Bar talk subject, enhancement, nice to have, solution needed
