### ISSUE TITLE
Novation Launchpad Support

### ISSUE THREAD

**Issue by itsfiadh** [bitfocus/companion#2288] opened 2023-01-17 02:46 UTC
I would be super interested in being able to use Companion's elgato emulator using the Novation Launchpad as the input device. It shares a similar setup to the Streamdeck, but with more buttons. This would be especially useful for all the added functions Companion contains

**Comment by Julusian** [comment] 2023-01-21 13:21
Duplicate of #1709

**Closed by Julusian** 2023-01-21 13:21 UTC
