### ISSUE TITLE
Generic OSC fails when sending OSC to broadcast address

### ISSUE THREAD

**Issue by ickna** [bitfocus/companion#471] opened 2019-01-31 01:48 UTC
Uncaught Exception:
Error: send EACCES 192.168.2.255:53000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:498:11)

1. Add a Generic OSC instance
2. set target IP to local broadcast address (eg. 192.168.2.255) 
3. Create a button to send any OSC message
4. Test action

In my original use, I was setting a value of the same cue in multiple instances of Qlab on the same LAN. I can send a message via Qlab to the .255 broadcast address and it will change that value in all three computers. I'd hoped to be able to use Companion to send the same message to the same broadcast address to update the workspaces simultaneously.

 - OS: OSX, Safari 
 - Versions 1.3.0 (1a7592b-1203) and (5649064-1234)

**Comment by willosof** [comment] 2019-01-31 12:37
Yeah, to be able to send to broadcast, we'll need admin privileges on the computer running companion. We don't have that right now.

We'll look into it.

**Comment by depili** [comment] 2019-02-07 05:45
This shouldn't be about having admin access, since a regular user can use other programs to send the broadcast packets just fine, at least on linux and osx.

It seems to be that the nodejs sockets just need a flag to be set to allow broadcast packets to be send, see https://stackoverflow.com/questions/6177423/send-broadcast-datagram and https://nodejs.org/docs/v0.3.1/api/dgram.html#dgram.setBroadcast

**Comment by depili** [comment] 2019-02-07 06:04
Just adding `broadcast: true`to the options for the shared osc implementation in https://github.com/bitfocus/companion/blob/master/lib/osc.js#L26 is enough to allow the broadcast packets to work in osx, will more than likely be enough for linux and windows also.

**Comment by depili** [comment] 2019-02-07 19:33
I can confirm that the above change also works just fine on linux.

**Comment by haakonnessjoen** [comment] 2019-02-07 19:50
Fixed by 8771b6f

**Closed by haakonnessjoen** 2019-02-07 19:50 UTC
Labels: Internal, Solution needed

**Comment by jgastonraoul** [comment] 2019-02-08 23:13
Is there a way to do the same thing on ArtNet module ?

**Comment by depili** [comment] 2019-02-09 09:02
Opening a separate issue would be the right thing to do for that. But the
solution would be to somehow call .setBroadcast(true) on the udp socket in
https://github.com/hobbyquaker/artnet/blob/master/lib/artnet.js#L20
