### ISSUE TITLE
Update modules over GUI

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2494] opened 2023-06-22 07:05 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It should possible to update the modules from the GUI. This could done over the connection list with an extra update button in the connection item.

### Usecases

Stay tuned with the last version without waiting for a new main release.

**Comment by Julusian** [comment] 2023-06-22 07:37
Duplicate of #1002

**Closed** 2023-06-22 07:37 UTC
