### ISSUE TITLE
Group Triggers

### ISSUE THREAD

**Issue by BOBBYdirectory** [bitfocus/companion#2504] opened 2023-06-26 03:18 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Allow the ability to group triggers which will help with organizing multiple sets of triggers which affect different devices

**Comment by Julusian** [comment] 2023-07-03 20:09
Duplicate of #2065

**Closed by Julusian** 2023-07-03 20:09 UTC
