### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LorenzoApra** [bitfocus/companion#2200] opened 2022-11-25 17:02 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In blackmagic design atem if I set as Preset Style Long Name when I drag and drop a preset the name is always shor and not long.

### Steps To Reproduce

go to Connection
Add Blackmagic design Atem
go to Edit
Select as Preset Style Long Name
Go to button 
go to preset
go to blackmagic design atem
select preview M/E1
Drag and drop one of the preset

### Environment (please complete the following information)

```markdown
- OS: MacOS 12.6.1/Win 10
- Browser: Chrome/Safari/Edge
- Companion Version: 2.4.0
```

**Comment by Julusian** [comment] 2022-11-25 17:06
duplicate of https://github.com/bitfocus/companion-module-bmd-atem/issues/221

**Closed by Julusian** 2022-11-25 17:06 UTC
Labels: BUG

**Comment by AndrewApi** [comment] 2022-11-27 12:47
"closed this as not planned". What does this mean, is the issue fixed in the latest beta?
