### ISSUE TITLE
Cancel button operation if an action is in a certain state. 

### ISSUE THREAD

**Issue by Brennan-Dan** [bitfocus/companion#1136] opened 2020-06-13 10:30 UTC
**Describe the feature**
Companion allows a state change from the last pressed button. But suppose if two or more buttons used the same features/functions to operate. One button could cancel the other out. If a feature to “cancel action” was enabled, the other button could not accidentally disable the command until its state has been switched back.

**Usecases**
Behringer X32: To not switch on channel when it is muted

Companion: To not change colours of button text/ button background when another button is pushed.

Blackmagic ATEM: To not accidentally cut to blank sources with no inputs when “on air”

**Comment by Julusian** [comment] 2022-02-25 00:46
I think this is a duplicate of #1052

**Closed by Julusian** 2022-02-25 00:46 UTC
Labels: Enhancement
