### ISSUE TITLE
[BUG] tricaster connection

### ISSUE THREAD

**Issue by kaleforge** [bitfocus/companion#2570] opened 2023-09-11 13:57 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating to the most recent tricaster firmware, the connection between companion and Tricaster is inconsistent. Dropping connection on and off

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by bryce-seifert** [comment] 2023-09-11 17:15
Duplicate of https://github.com/bitfocus/companion-module-newtek-tricaster/issues/41

**Closed by bryce-seifert** 2023-09-11 17:15 UTC
Labels: BUG
