### ISSUE TITLE
Dropdown menu doesn't fit the screen

### ISSUE THREAD

**Issue by hotag** [bitfocus/companion#636] opened 2019-05-05 21:36 UTC
The bug is really simple, when I'm using Chrome (I didn't test with other browsers), the dropdown menu for "Add by Category" or "Add by Manufacturer" don't fit the screen, which is awful to know what features Companion already has.

**To Reproduce**
1. Go to 'Instances'
2. Click on 'Add by Category' or 'Add by Manufacturer'
3. See error

**Comment by johncoles** [comment] 2019-05-18 22:39
Should also be noted that the lists have multiple duplicates that really aren't needed. For example in "Add by category" the categories ""eventmaster "EMT", "xml" and "Toolset" all only have "Barco Event Master xml version" in them. It's also important to note that none of those category names are actually categories.

**Comment by josephdadams** [comment] 2019-08-26 00:42
This is really a duplicate of #362 , the list is too long to fit on the screen. Closing this one.

**Closed by josephdadams** 2019-08-26 00:42 UTC
Labels: GUI
