### ISSUE TITLE
[BUG] Can‘t connect with liveprof2

### ISSUE THREAD

**Issue by MeandtheDevilknockingonyourdoor** [bitfocus/companion#1539] opened 2021-04-01 19:40 UTC
**Describe the bug**

i have a issue what Happens after upgrade my Mac to big sur.
when I start the instance the log says

“Error: bind EADDRINUSE 127.0.0.1:8011”

Companion Control in live Prof is in standard mode

I don’t know what’s happen. Before the upgrade everything work well.

**To Reproduce**
**Expected behavior**
**Screenshots**
**Desktop (please complete the following information):**

- OS: [Big Sur]
- Browser [safari]
- Companion Version [2.1.2]

**Additional context**

**Comment by Julusian** [comment] 2021-04-05 12:11
Duplicate of https://github.com/bitfocus/companion-module-audiostrom-liveprofessor/issues/1

**Closed by Julusian** 2021-04-05 12:11 UTC
Labels: BUG
