### ISSUE TITLE
Bug Report:  When button is selected on Stream Deck, changing pages moves the button's label to new page.

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#72] opened 2018-06-05 19:50 UTC
**Describe the bug**
When yellow "selection" bar is displayed at top of button, changing pages will temporarily display the first button's label on the new page.

**To Reproduce**
Occasionally when pressing a button on the Stream Deck, the button will remain "selected" for up to 10 seconds.  I do not know how to reproduce this particular aspect of the bug, as sometimes the yellow selection indicator extinguishes right away, other times it will not.

1. While button is "selected" change pages (up or down)
2. Button label is diplayed on new page.
3. Pressing the button executes the action that is actually programmed, and not what the "copied" label suggest.  After pressing the button, the label reverts to what it should be.
4. Cycling through the pages resets the label to what it should be.

See linked video below for demonstration.

**Expected behavior**
Button Labels should always display what is programmed.

**Screenshots**
https://photos.app.goo.gl/EdA15WhnbMwl5l9q2

**Desktop (please complete the following information):**
 - OS: macOS High Sierra (10.13.4)
 - Browser: Chrome 66.0.3359.181
 - Version: Companion 1.0.12

**Additional context**

**Comment by haakonnessjoen** [comment] 2018-06-05 20:00
Hi,

The "up to 10 seconds" problem should have been fixed after e081b0a. Could you please try to download the latest binary from https://builds.bitfocus.io/companion/ and try again and update if that issue is resolved?

The next part, seems like a bug that would still be present, I will investigate.

Thank you for the very detailed bug report! <3

**Comment by haakonnessjoen** [comment] 2018-06-05 20:05
I am currently not able to reproduce your bug. Are you, on the latest version?

**Comment by IanTGreenwood** [comment] 2018-06-05 20:28
> I am currently not able to reproduce your bug. Are you, on the latest version?

I just downloaded the newest version and it seems to have fixed the first part of the bug, and by the extension, the second part.  I was using "Companion-1.0.12-bugfix1-osx" downloaded yesterday.

**Comment by haakonnessjoen** [comment] 2018-06-05 20:30
Already fixed by e081b0a

**Closed by haakonnessjoen** 2018-06-05 20:30 UTC
Labels: bug, question
