### ISSUE TITLE
Companion Button Actions don't fire on Streamdeck when used in multi-action [BUG]

### ISSUE THREAD

**Issue by thechrisguerra** [bitfocus/companion#2467] opened 2023-06-02 13:53 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I searched prior issues and located a couple that match the issue I'm experiencing but they are closed. I commented but my comments have not been answered so I'm submitting a new issue. The previous issue is #1180. 

When using the companion button plugin for Streamdeck, the buttons work fine if you assign them directly to the home screen. But once you try to create a multi-action button and nest the companion button within the multi-action, the button's fail and do not trigger. 

I've noticed that when you add a button to the main screen, it will populate the button with the image from companion as expected - but when you add a button within a multi-action, it does not populate the button image. So even though it let's you add the button, it doesn't seem to be actually linking to companion. 

### Steps To Reproduce

1. Open the Streamdeck software
2. Add a companion button to the main screen (it should populate the image from companion)
3. Test that it fires correctly (in my case, I firing a simple macro to change super source)
4. Add a new multi-action button from Steamdeck
5. Add a companion button within the multi-action - use the same one you tested earlier
6. Add an OBS scene switch action
7. Return to the home screen and run the multi-action

### Expected Behavior

The expected behavior would be for companion to switch super sources from the macro being run, and then OBS switch scenes.

### Environment (please complete the following information)

```markdown
- OS:Windows 11
- Browser: Chrome 114.0.5735.91
- Companion Version: 3.0.0-rc1+5909-v3-0.0-rct-725c3583
```

### Additional context

I also noticed that if you place the companion button in the muti-action by itself without any other actions - it fires. The moment you add any other non-companion button actions, the companion buttons do not fire but the other actions, such as switching the OBS scene do fire.

**Comment by Julusian** [comment] 2023-06-04 20:32
I've tried following your instructions to produce a multi-action, but it is working fine for me other than the image not showing

![image](https://github.com/bitfocus/companion/assets/1327476/4248ce89-12c4-4e53-953a-f49b60752148)

**Comment by thechrisguerra** [comment] 2023-06-05 00:29
Ok so along those lines, do you have any recommendations for how I might need to verify I have things configured to produce the expected results you’re seeing? And is there anything I can provide at this point that may help you see what I’m seeing on my side? Screenshots or a video? Happy to do whatever is needed. Thank you for responding.

**Comment by thechrisguerra** [comment] 2023-06-06 20:47
I’ve captured some video of what I’m seeing on my side. The multi-action does not fire for me. Hope this helps.   [StreamDeck Multi-Action Not Firing ](https://www.dropbox.com/s/080janea864wm1u/Video%20Jun%2006%202023%2C%2015%2038%2049.mov?dl=0)

**Comment by Julusian** [comment] 2023-06-14 19:54
Is this any better/worse in the latest update to the plugin that was released late last week? That will at least fix the icon drawing issue, could have an impact on the rest

I'm not sure how to progress here, as I am really unable to reproduce it, and have no idea why it wouldn't work for you.

**Comment by Julusian** [comment] 2024-02-25 19:46
If anyone has any more advise on how to reproduce this I can reopen this, but as there aren't more users chiming in it sounds like this is a rare bug that only affects a couple of people, or got fixed by accident at some point.

**Closed by Julusian** 2024-02-25 19:46 UTC
Labels: BUG, Help Wanted, area/elgato-plugin
