### ISSUE TITLE
[BUG] Import of a particular page not working

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#3033] opened 2024-09-14 09:59 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A 16x8 page with many steps per button and over 5000 feedbacks seems to export OK (page, full export) but during import theHouston message is displayed and no luck. The page is about ATEM Micro panel with 20 source buttons and 60-80 shifted sources and is for 1 M/E - 4 M/E BMD switchers. I'm planning on sharing this page on the Companion User Group page within a few weeks but there is no point in doing that when people can't import it. 

### Steps To Reproduce

1. Export a "heavy" page; 2. Import the export in same configuration / installation (Mac) or on another (Windows mini-PC with limited resources) 3. Check Log (no errors)

### Expected Behavior

Perhaps an error message during export / import (in Log); successful import of page / full file

### Environment (please complete the following information)

```markdown
- OS: Mac OS apple silicon, latest version
- Browser: Safari
- Companion Version: both v3.3.1 and 3.4.0

Also on Windows 11 mini-PC with Edge
```

### Additional context
UPDATE: This is related to DB size. Reduced the page size for p1 from 163,2 MB to 29,4 MB (by combining Boolean Expressions and therefore dropped a large number of 24 KB PNGs). Was able to import the page on mini-PC successfully. Reduced another page from 77,8 MB to 17,3 MB by removing PNGs (copies from Stills in ATEM media pool). Reduced the overall size from full export from 300 MB to 117,3 MB, but still NOT able to import it on mini_PC
_No response_

**Comment by Julusian** [comment] 2024-09-16 11:17
Could you send me the page so that I can try importing it for debugging?
Either here, DM on slack or email me.

**Comment by LikeThisReview** [comment] 2024-09-16 17:48
Julian,
Thanks. The page is now 29,4 MB and I can import it OK now. I was able to
bring it down in size in steps (from 163 MB). Gmail does not accept
attachments larger than 25 MB).
The full export is now 117,3 MB and I still cannot import it.

I reduced file size by combining boolean expressions (used to have a 46 KB
PNG for each expression; hundreds of PNG).

Regards,
Nico Wasmus


Op ma 16 sep 2024 om 13:17 schreef Julian Waller ***@***.***>:

**Comment by thedist** [comment] 2024-09-16 17:54
Is there a particular reason why you're trying to put an excessively large amount of data within a single page? Even if technically possible this sounds like it'd run in to performance issues.

**Comment by LikeThisReview** [comment] 2024-09-16 19:05
Jeff,
The page is a ATEM ‘micro’ panel with 20 buttons each for preview, program,
and select bus. With Shift buttons you can access all shifted sources. The
page is 16x8 for four Stream Deck XL surfaces. It supports all current BMD
switchers, including the 4 M/E Constellation 4K.
The page is in a working version although I need to rework a number of
buttons because features available in v3.4.0 (logical AND). Performance is
acceptable.

See also my page ATEM Micro panel 10 as posted mid April.

Regards Nico


Op ma 16 sep 2024 om 19:54 schreef Jeff Martin ***@***.***>

**Comment by Julusian** [comment] 2024-09-17 18:59
you could upload it to google drive or wetransfer or something and send the link?

between this and #2980, maybe we need to be thinking about rethinking the db file, as it seems like we might be hitting a limit of the size of json that nodejs can handle

**Comment by LikeThisReview** [comment] 2024-09-19 13:21
Julian,
Sorry my google drive is full, but I think it is clear now. As before, too
many PNGs are causing the issue. I also tried to send one button in a 7.1
MB export but it looks like it is too large for github.

If you like, you can create a button, add 1 feedback with a PNG and then
copy the feedback a large number of times. The copy-paste the button many
times. The export file should be very large.

Regards, Nico Wasmus

Op di 17 sep 2024 om 21:00 schreef Julian Waller ***@***.***>:

**Comment by thedist** [comment] 2024-09-19 15:15
Are each of your PNGs unique, or are you using the same PNG across multiple buttons? It sounds like while there may be an issue of importing an excessively large page, the cause could likely be solved by better use of graphics, such as removal of duplications, and or using graphics generation in companion rather than pre-making all the PNGs which vastly increases storage size.

**Comment by LikeThisReview** [comment] 2024-09-19 20:09
Jeff,
There are two sets of PNG’s I use:
1. White, Green, Red, Yellow, Blue, Grey, and Black buttons for selecting
camera 1, selecting a destination etcetera. Small set, used all over the
place
2. Settings like ON OFF. Large set , each used a view times.
As mentioned, I started by adding PNGs when adding additional functionality
(expressions). Now I have combined many expressions and reducing the number
of PNG used significantly.

Further removal of PNG’s may perhaps be possible by using more advanced
configuration techniques. i did not look in to that.
At the other hand, if more atem Feedbacks would support variables the
number of steps and actions, and Feedback with PNG’s will be reduced
drastically.

I exported a PNG from Stream Deck software a couple of years ago (188x188)
and are using that as a template ever since. I’m not aware Graphics
Generation in Companion - do you have more info on that?

Perhaps is my goal of making a 16x8 button atem micro panel in Companion
for a 4 M/E Constellation switcher to ambitious.

Regards, Nico Wasmus

**Comment by thedist** [comment] 2024-09-19 20:37
>1. White, Green, Red, Yellow, Blue, Grey, and Black buttons for selecting
camera 1, selecting a destination etcetera. Small set, used all over the
place

Do those need to be PNG's, instead of just changing a buttons background?

>2. Settings like ON OFF. Large set , each used a view times.
Do these need to be PNG's, instead of just Text?

> I exported a PNG from Stream Deck software a couple of years ago (188x188)

IIRC the button resolution is 72x72, or 72x58 with the top bar enabled (at least these are the button resolutions provided to feedbacks). So part of your issue could be you're using PNG's that are about 7 times larger than needed, and times that by the number of PNG's you're using then depending on encoding that may be a significant amount.

> I’m not aware Graphics Generation in Companion - do you have more info on that?

I created a utility module, [https://github.com/thedist/companion-module-utils](https://github.com/thedist/companion-module-utils), that can be used by module developers to do basic image generation, such as shapes, symbols, audio meters, of different colours/sizes/positions. This can be used by people who want to build a utility module, or add to another Companion module, that can generate those images as needed rather than storing vast amounts of PNG data and it uses caching so a dozen buttons could use the same image and it'd only be generating the data once, where as if you use PNG's on buttons then it'd result in a crazy amount of duplicate data.

**Comment by LikeThisReview** [comment] 2024-09-19 21:08
Many thanks!

**Comment by stevespaw** [comment] 2024-09-19 21:09
Just to add my 2 cents, only worth a penny, I have optimized PNG's on every button. They are semi transparent and then use background color to change the look. Then use needed text on top. This works and looks great and I have no complaints. But MANY of the buttons are the same PNG. I always wonder if it would be more efficient to have a "media library" to load these PNG's to recall and reference. If I could just load my library of buttons and then select them from a library when building a show it would go so much faster..

**Comment by LikeThisReview** [comment] 2024-09-19 21:27
Steve, Thanks! Will do some tests with semi-transparent PNGs / changing
Background color (still a PNG!?).
Saving PNGs with a unique key / link in a separate Database sounds good to
me. It will reduce page size and size full json export (but export PNG
function is then also needed).

Resizable grid, more than 99 pages, and other new features will increase
storage demands…. Curious what the developers decide to do.

Regards,
Nico

**Comment by Julusian** [comment] 2024-09-23 19:58
OK, I believe you are hitting the semi-arbitrary limit defined at https://github.com/bitfocus/companion/blob/c8470f33ace18d6d6bb5e77585b98a34833bad89/companion/lib/UI/Handler.ts#L130
This is triggering a DOS attack prevention logic, by closing connections which try to send messages larger than a defined threshold.

For now I'm going to just increase this, but I can't guarantee that will behave well.
At ~150mb I can already feel companion being much slower than before, and its using quite a bit of memory (1gb, with no modules running). And that's not factoring in the network traffic, as we are sending those pngs to your browser whenever you edit a button

**Closed by Julusian** 2024-09-23 19:58 UTC
Labels: BUG

**Comment by LikeThisReview** [comment] 2024-09-23 21:51
Many thanks. I’m making good progress on reducing the size of the page
export (now back to 10 MB) and the full export (now 53,6 MB).
Regards, Nico
