### ISSUE TITLE
Iris Countdown Timer unable to change display mode "time"

### ISSUE THREAD

**Issue by LightmasterDanny** [bitfocus/companion#348] opened 2018-11-20 12:36 UTC
**Describe the bug**
Unable to change to display mode "Time" all other like Clock, Black and TEST works fine.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser: Safari
 - Version 12.0.1

**Comment by haakonnessjoen** [comment] 2018-11-26 18:39
Could not reproduce. Might be fixed in an earlier update.

**Closed by haakonnessjoen** 2018-11-26 18:39 UTC
Labels: BUG, Enhancement, Module

**Comment by LightmasterDanny** [comment] 2018-11-27 10:09
Hi, still does not work to switch back to timing after switching to any other display mode. Tested on latest update 1.2.0 with same result as before.

**Comment by DaveShep** [comment] 2018-11-27 11:01
Running 1.2.0. Cannot reproduce.
