### ISSUE TITLE
Reorder pages

### ISSUE THREAD

**Issue by buffos** [bitfocus/companion#2438] opened 2023-05-05 21:18 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Reorder pages. It would be nice if this is possible. 

Even page swapping (swap page 3 with page 5) would be enough to change the order of the pages, without any fancy tool to assist.

### Usecases

You have a new idea or request and add a new page, but you want to keep pages with the same theme close to each other, so you need to reorder pages.

For example, you have 3 cameras and 3 pages that control them (4,5,6) and then you have audio-related stuff. You get a new camera and you want to add a new page to control it, but you need it to be at position 7. Currently, this is almost impossible to do.

**Comment by krocheck** [comment] 2023-05-05 22:04
This is planned, and we've made some architecture modifications in 3.0 that move us toward being able to do this in a future version, but there's a couple more incremental steps to go.

**Comment by Julusian** [comment] 2023-12-22 20:38
Duplicate of #976

**Closed by Julusian** 2023-12-22 20:38 UTC
Labels: Enhancement
