### ISSUE TITLE
Behringer X Touch Mini

### ISSUE THREAD

**Issue by Agodoys** [bitfocus/companion#1984] opened 2022-04-08 01:58 UTC
As one of the cheapest surface control units, Behringer X Touch Mini has been widely used in multiple enviroments. Maybe is one of the most useful units for VMix since it has multiple variable control, as well as multi state buttons.

**Comment by Julusian** [comment] 2022-11-01 17:38
I believe this is a midi device, so this is a duplicate of #1709

**Closed by Julusian** 2022-11-01 17:38 UTC
Labels: Enhancement, area/surface
