### ISSUE TITLE
Drop down menu not working correctly.

### ISSUE THREAD

**Issue by WNTLtd** [bitfocus/companion#754] opened 2019-07-28 11:21 UTC
Bitfocus Companion
2.0.0 (f67a277)
**Describe the bug**
On the Instances page - when clicking on the "Add by manufacturer" - the pop up list appears - but doesn't move with the page, meaning you cannot click on the upper or lower items on the list.  The "Add by category" works as expected.

**To Reproduce**
1. Go to 'Instances'
2. Click on 'Add by manufacturer'
3. Scroll down to '....' - that's the point - you cannot scroll down....!

**Expected behavior**
Same as clicking on "Add by category"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave . MacBook Pro late 2011 13" screen.
 - Browser Chrome 
 - Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by josephdadams** [comment] 2019-08-21 23:44
Duplicate of #636 . Closing this one.

**Closed by josephdadams** 2019-08-21 23:44 UTC
