### ISSUE TITLE
[BUG] Companion Locks up after being idle

### ISSUE THREAD

**Issue by kd8ssq** [bitfocus/companion#1314] opened 2020-12-13 16:43 UTC
**Describe the bug**
We use the computer that companion is installed on 3 times a week.  When coming back to the computer after a few days of it being inactive, none of the buttons on the stream deck are responding.  The Web interface will not load.  I have to kill the process and restart Companion in order to get it to be responsive again.  This only started happening with versions 2.1.1 and 2.1.2.

**To Reproduce**
The only steps I can say are to launch a fresh copy of Companion, use it for an hour and then lock the computer for a few days.  When I come back to use it after a few days, it’s unresponsive.

**Expected behavior**
Companion to be responsive after being inactive for several days. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Chrome 87.0.4280.88
 - Companion Version: 2.1.2

**Comment by krocheck** [comment] 2020-12-13 22:10
@kd8ssq did you not have this issue with v2.1.0?  Which modules are you using?

**Comment by kd8ssq** [comment] 2020-12-14 14:03
No I didn't have this problem with v2.1.0.

Active Modules
- vmix
- visca
- propresenter
- vicreo hotkey
- x32
- smartcast

Disabled Modules
- osc
- artnet
- unifi

**Comment by kd8ssq** [comment] 2020-12-30 15:43
Anyone have any ideas?  It's still happening every time I go back to use companion after a few hours of the computer sleeping.  Completely locked up.  Have to kill the app and re-open.

**Comment by kd8ssq** [comment] 2021-01-06 14:07
If there's no ideas, is it possible to roll-back to a previous version w/o having to manually rebuild the settings in companion?

**Comment by andreasjr** [comment] 2021-01-27 23:21
I'm having this issue too. A fresh install of Companion with the same settings across two Windows 10 PCs will freeze after a period of time. The period of time can range from an hour to a dozen hours, but every time I check the computers at the end of the day, it's frozen. Similar to kd8ssq, I have to force quit the app.

**Comment by kd8ssq** [comment] 2021-01-28 14:36
Glad to hear I'm not the only one @andreasjr.  What plugins are you running?

Yesterday I attempted to rollback to 2.1.1 and still had the same problem happen last night.  I tried to find a copy of 2.1.0 but I can't seem to find it.  Never had these problems with that version.  

Each time I have to kill the Companion process in Task manager, I see what looks to be half a dozen Companion processes (I'm assuming one per plugin).  I look for the one with the highest memory utilization (which is normally 450MB)+ and kill it and it kills everything.

I really don't want to try rebuilding everything fresh because I have lot of configuration.

**Comment by josephdadams** [comment] 2021-01-28 14:40
Is anyone on Mac or Linux having this issue?

**Comment by Julusian** [comment] 2021-01-28 14:40
If you are able to, could you try disabling the instances one by one until you either run out or it stops happening.
It is likely to be caused by one of them rather than the main part of companion, so knowing which one to start looking in would be a big help.

Is this only happening once the computers go to sleep? If so, then it may not be a module but some bad handling of sleep

**Comment by andreasjr** [comment] 2021-01-28 14:47
@kd8ssq I'm guessing the process with the highest memory utilization is the 'host' process-- it's an electron app, and I think? that's how they work.
I installed a build of the latest Windows pre-release (2.2.0 c13b28a-2814) last evening and it's still running smoothly so far (it would have frozen by now)-- so I don't know what to make about that.

My modules are:
-atem
-visca
-roku-tv x2
-x32
-tcp-udp x3 (only because the IP2IR module wouldn't work)
-VICREO hotkey
-OBS

 I don't know if this is the case for you, but sometimes my devices aren't online (like the x32), and that builds up quite a large log in the dashboard. I wonder if there might be a memory leak in that? Just speculation.

@josephdadams I have a Mac so I can try it on that too.
@Julusian, I've disabled all but one or two of the modules and the issue still happens. I originally attested the crash to the roku module, as that would usually throw an error unless disabled. However, disabling those modules still caused the app to freeze.

**Comment by kd8ssq** [comment] 2021-01-28 14:49
@josephdadams I only run Companion on my Windows machine

@Julusian I thought about trying that today to see if it did anything.  I don't put my computer to sleep.  They're just locked till the next time they're needed.

@andreasjr Yes, I have at least 2 modules that are trying to constantly connect to "offline" devices (x32 and ProPresenter).

**Comment by andreasjr** [comment] 2021-01-30 22:06
@kd8ssq I received your comment yesterday and went to check on my setup. The beta version of Companion I was running had also frozen. So I did what you did, and disabled the modules that keep trying to reconnect (x32, OBS, and sometimes one of the roku modules). I just checked the setup more than 24 hours later, and Companion is still running; that's longer than it's run in a while. So, this leads me to suspect there's some sort of timeout crash or memory leak bug (either related to the constant 'reconnecting' or the log that gets built as a result). I'll keep an eye on it.

I recently added Vicero after my problems started, so I don't think that's the issue. The version I'm running is 2.0.9.
The modules that lose connection are primarily x32 and OBS (that's a whole other issue, unrelated to anything with Companion), with roku and some IP2IR sometimes losing connection, but that hasn't been consistent.

I added in instance enable and disable functions to certain buttons I set up so that the setup can still be used (e.g. instead of pressing a button to mute an input on the x32, it enables the instance, waits some milliseconds, and then runs the action. It's a toggle, so pressing it again mutes the input and then disables the instance). I'll check in and let everyone know how that goes.

**Comment by smayberry** [comment] 2021-01-31 20:19
Just anecdotally, we've been having random lockups since starting to use the roku module. But, I also updated companion at the same time and haven't tried removing roku to confirm it is to blame.

**Comment by kd8ssq** [comment] 2021-02-01 14:13
@andreasjr I re-enabled all my modules except for the x32 on Friday and everything stayed online w/o issue until we re-enabled the x32 module for a service on Sunday morning and left it enabled. The x32 was shutdown around 12:15, but the module was still enabled.  When I checked the computer again at 6pm, Companion was locked up.  I ran the same test again and powered off the x32 around 7:30pm and this morning, Companion is locked up.  

I think you're on the right track.  While I don't see connection errors in the log once I turn off the x32, to me, that seems to be the only logical explanation.  

@smayberry is your roku always online, or does it go to sleep?

**Comment by smayberry** [comment] 2021-02-01 14:25
It is not always on, and  it does seem like some modules do not handle connection errors very gracefully.

**Comment by kd8ssq** [comment] 2021-02-01 14:40
Thanks @smayberry.  We seem to be on to something.  I never had this problem with v2.1.0 or earlier.  We always had a handful of modules disconnected but never had Companion lock up before.  I was hoping to roll-back to 2.1.0 when everything worked, but I can't seem to find the old executables. I can see the source code, just not the installers.

**Comment by josephdadams** [comment] 2021-02-01 18:03
Regarding the Roku module, I added a lot of try/catch and other methods to hopefully help catch these issues better - I did that back in October, so if you're using the latest version of that module and having issues with it specifically, let me know.

**Comment by kd8ssq** [comment] 2021-02-03 13:40
Well, I left everything else enabled except the x32 module on Monday and when I checked this morning, everything was still responsive.  I even have 2 other modules that are trying to connect to offline devices (vmix and propresenter).  I'm not sure if the underlying issue is with the x32 module or how companion handles something from the module.

**Comment by Julusian** [comment] 2021-02-03 17:38
I think this should be fixed in 2.2.0-7002c50-2849. When trying to reconnect to the x32 it wasnt cleaning up old connections properly

**Comment by kd8ssq** [comment] 2021-02-03 19:14
@Julusian Awesome!  Thank you.  Looking forward to testing.

**Comment by Julusian** [comment] 2021-02-17 20:49
Has anyone seen this issue again since that change?

**Comment by kd8ssq** [comment] 2021-02-18 18:37
@Julusian once I applied the version w/ the fix, I have not experienced this issue anymore.  Thanks for getting this resolved!

**Comment by Julusian** [comment] 2021-02-18 19:23
@kd8ssq happy to hear.
Ill close this then

**Closed by Julusian** 2021-02-18 19:23 UTC
Labels: BUG, Question

**Comment by BigJinge** [comment] 2021-12-19 16:49
Just an FYI, the "Companion hanging / locking due to constantly checking for a device that hasn't come up yet" issue is still present in 2.2.x

We had it this morning where we hadn't turned on a PTZOptics camera for twenty mins or so. When we did, Companion buttons worked for five minutes then no Companion buttons would work. We power cycled the server and it worked again without hanging, no doubt because the camera was already on.

Do I raise a new case?

**Comment by BigJinge** [comment] 2022-01-21 04:11
Bump.
