### ISSUE TITLE
[BUG] Companion *PI* should not be recommending upgrades to 2.4.2

### ISSUE THREAD

**Issue by scotttroyer** [bitfocus/companion#2353] opened 2023-03-01 21:22 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have two installations of Companion PI—v2.4.1 and v2.2.2. Both were recommending upgrades to v2.4.2, which is not currently possible on PI. Currently, v2.4.1+70 is the latest stable available for PI.

Running `sudo companion-update` on the v2.4.1 forced an update to the database to v3.0 compatibility, which then required the OS to be upgraded to v3.0.

Unless I'm mistaken, I think Companion Admin on Companion PI installations should NOT be recommending upgrades until a proper v2.4.2 is available for the PI. 

![Screen Shot 2023-03-01 at 3 58 03 PM](https://user-images.githubusercontent.com/1580212/222266770-832a85ac-a4a3-4002-8648-a56c3a87eacf.png)
![Screen Shot 2023-03-01 at 3 55 44 PM](https://user-images.githubusercontent.com/1580212/222266772-0de5e3bc-b8d1-4546-80d1-19c3ede1a5b5.png)
![Screen Shot 2023-03-01 at 3 54 18 PM](https://user-images.githubusercontent.com/1580212/222266775-250dd947-2aad-4245-90d5-f8f7a2bdee75.png)

### Steps To Reproduce

1. Visit the Admin page of a Companion PI installation running a stable release (v2.4.1+70 or less).
2. See the "Hey! Version 2.4.2 is available. Update today!" alert at the top of the page.
3. Run 'sudo companion-update'.

### Expected Behavior

Installations of Companion PI should not have upgrade alerts in the Admin page.

### Environment (please complete the following information)

```markdown
- OS: Companion PI
- Browser: Firefox 109.0.1
- Companion Version: any Companion PI version v2.4.1+70 or less.
```

**Comment by Julusian** [comment] 2023-03-04 16:31
Duplicate of https://github.com/bitfocus/companion-pi/issues/6

**Comment by Julusian** [comment] 2023-03-04 16:32
When I made this change I was expecting 3.0 to have been released by now, so didn't expect it to have much impact. But it looks like I need to go back and make it work..

**Closed by Julusian** 2023-03-04 16:31 UTC
Labels: BUG
