### ISSUE TITLE
Implement protocol for automatic detection of devices on network

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#242] opened 2018-09-19 19:23 UTC
**Describe the feature**
Companion will either broadcast a are_you_there packet or just spend some time listening for a module to broadcast i_am_here packet (SSDP style etc.). Discovered devices can now be shown in a list for easy selection. Also consider supporting a unique identifier for the device, which could abstract away the need for the user to know the IP address, allowing automatic network configuration or a device IP change being automatically handled.

**Comment by dnmeid** [comment] 2018-10-01 12:13
Possibly a duplicate of #240

**Comment by josephdadams** [comment] 2019-08-22 19:16
Closing as this does seem to be a duplicate of #240, and MDNS support has been discussed and could be implemented down the road to speed up instance creation.

**Closed by josephdadams** 2019-08-22 19:16 UTC
Labels: DUPLICATE
