### ISSUE TITLE
Request: Feedback conditions (AND / OR)

### ISSUE THREAD

**Issue by BlackScreen** [bitfocus/companion#1327] opened 2020-12-16 08:23 UTC
**Describe the feature**
Feedback could use conditions like AND or OR to use for multiple feedbacks, insted of the stacked feedback which we have right now.

**Is this platform dependent (windows, mac, ..)?**
No.

**Usecases**
I could have used this a couple of times.
For example: I wanted to implement a status button, that shows, if multiple routings (input to output) on a Blackmagic Videohub are set as defined in the Companion.
In 1 > Out 1 **AND** In 2 > Out 2 and so on => Green light
If then In 2 goes to Out 1 the light would not be green.
I wanted to also use this for controling the routing of the ATEM multiviewer. I think this could be a very useful feature. :)

**Comment by dnmeid** [comment] 2020-12-28 19:22
There are some logic functions under development at the time. As far as I know nothing within the feedbacks itself, but I think some of your requested functionality will be available.

**Comment by BlackScreen** [comment] 2020-12-28 20:28
That sounds good, excited to try it out, when it is implemented.

**Comment by WesleyvN** [comment] 2021-01-02 12:52
Hi, 

I hope that the Logic Functions are coming soon! i cannot wait until i can implement them at some Feedbacks. i hope also that there will be a option to connect a logic (input ATEM Preview) directly to a Logic output (Tally information PTZ Cam). 

i cannot wait! 

Thanks in advance, Wesley

**Comment by Julusian** [comment] 2021-06-15 22:09
Duplicate of #372

**Closed by Julusian** 2021-06-15 22:09 UTC

**Comment by TVcameras** [comment] 2023-07-27 19:16
Hoping to use a logical condition (source A going to ATEM out AUX X **AND** source B going to ATEM AUX Y, etc.) for feedback to a button.  I am using Beta 6060, and do not see how to impliment this in the "Feedbacks" tab of the button(s).  Am I missing something?  Thanks!
