### ISSUE TITLE
Webpage for feedback & vairables in widgets style page display

### ISSUE THREAD

**Issue by Turnipisum** [bitfocus/companion#2654] opened 2023-11-18 17:22 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

![companion widgets](https://github.com/bitfocus/companion/assets/23130067/40bfe5da-ed42-4485-bcb1-dd79930975c7)

### Usecases

I would use this web display on most events and it would be very useful for other members of crew.

**Comment by Julusian** [comment] 2023-11-18 17:31
I think this is duplicate of https://github.com/bitfocus/companion/issues/2271 with some overlap to https://github.com/bitfocus/companion/issues/1429

I agree that this would be a useful feature, but it is waiting for someone to start thinking about what needs to be done to make it and to start prototyping it.

**Closed by Julusian** 2023-11-18 17:31 UTC
