### ISSUE TITLE
Buttons aren't redrawn when using "set surface to page" internal action

### ISSUE THREAD

**Issue by VanSorgenAudio** [bitfocus/companion#729] opened 2019-07-04 12:31 UTC
Compamion 2 v1.3.0 (1a7592b-1203)

**Describe the bug**
I made a button (we call this Button 'A1'):
 1ste Action: QLab Start Cue #
 2nd Action: delay 250ms
                     internal: Set surface to page 97

Button as PNG with a custom PNG

Button 'A2': (same position on the desk as 'A1')
 Action: internal: Set surface to page 98

Action Button '1A' works fine. When it goes to the new page the image of Button 'A1' doesn't change to the info of Button 'A2'). Even on a empty button, or on a programmed button. Button 'A2' works fine only the background is not refreshed. It doesn't matter if the new button style is None, Text of PNG.

 - OS: OSX 10.13.6
 - Browser: chrome
 - Versie 75.0.3770.100 (Officiële build) (64-bits)

With regards,
Gijs van Sorgen

**Comment by haakonnessjoen** [comment] 2019-07-04 15:06
Related or duplicate of #595

**Comment by josephdadams** [comment] 2019-08-26 00:50
This issue is friends with #595 and #769 :)

**Comment by PadaKwaak** [comment] 2020-01-08 12:17
I'm also having this issue with 2.0.0-8fe2222-1983 and Stream Deck XL where it does not update the button that was pressed when the button set the surface page.

The same happens for actions:
internal: Increment page number
internal: Decrement page number

Also, is it normal behaviour for the "pagenum" style button to take you to Page 1? In my opinion this button shouldn't be clickable or its actions should be configurable like a regular button

**Comment by Julusian** [comment] 2020-01-08 17:22
I have noticed this occasionally too.
It feels like a race condition in the ordering of redraws. I would guess this is only reported with the XL due to it having more draw and so the timings behave differently.
This is on a pi4 with a modified version of node-hid and the streamdeck library which improves draw speed (PR incoming once node-hid does a release) so it is less frequent, but still happens.

I can see the following flow of redraws occuring when I press and hold:
On press:
 * Flash of source button (pressed variant)
 * Target button (normal variant)
 * Source button just after the last button has redrawn (normal variant)
On release:
 * Target button (normal variant)

If I dont hold and very quickly release then I think it is simply missing the last redraw.

**Comment by istnv** [comment] 2020-01-10 20:55
> Also, is it normal behaviour for the "pagenum" style button to take you to Page 1? In my opinion this button shouldn't be clickable or its actions should be configurable like a regular button
The PAGE button has always been goto page 1, like a HOME key.

**Comment by josephdadams** [comment] 2020-03-16 21:21
@istnv can we close this?

**Comment by istnv** [comment] 2020-03-16 21:25
Yes. There were a couple of interacting modules in separate pull requests. All have been merged.

**Closed** 2020-03-16 21:53 UTC
Labels: BUG
