### ISSUE TITLE
swap buttons

### ISSUE THREAD

**Issue by PLRNA** [bitfocus/companion#2624] opened 2023-10-27 07:50 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Add another function to handle buttons. We have Delete, Copy and Move, a way to swap 2 buttons in the same page would be great.
It could work quite like the move function, except that the button in the destination place should move to the source place. 

### Usecases

For now, you need at least 1 space left in the page to swap buttons, using this space as a pivot. But what if the page is full, and you just want to swap 2 buttons ? I tried with the move function, and i lost a button !!!

**Comment by Julusian** [comment] 2023-10-27 07:51
Duplicate of #781

**Closed by Julusian** 2023-10-27 07:51 UTC

**Comment by istnv** [comment] 2023-10-27 08:31
FYI: You can change pages after selecting the button to copy/move.
