### ISSUE TITLE
Dual Streamdecks

### ISSUE THREAD

**Issue by superchache89** [bitfocus/companion#1697] opened 2021-08-26 04:13 UTC
I have a stream deck xl and a standard stream deck. I’d like to use the two in tandem within companion but switch out to other profiles using the elgato stream deck profiles. I know you can do this natively, but when I have my stream decks connected and running the elgato app, companion sees them as once device and mirrors the displays. I have to quit the elgato app and rescan usb devices to allow companion to see two separate devices so that I can use separate pages at the same time. However, I lose the ability to switch profiles at this point. Is this a bug, or am I missing something?

**Comment by Julusian** [comment] 2021-08-29 16:35
This is as designed
Using the streamdeck software does not let companion differentiate streamdeck easily, so they are treated as one device

**Comment by josephdadams** [comment] 2021-09-02 19:32
Closing since this is not a bug nor a feature request.

**Closed by josephdadams** 2021-09-02 19:32 UTC
Labels: BUG
