### ISSUE TITLE
Typo in Finish Wizard "Conections" should be "Connections" [BUG]

### ISSUE THREAD

**Issue by dodgyrabbit** [bitfocus/companion#2119] opened 2022-09-09 12:10 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a typo in the window as shown below
![companion-spelling](https://user-images.githubusercontent.com/518187/189346635-27c55fc7-35bc-4663-90fd-10c4a0e9dba7.png)

### Steps To Reproduce

1. Do a fresh install
2. Follow the setup wizard
3. Observe the typo on the final step

https://github.com/bitfocus/companion/blob/ccea40c77d9740ec2e43033cc404341ccde7e437/webui/src/Wizard/FinishStep.jsx#L20

### Expected Behavior

Spelling should be corrected

### Environment (please complete the following information)

```markdown
- OS:Ubuntu 20.04
- Browser:Chrome 105.0.5195.102 
- Companion Version: It's like this in main
```

**Comment by dodgyrabbit** [comment] 2022-09-09 12:10
Happy to submit a PR if everyone's busy :)

**Comment by Julusian** [comment] 2022-09-09 22:28
A fix has already been made for this

Duplicate of #2115

**Closed** 2022-09-09 22:28 UTC
Labels: BUG
