### ISSUE TITLE
Current PAGE and BUTTON number as internal variable

### ISSUE THREAD

**Issue by mideka** [bitfocus/companion#2505] opened 2023-06-27 08:46 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Add current page number as internal variable.
Add current button number as internal variable.

### Usecases

Make reoccurring buttons and behaviour based upon button and page location. Easy programming without the need to update dozens of buttons (i.e. I make recall presets for several camera on different pages.

**Comment by Julusian** [comment] 2023-06-27 08:58
Duplicate of #1909

**Closed by Julusian** 2023-06-27 08:58 UTC
