### ISSUE TITLE
Updating to 3946 deleted all time-based triggers

### ISSUE THREAD

**Issue by elliotmatson** [bitfocus/companion#1942] opened 2022-02-24 20:25 UTC
Updating to 3946 after seeing issue #1927 deleted all my time-based triggers, and upon adding any trigger, I get the following error:

`"object null is not iterable (cannot read property Symbol(Symbol.iterator))"`

I've tried rolling back, and get a similar error

**Comment by Julusian** [comment] 2022-02-24 20:29
Could you share your db file with us? 
If you dont want to attach it here, either pm it to me on slack or email it to `git@julusian.co.uk`

**Comment by ematson5897** [comment] 2022-02-24 20:46
Just emailed it to you!

**Comment by jsnyder886** [comment] 2022-02-26 00:10
Just updated from 3929 to 3697 with same result with regard to all of my triggers being just gone.  I was able to roll back to 3929 and have them come back to life thankfully.

It's worth nothing that while most of my triggers are time based, a few are not.  In 3967 everything with regard to my trigger configuration was entirely gone.

**Comment by Julusian** [comment] 2022-02-26 14:49
Looking at the provided db, it contains this mess which will be the problem:
```
{
            "title": "Sunday at 0850",
            "type": "tod",
            "config": {
                "0": {
                    "0": {
                        "0": {
                            "0": {
                                "0": {
                                    "0": {
                                        "0": {
                                            "0": {
                                                "0": {
                                                    "0": {
                                                        "0": {
                                                            "0": {
                                                                "0": {
                                                                    "0": {
                                                                        "0": {
                                                                            "0": {
                                                                                "0": {
                                                                                    "0": {
                                                                                        "time": "",
                                                                                        "days": []
                                                                                    },
                                                                                    "time": "0"
                                                                                },
                                                                                "time": "08"
                                                                            },
                                                                            "time": "08:"
                                                                        },
                                                                        "time": "08:5"
                                                                    },
                                                                    "time": "08:50"
                                                                },
                                                                "time": "08:50:"
                                                            },
                                                            "time": "08:50:0"
                                                        },
                                                        "time": "08:50:00"
                                                    },
                                                    "days": [
                                                        0
                                                    ]
                                                },
                                                "days": [
                                                    4
                                                ]
                                            },
                                            "time": "0"
                                        },
                                        "time": "08"
                                    },
                                    "time": "08:"
                                },
                                "time": "08:5"
                            },
                            "time": "08:50"
                        },
                        "time": "08:50:"
                    },
                    "time": "08:50:0"
                },
                "time": "08:50:00"
            },
            "last_run": "2022-02-20T14:50:00.683Z",
            "disabled": false,
            "actions": [
               ...
            ],
            "id": 4,
            "config_desc": "<strong>Sun</strong>, undefined"
        },
```

**Comment by Julusian** [comment] 2022-02-26 15:11
Please try build 3971.
I dont know what introduced that corruption, I cant reproduce that. But I believe they were 'missing' because when we were generating the strings to display in the ui it was throwing an error. Instead it will use 'Error' in the string.

After updating to 3971, check the triggers page for any which say 'Error' as they will need manually fixing.

If you can reproduce the steps to get into this broken state then I can look at fixing that too

**Comment by Julusian** [comment] 2022-03-01 10:27
Yeah, I assume the source of the corruption was fixed by the other fix.

I don't think there is anything we can do to fix up corrupted data, so Im going to close this

**Closed by Julusian** 2022-03-01 10:27 UTC
Labels: BUG
