### ISSUE TITLE
Editing a disable instance causes a error

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#207] opened 2018-08-20 00:25 UTC
**Describe the bug**
Editing a disabled instance creates a JS error box, making the HTTP interface frozen

`Uncaught Exception:
TypeError: Cannot read property 'config_fields' of undefined
    at Socket.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/instance.js:210:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /Applications/Companion.app/Contents/Resources/app.asar/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**To Reproduce**
1. Disable a instance
2. Edit it

**Comment by haakonnessjoen** [comment] 2018-08-20 07:28
Duplicate of #190

**Closed by haakonnessjoen** 2018-08-20 07:28 UTC
