### ISSUE TITLE
Just updates to companion 3 from companion 2.2 - Cycle mode in tablet view no longer exists?!

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion#2597] opened 2023-10-08 15:44 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I used to be able to access a tablet view, which had buttons on the top, to flip between pages. This is no longer possible on companion v3. 
Back in 2.2, i even created a specific ipad.html view, that was optimized for use with old ipads. (Check discussion [here](https://github.com/bitfocus/companion/pull/1471))

How do i get this functionality (or something similar) with v3?

### Usecases

Anyone that doesn't have a streamdeck and want to use an old ipad as a streamdeck emulator.

**Comment by Julusian** [comment] 2023-10-08 21:48
Duplicate of https://github.com/bitfocus/companion/issues/2509

Have you tried the emulator in 3.0? It has been restyled to match the tablet/web views

**Closed by Julusian** 2023-10-08 21:48 UTC

**Comment by yurividal** [comment] 2023-10-08 22:20
@Julusian yes, but with that view, there is no way to cycle between pages, unless I dedicate 2 buttons on each of my pages to flip to the next/previous page.
It was nice having the next/previous button on top of the stream deck buttons. 
So, currently, there is no way of doing that?

**Comment by yurividal** [comment] 2023-10-08 22:22
The duplicate post you linked me to has exactly what I am referring to. The OP managed to design his own page, and I have tested it. The only problem is that, since it's not running native in companion, and it's using the API, it's significantly slower that the native views.
Do you guys have plans of implementing such a view again?
