### ISSUE TITLE
Add actions dropdown should be a structured list

### ISSUE THREAD

**Issue by CrazySimz** [bitfocus/companion#510] opened 2019-02-26 16:38 UTC
**Describe the feature**
Put a two layers concept to select the functions of the button. 

**Is this platform dependent (windows, mac, ..)?**
Companion App

**Usecases**
When you have many projectors or device with many Function. Layer 1 Device - Layer 2 - Function

Example :
List 1 : Projo 1 - Projo 2 - Projo 3 - Projo 4 - Projo 5 - Projo 6 - Kipro 1 - Kipro 2 - Kipro 3 - Kipro 4   
List 2 : Shutter - Test Pattern - Power - Etc.

**Comment by haakonnessjoen** [comment] 2019-02-26 18:51
If you use "internal: change page", you can have each projectors control functions on separate pages, and have each projector button change to the corresponding page for that projector.

**Comment by CrazySimz** [comment] 2019-02-26 20:16
Now
![now](https://user-images.githubusercontent.com/42504406/53443335-7a0efd80-39d9-11e9-9282-8f1e16c8c22a.jpg)


The example

![example 1](https://user-images.githubusercontent.com/42504406/53443355-82ffcf00-39d9-11e9-9471-97e2da742707.jpg)

**Comment by dnmeid** [comment] 2019-03-02 17:07
This is related to #89 but not a 100% duplicate. I like the hierarchical drop down idea.

**Comment by josephdadams** [comment] 2019-08-25 18:52
This is essentially a duplicate of #346, however I will leave this one open for the picture mockup being helpful.

**Comment by Julusian** [comment] 2022-09-05 20:55
This has been solved in 2.3.0 with a browser modal #2014

**Closed by Julusian** 2022-09-05 20:55 UTC
Labels: Enhancement, area/gui
