### ISSUE TITLE
Persistent Buttons

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#1837] opened 2021-12-28 23:58 UTC
Having an option to have a button on all pages in the same position or specified pages 1-10,16,99 these being persistent and change one and it does all. 

Also have copy to all pages or selected pages. These being none persistent and changes are not replicated to all pages.

**Comment by Julusian** [comment] 2022-05-12 20:46
Duplicate of #27

**Closed by Julusian** 2022-05-12 20:46 UTC
Labels: Enhancement
