### ISSUE TITLE
Variable to use Current Surface by ID/Name/# or IFTTT buttons

### ISSUE THREAD

**Issue by WillieDaWonka** [bitfocus/companion#3164] opened 2024-12-01 05:09 UTC
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

As per title, I'm currently trying to "lock down" some controls depending on what emulator/surface is being used by an operator. While there is a way for the action `internal: Surface: Set to page` and similar to see surface ID's, it'd be great for feedback variables or actions that support variables to use, for example, `$Internal_Surface_Current_ID`. Another way of doing this (I should probably open another thread), implement a way for buttons to do If This Then That actions, for example:

> If
Surface = Room-1_Streamdeck
Then
Action set = # 1

> If Surface = Room-2_Streamdeck
Then
Action set = # 2

### Usecases

Use case:
- I'd like to use the "Generic: Blink" module to check the variable `$(this:surface_id)` so the operator of each device will be guided to press the correct buttons.
- Currently have multiple pages doing essentially the same things, but have certain elements taken off each to prevent accidental presses (different zones that combine into a larger zone).

Current workaround:
- My current workaround has been to set every surface to have their startup page/current page as where they should be, but with clients running around just grabbing iPad's, this gets very clunky as I have to go there and re-open the appropriate emulator page.

Backstory:
- Current inventory of 60+ connections
- 12+ different emulators/Stream Deck's
- I'd like to condense the pages I have now (approaching 70+ pages full) down to 20+ by having the buttons be specifically for the surface that is being viewed and used from

This starts to add up real quick as we open up remote controls for our expansive Crestron system with drape motors, camera lifters, etc.

The "not enough pages" problem is absolutely niche, it will benefit other combination of things as well like a pseudo "Users" setup without needing Companion Satellite/Cloud that might get too resource heavy and difficult to have everything always updated to latest configs. Even then, Satellite/Cloud doesn't help my use case as we use more Emulators than physical Stream Deck's.

**Comment by dnmeid** [comment] 2024-12-01 22:14
Let me break this down from bottom to top:

> The "not enough pages" problem

Starting with 3.5 you can have any number of pages, it is already in the beta.

> I'd like to condense the pages I have now (approaching 70+ pages full) down to 20+ by having the buttons be specifically for the surface that is being viewed and used from

You can do this easily by expanding the grid and offsetting individual surfaces. With this style you can e.g. arrange your surfaces side by side and reflect that in the programming. I don't know your application but one drawback could be that the offset is permanent and if you want to share some buttons between offset surfaces, you'll have to duplicate them.

> If This Then That actions

Duplicate of #1052  
Conditional action workflows are not to far away. Currently you can do conditional workflows with triggers or with "press button if condition..."

> it'd be great for feedback variables or actions that support variables to use, for example, `$Internal_Surface_Current_ID`

Based on the syntax of the proposed variable this would be a global variable and a global variable is definitely not something which would help for your problem.  
Let's assume you mean a local variable like: `$(this:surface)`  
That would be a feature request, that could be done and is fairly simple.

**Comment by WillieDaWonka** [comment] 2024-12-03 21:12
@dnmeid

> You can do this easily by expanding the grid and offsetting individual surfaces. With this style you can e.g. arrange your surfaces side by side and reflect that in the programming. I don't know your application but one drawback could be that the offset is permanent and if you want to share some buttons between offset surfaces, you'll have to duplicate them.

The workaround that would definitely be yet another feature request of "offset grid for this surface"

@Julusian 
> But I suspect you want to be able to use this variable in feedbacks, which isn't possible and isn't planned to change currently. We draw each button once, and use that drawing for every streamdeck/surface.
This might change at some point, but is an even larger architectural change to be made at some point

A colleague and I was just having a discussion after I sent this and we came at that same conclusion, glad to see that we were right

**Comment by dnmeid** [comment] 2024-12-04 19:36
>> But I suspect you want to be able to use this variable in feedbacks, which isn't possible and isn't planned to change currently.

> A colleague and I was just having a discussion after I sent this and we came at that same conclusion

OK, then I close this as not planned.

**Closed by dnmeid** 2024-12-04 19:36 UTC
Labels: Enhancement, area/internal
