### ISSUE TITLE
[BUG] Updating to v3.4.0 broke support for unicode fonts in Button text strings

### ISSUE THREAD

**Issue by themanjotsingh** [bitfocus/companion#3031] opened 2024-09-12 21:29 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On v3.3.1 and prior, unicode fonts rendered fine for button text as shown in image1. 

![image1](https://github.com/user-attachments/assets/fd6e380e-d387-47eb-9b78-a7c74b3bf81c)

After updating to v3.4.0, they do not render properly as shown in image2. 

![image2](https://github.com/user-attachments/assets/121aa95b-c73d-4510-81ba-e825b5887a92)

I have checked by exporting and importing to an older install to confirm that I am able to still see the text when viewing from older install. Same pc/browser, nothing else has changed.

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Firefox 130.0
- Companion Version: v3.3.1 -> v3.4.0
```

**Comment by Julusian** [comment] 2024-09-12 21:37
This is annoying to hear. But at least it's not doing what 3.3 did when encountering some unicode fonts which was to crash.
I'll take a look into this soon. Could you provide an example bit of text that doesn't work in a comment of this issue? That should make it easy to reproduce your exact issue and confirm when it is fixed (as other characters do work)

**Comment by themanjotsingh** [comment] 2024-09-13 01:41
Yes, true. Better than crashing. We'll write in English for now.

Here's a few examples of strings: ਤਖ਼ਤ, ਕੀਰਤਨ

Language is Panjabi/Punjabi, written in the Gurmukhi Script.

Thanks for your help!

**Comment by RabbitJun** [comment] 2024-09-13 03:17
I also noticed that this doesn't work in Chinese v3.3.1 -> v3.4.0。'节目' has become □□

**Comment by jwetzell** [comment] 2024-09-13 22:36
This break was introduced with this #2785.

**Comment by Julusian** [comment] 2024-09-16 11:33
What has happened is that the old canvas library would fallback to using system fonts for any characters not included in the font used by companion. But the new canvas library does not do that.

I don't remember if this was semi-intentional, because what it finds on the system varies depending on OS, which makes portability of configs inconsistent.

I've added the Gurmukhi and Simplified Chinese portions of the font we use, so the examples provided here now draw as expected.

If anyone has examples of another character set that is missing, open an issue and it can be added.

This is in the betas now, and will be in 3.4.1 soon

**Closed by Julusian** 2024-09-16 11:33 UTC
Labels: BUG

**Comment by scientastic** [comment] 2024-10-03 05:53
I can't get Korean characters (한글) to show:

![image](https://github.com/user-attachments/assets/5caae455-ba2a-4128-bbdb-f324c433fac6)

**Comment by Julusian** [comment] 2024-10-04 20:58
I have added the korean character set, which will be in the betas shortly and next release

**Comment by scientastic** [comment] 2024-10-26 01:35
Thanks! Confirmed in 3.4.2 👍
