### ISSUE TITLE
Reorder Instances

### ISSUE THREAD

**Issue by ianmdesign** [bitfocus/companion#1111] opened 2020-05-23 14:11 UTC
**Describe the feature**
The ability to sort instances into your prefered order after creating them.

**Is this platform dependent (windows, mac, ..)?**
Not dependent.

**Usecases**
If a new Instance is added later on after initially creating your configuration, it may not make sense to place this instance at the bottom of the list, depending on your workflow.

**Comment by Julusian** [comment] 2022-10-02 16:24
Duplicate of #1283

**Closed by Julusian** 2022-10-02 16:24 UTC
Labels: Enhancement, area/gui
