### ISSUE TITLE
Feature Request: "Master Memory" Button

### ISSUE THREAD

**Issue by Jockgerman** [bitfocus/companion#251] opened 2018-09-21 11:12 UTC
**Describe the feature**
Set a button to activate other buttons. 
This way you can pre configure the deck and just adjust to the show without setting new delay times etc.

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
Page 1 Control Page
Page 2 Video Page (livecore)
Page 3 VT Page (SCS)
Page 4 Lighting Page (Artnet)

**1.1 Welcome**
   Activates: 2.5, 3.1, 4.4

**1.2 PPT1**
Activates: 2.1, 2.4, 4,2

**1.3 PPT2**
Activates: 2.2, 2.4, 4.2

**1.4 Video 1**
Activates: 2.3, 2.4, 4.4

2.1 PPT1 
2.2 PPT2
2.3 Video
2.4 Global Take
2.5 Frame 1
2.6 Frame 2
2.7 Frame 3

3.1 Play Cue 1
3.2 Play Cue 2 
3.3 Play Cue 3
3.4 GO!

4.1 Stage 100%
4.2 Stage 80%
4.3 Stage 50%
4.4 Stage 15%

**Comment by willosof** [comment] 2018-09-21 11:38
Duplicate of #229

**Comment by josephdadams** [comment] 2019-08-22 21:41
There’s internal actions to press other buttons. Might be some bugs, but there’s issues for that. We can close this request since the feature does exist.

**Closed by josephdadams** 2019-08-22 21:41 UTC
Labels: DUPLICATE, Internal, TODO
