### ISSUE TITLE
Stream Deck Access to Companion through network

### ISSUE THREAD

**Issue by CCL-DanielLewis** [bitfocus/companion#2081] opened 2022-07-31 07:22 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I have created a Companion instance on my home server, but my Stream Deck is connected to my main computer. I want to be able to tell the Stream Deck to look for Companion at 192.168.0.xxx instead of localhost

**Comment by Julusian** [comment] 2022-07-31 11:54
Duplicate of https://github.com/bitfocus/io.bitfocus.companion-plugin/issues/2

**Closed by Julusian** 2022-07-31 11:54 UTC
