### ISSUE TITLE
Request:Keyboard  keystroke input

### ISSUE THREAD

**Issue by Croonquist** [bitfocus/companion#387] opened 2018-12-05 08:57 UTC
This would be quite useful for PowerPoint remotes. To enable/disable remote I on main and backup machine depending on which is live on PGM. 
And for when you have multiple computers you want to control simultaneously from a master cue/ Perfect Cue remote system.

**Comment by BasilChessman** [comment] 2018-12-17 15:16
Yes, please!

**Comment by BasilChessman** [comment] 2019-01-01 16:33
Does anyone know if this is in development?  If it's not, can anyone suggest a way to have a Perfect Cue button press trigger a Companion button press?

**Comment by willosof** [comment] 2019-01-19 15:53
People use octopus listener for this today. And, later this year there will probably a companion-listener as well.

**Comment by BasilChessman** [comment] 2019-01-19 16:36
> People use octopus listener for this today.

Perhaps I am misunderstanding, but how would Octopus listener be used to execute a Companion button press?  I can currently do the opposite (have Companion send a keystroke via octopus).  The end goal is to have a keyboard key press trigger a companion button.

**Comment by josephdadams** [comment] 2019-08-23 01:50
Duplicate of #204. Closing.

**Closed by josephdadams** 2019-08-23 01:50 UTC
Labels: Module, Request
