### ISSUE TITLE
More Layers for button visuals/images

### ISSUE THREAD

**Issue by joezimjs** [bitfocus/companion#2676] opened 2023-12-15 16:52 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I'd love to be able to layer background images on each other. I'd like to be able to set a background color, then add a little "glow" gradient layer on top of that (semi-transparent), then throw other "decorations" like borders or dot indicators on top of that, then throw an icon on top of that, then finally the text on top of that. 

This way I can create one image for each state of each layer instead of having to combine multiple layers together into each possible combination of layers and exponentially growing the number of images needed.

Also, when this is implemented, I don't see any reason we can't reorder these layers and potentially even be able to move text below some image layers or have multiple layers of text so they can be positioned, sized, and colored in different ways and potentially make it easier to create expressions because they may only need to contain part of the text, rather than concatenating strings into expressions. These layers should all be able to be named so they can be more easily identified without seeing the details of them. And feedback would be able to adjust individual layers, including showing/hiding them and potentially re-ordering them.

Finally, to wrap this all up into an even more amazing feature: be able to save a set of layers as a template so if you have a few layers that you want to use in a lot of different buttons, you don't need to  re-set it all up or copy/paste an entire button, potentially wiping out the actions, etc. that may have already existed for that button.

I'm not under the impression that this will be quick or easy, so I appreciate any amount of consideration you give it.

### Usecases

This is especially useful for people who don't have image editing expertise or the time to learn it. If someone finds something like this:

![blank](https://github.com/bitfocus/companion/assets/1313898/d107e400-cd2b-4646-a504-e7fc0c72329f)

that they want to use for the background for a lot of buttons and find a different set of icons they can lay over the top and maybe they want a colored status indicator icon to put in a corner.

I can see tons of way this can enhance the button-making experience.

**Comment by dnmeid** [comment] 2024-02-24 13:08
Duplicate of #262

This feature is on the roadmap https://github.com/orgs/bitfocus/projects/4/views/1

**Closed by dnmeid** 2024-02-24 13:08 UTC
Labels: Enhancement, area/graphics
