### ISSUE TITLE
Web Buttons :: "internal: Set surface with s/n to page" to work the same way as in emulator

### ISSUE THREAD

**Issue by phwecker** [bitfocus/companion#2034] opened 2022-05-30 14:39 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

the action "internal: Set surface with s/n to page" works fine for surface / emulator, but it would be very helpful if a button defined with this action to also navigate when using the web buttons / new web buttons ... or to create a similar action for the web buttons. 

### Usecases

as a user, i would like to be able to create buttons that navigate based on page number, not just page up / down, when using a touch screen (not a surface or emulator) 

as an admin i would like to be able to create a setup that has the same navigation schema on a surface as with the web buttons.

**Comment by Julusian** [comment] 2022-05-30 14:46
Duplicate of #1071

**Closed by Julusian** 2022-05-30 14:46 UTC
