### ISSUE TITLE
Application arrangement

### ISSUE THREAD

**Issue by CrazySimz** [bitfocus/companion#206] opened 2018-08-19 01:29 UTC
I like your application so much. But maybe just splitting the menu in two part when you have to choose the fonction of the buttons. 

My idea is to put the content in 2 scrolling menu. One to select the device you want to talk and the second to select the function. It could be easyier to program when you have so much device with a long list of function.

**Comment by willosof** [comment] 2018-09-11 00:11
Noted and planned!

**Comment by willosof** [comment] 2018-09-14 16:54
Duplicate of #118 ish.

**Closed by willosof** 2018-09-14 16:54 UTC
