### ISSUE TITLE
Ability to enable/disable triggers with buttons

### ISSUE THREAD

**Issue by DoughnutWuff** [bitfocus/companion#1957] opened 2022-03-11 13:08 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I've been using the beta builds of Companion for a while now, and have recently started using triggers to automate tasks I'd often forget about (recording in vMix/Livestream Studio, for example, or setting a hyperdeck to record).

I noticed that you can enable/disable the triggers individually within the triggers tab, just like instances.
Instances can be enabled/disabled using buttons, however this functionality is not available for the triggers.

When I've got some time I might have a look at doing this myself and making a pull request, however have raised it just for now in case anyone has any other ideas?

### Usecases

This would be super handy for "arming" triggers with buttons. I don't always want a trigger to activate, so having it available as a button would be amazing.

**Comment by Julusian** [comment] 2022-03-11 13:52
Duplicate of #1894

**Closed by Julusian** 2022-03-11 13:52 UTC
