### ISSUE TITLE
Comments in configuration

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#1794] opened 2021-11-21 15:41 UTC
**Describe the feature**
Add a comments field to button action and trigger action configuration, as well as to the button and triggers themselves.

**Usecases**
Some of my button configs and trigger configs are pretty complex.  They mean something to me because obviously I set the system up.  However, it isn't immediately clear to anyone else that may sit at the console as to what I was thinking at the point it was setup. 
 Also, sometimes enough time has passed since I programmed something myself that I don't recall exactly what led me down a particular road.  Adding a comment field to each button/trigger action and perhaps to the actual button or trigger itself would go a long way towards improving communication between team members working towards the same goal.

**Comment by krocheck** [comment] 2021-11-24 01:44
Duplicate of #760

**Closed by krocheck** 2021-11-24 01:44 UTC
