### ISSUE TITLE
Explicit enable and disable of buttons as core feature to companion, previous request for same seem to have been closed or disabled with no qualification?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [bitfocus/companion#2966] opened 2024-07-28 03:23 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

Related, at least on initial review of titles...
#2911
#2076
#1650
#1568
#908
#351

### Describe the feature

Reference above, I would say 908 is key.

### Usecases

Please review 908 and 2911, there are several detailed discussions on various use cases.

And...

This has been requested as least twice, and referenced several times more, the explicit ability to enable and disable buttons as internal to companion, not module specific.  And both 908 and 2911 have been closed for example?  Not understanding why they have been closed, 2911 as duplicate, OK get that.  But 908 should still be open, no?  Even if all the others qualified as duplicates, would 908 not be kept open until implemented?  Or explicit explanation of why it will not be implemented, not be in order?

**Comment by Julusian** [comment] 2024-07-28 09:09
#908 is still open and is waiting for someone to propose how it should behave, in order to be user friendly.

So closing this as a duplicate of #908

**Closed by Julusian** 2024-07-28 09:09 UTC
