### ISSUE TITLE
Add support for Scheduled/Timer/Triggered operations within the server-client application.

### ISSUE THREAD

**Issue by joe-tamburello** [bitfocus/companion#318] opened 2018-11-02 15:50 UTC
**Describe the feature**
Would it be possible to introduce a schedule/timer/triggered option within Companion? Meaning a button/operation can run automatically (via the server-client and not necessarily from a Steamdeck). Ideally it would be nice to schedule something to run at a specific time automatically... another user (cxselph) suggested something similar to what QLab does where you can trigger cues/buttons based on time of days of the week.

**Is this platform dependent (windows, mac, ..)?**
This would be something set within the GUI, so it would have to work for both the Windows/Mac platform. 

**If documentation is required to implement, do you know where to find it?**
Attached is a screenshot from QLab (provided by cxselph)

<img width="539" alt="screen shot 2018-11-02 at 11 05 02 am" src="https://user-images.githubusercontent.com/25694214/47925192-8c45b880-de8b-11e8-8ab7-8c3e20f296ea.png">

**Usecases**
The ability to trigger any button on a scheduled bases is pretty self explanatory, but for one of my specific use cases, I would like the ability to automatically switch 'sources' when using Companion with our BMD SmartVideoHub and BDM ATEM Switcher... I would use this to automatically rotate what source is being viewed on a dashboard(s) (which are wall mounted TVs). We would do this for both "day-to-day" situations as well as "event" situations... today, we use both a BMD SmartVideo Hub (for dashboards) and a BMD ATEM switcher (for live events) for the backend hardware and we achieve this behavior today by manually change sources via Steamdeck/GUI-emulator, but it would be really awesome if this could be automated. 

Thanks for considering!
-giuseppe

**Comment by scoobiekw** [comment] 2018-11-21 14:43
Your OS has a scheduler. Windows Scheduler will send http commands. 

Curl http://127.0.0.1:8000/press/bank/1/1

On mac, the Unix cron command is available. https://www.macupdate.com/app/mac/7486/cronnix is a GUI for it. The above command will work on Mac/Linux as well.

Nice to have integrated, but since the OS tool is there and tested, I'd rather see module dev.

**Comment by willosof** [comment] 2018-11-25 16:51
Thanks for the idea. I can't promise implementation of this, but it may happen.

**Comment by josephdadams** [comment] 2019-08-23 02:09
Duplicate of #389.

**Closed by josephdadams** 2019-08-23 02:09 UTC
Labels: Enhancement, Internal, Needs beer!, Nice to have, Solution needed
