### ISSUE TITLE
[feature request] Different actions based on latch state of a button

### ISSUE THREAD

**Issue by buffos** [bitfocus/companion#1602] opened 2021-05-21 10:38 UTC
Let me give you a use case example based on Vmix.

We want to send an input to Preview or Program. As is now we have to create 2 sets of buttons. One to send to preview and one to send to program.

What we need.

A latch button with no action. Just the 2 states. Change the name based on the state. Preview and Program

Now lets say we want to send input 1 to Preview or Program.

* Create a button with text: Input 1
* Next we need a new type of action. We need it to be compatible with the current model of actions
  so the simplest solution is to create the following type of action
   ```
    internal: skip actions if:    and the choices will be
    
    a dropdown with:
             button text is : " some text"  or button color is: "some color" or button state is:  on|off  AND
    a textbox with 
                how many actions we want to skip
    ```
    
  * with this simple change we can cut the required buttons by 2 as follows
  
  - internal: skip actions if:   
             * button state (we should pick the button to check state) is On (for us on means lets say program mode)
             * 1 action to skip
  - vmix action send input 1 to preview (this will be skipped if the button is ON )
  - vmix action send input 1 to program (this will NOT be skipped)
  
  
  And this way we will have conditional actions which can reduce required buttons by a lot.

**Comment by McHauge** [comment] 2021-05-21 11:03
Think this is what is referred to as a shift layer, of sorts

**Comment by stevespaw** [comment] 2021-05-21 15:34
I have been working on the best way to Preview Graphics overlays with similar hurdles. Because of the animate in and out features. I still don't have a great way to do it without another whole page of "preview" buttons. The director wants to see the CG overlay before air, and then decide to take it "with" or not. That is a current struggle in workflow.

**Comment by buffos** [comment] 2021-05-21 17:18
> I have been working on the best way to Preview Graphics overlays with similar hurdles. Because of the animate in and out features. I still don't have a great way to do it without another whole page of "preview" buttons. The director wants to see the CG overlay before air, and then decide to take it "with" or not. That is a current struggle in workflow.

To be fair, I can workaround this issue using dynamic variables inside Vmix, which can be from simple numbers to complex xml files, and utilize that in scripts, or use external scripts that have logic and call vmix using http requests, but it would be nicer to avoid those workarounds.

**Comment by josephdadams** [comment] 2021-05-23 02:14
#383

**Comment by Julusian** [comment] 2021-05-24 12:32
#1052

**Comment by JohnNorris92** [comment] 2021-05-25 01:52
This would be very helpful for Storing vs Recalling PTZ Camera presets too, Normally the button would call the preset, but if the store button is latched it will save the preset over that number

**Comment by Gartom** [comment] 2021-05-25 04:59
> This would be very helpful for Storing vs Recalling PTZ Camera presets too, Normally the button would call the preset, but if the store button is latched it will save the preset over that number

@JohnNorris92, I understand that this functionality would be useful for storing PTZ presets as you say but you can already do it today with delayed actions:

On button press:
* Store preset, delayed e.g. 2s

On button release:
* Abort delayed actions on button
* Feth preset

**Comment by JohnNorris92** [comment] 2021-05-25 05:17
> > This would be very helpful for Storing vs Recalling PTZ Camera presets too, Normally the button would call the preset, but if the store button is latched it will save the preset over that number
> 
> @JohnNorris92, I understand that this functionality would be useful for storing PTZ presets as you say but you can already do it today with delayed actions:
> 
> On button press:
> 
> * Store preset, delayed e.g. 2s
> 
> On button release:
> 
> * Abort delayed actions on button
> * Feth preset

Genius @Gartom  :)

**Comment by buffos** [comment] 2021-06-01 13:29
I have ended storing state in an external XML file. This gives me the possibility to have not only 2 states for a button, but infinite.

* When a button is pressed I run a PowerShell script and change some attribute in the xml file, or create new elements.
* Then I run a script to update companion state (for the buttons affected

This way buttons can have multiple functionalities depending on the state of other buttons, different colors etc.

I have some PowerShell scripts in my vmixproject repo. It may help someone speed up their process.

**Comment by Julusian** [comment] 2022-10-01 19:16
Duplicate of #1052

**Closed by Julusian** 2022-10-01 19:16 UTC
Labels: Enhancement
