### ISSUE TITLE
Disable Surface to allow Elgato's software to run on one device

### ISSUE THREAD

**Issue by cerspense** [bitfocus/companion#293] opened 2018-10-17 01:20 UTC
I need the ability to disable Companion's control of one of my stream decks so that it can be used exclusively with Elgato's stream deck software, while another stream deck is running Companion.

Me and my colleagues are Notch users and have been using the Stream deck to run AutoHotKey scripts to drop nodes into the scene to create real time visuals. In addition to this, we need to be able to control media servers like Disguise and send OSC messages into Notch to control certain nodes in real time. Because of this, we need to be able to run Elgato's Stream deck software on one stream deck, and have Companion on another. Ideally we could hit a button in the Elgato software to switch into companion, (and hit a button in companion to switch back into Elgato's software) but if we could just disable it completely on one device, that would be a great starting point.

This would be great for usecases where functionality from Elgato's software is needed along with features from companion.

**Comment by haakonnessjoen** [comment] 2018-10-17 08:30
As a quickfix, you could connect just the one. Start companion. Connect the next one, and then start Stream Deck software. This should allow the stream deck software to take control of just the one stream deck.

**Comment by Julusian** [comment] 2022-09-05 14:27
Duplicate of #1891

**Closed by Julusian** 2022-09-05 14:27 UTC
Labels: Enhancement, Internal, Nice to have
