### ISSUE TITLE
MIDI input

### ISSUE THREAD

**Issue by robsidle** [bitfocus/companion#2263] opened 2023-01-05 19:03 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Ability to press a button with an external midi controller. Similar to what OSCulator can do, but natively within Companion. Either add a midi controller under "Surfaces" tab, or through MIDI-Relay program & module. 

### Usecases

Doing stage production and would love to trigger video/audio/lights actions from midi foot controller.

**Comment by Julusian** [comment] 2023-01-05 19:05
Duplicate of #1709

**Closed as completed by Julusian** 2023-01-05 19:05 UTC
Labels: Enhancement, area/surface
