### ISSUE TITLE
[BUG] Latest version stopped working

### ISSUE THREAD

**Issue by gravelfreeman** [bitfocus/companion#2730] opened 2024-02-02 02:02 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can't deploy docker.

### Steps To Reproduce

Update to latest version of Companion.

### Expected Behavior

Deploy the app.

### Environment (please complete the following information)

```markdown
- OS: TrueNAS Scale
- Companion Version: Latest
```

### Additional context

The error seems related to an issue with Blocky my DNS server since the port 5353 is from Blocky. Here's the log from the crash.

```python
2024-02-02T01:59:17.446Z info Log/Controller Application starting 
2024-02-02T01:59:17.449Z info Registry Build 3.2.0+6663-stable-b83f412f 
2024-02-02T01:59:17.450Z info Registry configuration directory: /companion/v3.2 
2024-02-02T01:59:17.511Z info Log/Controller Sentry error reporting configured 
2024-02-02T01:59:17.534Z info Graphics/Controller Render worker created 
2024-02-02T01:59:17.538Z info Graphics/Controller Render worker created 
2024-02-02T01:59:17.694Z info Service/OscListener Listening on port 12321 
2024-02-02T01:59:17.703Z info Service/Tcp Listening on port 51234 
2024-02-02T01:59:17.704Z info Service/Udp Listening on port 51235 
2024-02-02T01:59:17.706Z info Service/ElgatoPlugin Listening on port 28492 
2024-02-02T01:59:17.708Z info Service/BonjourDiscovery Listening for Bonjour messages 
2024-02-02T01:59:17.801Z info Graphics/Controller Render worker created 
2024-02-02T01:59:17.803Z info Graphics/Controller Render worker created 
2024-02-02T01:59:17.804Z info Graphics/Controller Render worker created 
2024-02-02T01:59:17.805Z info Graphics/Controller Render worker created 
Error: bind EADDRINUSE 0.0.0.0:5353
    at node:dgram:364:20
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 5353
}
sentry error {
    "values": [
        {
            "type": "Error",
            "value": "bind EADDRINUSE 0.0.0.0:5353",
            "stacktrace": {
                "frames": [
                    {
                        "filename": "node:internal/process/task_queues",
                        "module": "task_queues",
                        "function": "process.processTicksAndRejections",
                        "lineno": 83,
                        "colno": 21,
                        "in_app": false
                    },
                    {
                        "filename": "node:dgram",
                        "module": "node:dgram",
                        "function": "<anonymous>",
                        "lineno": 364,
                        "colno": 20,
                        "in_app": false
                    }
                ]
            },
            "mechanism": {
                "type": "onuncaughtexception",
                "handled": false
            }
        }
    ]
}
2024-02-02T01:59:18.212Z error Instance/Modules Error loading module from "/app/bundled-modules/restream-api": Error: Manifest incorrectly references template module 'companion-module-your-module-name' 
2024-02-02T01:59:18.273Z info Instance/Modules Looking for extra modules in: /app/module-local-dev 
2024-02-02T01:59:18.277Z info Instance/Modules Found 0 extra modules 
2024-02-02T01:59:18.310Z info Instance/ModuleHost Starting connection: "VDO_Ninja"(n-GX7039zkJrx3x0Q5Ssc) 
2024-02-02T01:59:18.311Z info Instance/ModuleHost Starting connection: "obs"(YORp9BK9T7fD1IWkpoR-9) 
Started
2024-02-02T01:59:18.314Z info UI/Server new url: http://0.0.0.0:8000/ 
FATAL ERROR: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neon-0.10.1/src/types/promise.rs:178:22 Failed to resolve promise
 1: 0xb85bc0 node::Abort() [./node-runtime/bin/node]
 2: 0xa94749 node::OOMErrorHandler(char const*, bool) [./node-runtime/bin/node]
 3: 0xb4aa53 napi_fatal_error [./node-runtime/bin/node]
 4: 0x7f42749f6368  [/app/node_modules/@julusian/skia-canvas/lib/v6/index.node]
 5: 0x7f4274a63805  [/app/node_modules/@julusian/skia-canvas/lib/v6/index.node]
 6: 0x7f42749dc4ba  [/app/node_modules/@julusian/skia-canvas/lib/v6/index.node]
 7: 0xb4c362 node::ThreadPoolWork::ScheduleWork()::{lambda(uv_work_s*, int)#2}::_FUN(uv_work_s*, int) [./node-runtime/bin/node]
 8: 0x166428d  [./node-runtime/bin/node]
 9: 0x1668a76  [./node-runtime/bin/node]
10: 0x167afb4  [./node-runtime/bin/node]
11: 0x16693de uv_run [./node-runtime/bin/node]
12: 0xb0b040 node::Environment::CleanupHandles() [./node-runtime/bin/node]
13: 0xb0b0d8 node::Environment::RunCleanup() [./node-runtime/bin/node]
14: 0xac8ed7 node::FreeEnvironment(node::Environment*) [./node-runtime/bin/node]
15: 0xc5242b node::worker::Worker::Run() [./node-runtime/bin/node]
16: 0xc52958  [./node-runtime/bin/node]
17: 0x7f427dc69ea7  [/lib/x86_64-linux-gnu/libpthread.so.0]
18: 0x7f427db89a2f clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted
```

**Comment by premultiply** [comment] 2024-02-02 07:57
> `Error: bind EADDRINUSE 0.0.0.0:5353`

The Port is already in use by another process (or instance).

**Comment by Julusian** [comment] 2024-02-06 15:42
Duplicate of #2714 

The bind error is also interesting, but is just some messy logging and not something critical. Although it does mean that bonjour/mdns discovery wont work on your machine

**Closed by Julusian** 2024-02-06 15:42 UTC
Labels: BUG
