### ISSUE TITLE
[BUG] Surface location variables are always blank

### ISSUE THREAD

**Issue by fahhem** [bitfocus/companion#2733] opened 2024-02-06 08:34 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All the variables for surface locations are blank, even for the emulator.

![image](https://github.com/bitfocus/companion/assets/306100/7f9ea67e-8163-4fcf-a335-fd21b25deec7)

### Steps To Reproduce

1. Go to Buttons
2. Go to Variables
3. Select internal
4. Search for "location"
5. Note the value column for all the surface location variables

### Expected Behavior

It should be the values seen under the Surfaces tab: Local, Offline, Emulator (are there more?).

### Environment (please complete the following information)

```markdown
- OS: Linux
- Browser: Chrome 120
- Companion Version: 3.3.0+6716 beta (though I tried this on multiple versions, I just updated to check that it's still broken before reporting)
```

### Additional context

Edit: I just saw there's an external API for rescanning over USB! Now the only thing missing is being able to replace the background image via the API rather than needing a polling feedback (I have backgrounds that update in reaction to events, so I'd rather they didn't poll).

Edit 2: And there's also a "Watch for new USB Devices". So actually I don't care about this variable anymore since my use-case is solved. I guess this is now an FYI that the location variables are blank on Linux/Ubuntu!

**Comment by Julusian** [comment] 2024-02-07 20:16
I appear to have decided that when a streamdeck is connected 'locally' to companion that this variable should be blank instead of saying 'local'. 
It appears that the variables don't exist while a surface is offline.
When surfaces are connected over satellite, these variables will have more meaningful values.

> Watch for new USB Devices

Yeah, this sounds like the key things you need

**Comment by Julusian** [comment] 2024-02-10 14:40
I think Im going to close this as this is behaving as intended. Whether it would be better to change it or not is a different matter, as there is going to be a lot of opinions on what should be used (127.0.0.1, localhost, Local ?)

When displaying these locations, I would do it with expressions, as that will allow you to handle the emtpy string and substitute in your own.

**Closed by Julusian** 2024-02-10 14:40 UTC
Labels: BUG
