### ISSUE TITLE
BUG: Selecting module from dropdown list bug.

### ISSUE THREAD

**Issue by stwr** [bitfocus/companion#565] opened 2019-03-26 21:42 UTC
**Describe the bug**
On build 'companion-1.3.0-b832226-1349-osx' in chrome, when in the dropdown menu to add an instance, when you scroll down to make the dropdown list fit, the categories shift relative to the mouse position. (see video)

**To Reproduce**
1. Go to instances
2. Click on add by manufacturer
3. Scroll down

**Expected behavior**
You expect the mouse to stay in sync with the selection, the bottom manufacturers can now not be selected. as the list is so big, is this the right way to present it?

**Screenshots**
see quick vid: https://youtu.be/0V5QrpC1xms

**Desktop (please complete the following information):**
 - OS: MAC OSX
 - Browser: Chrome
 - Version: Latest

**Additional context**

**Comment by josephdadams** [comment] 2019-08-21 23:03
Duplicate of #636 . Closing this one.

**Closed by josephdadams** 2019-08-21 23:03 UTC
Labels: GUI
