### ISSUE TITLE
Feature request: Cut/Copy/Paste for buttons

### ISSUE THREAD

**Issue by SSormunen** [bitfocus/companion#182] opened 2018-07-20 12:16 UTC
**Describe the feature**
Normal cut/copy/paste for buttons and their configs. So you can easily
rearrange and move buttons in same or between other pages

**Is this platform dependent (windows, mac, ..)?**
No, same for all platforms

**Usecases**
Constantly needing this feature. Pain to re-arrange or update buttons on pages without this.

**Comment by MartijnKraats** [comment] 2018-07-25 09:32
+1

**Comment by SondreMoan** [comment] 2018-08-05 11:25
+1

**Comment by willosof** [comment] 2018-08-05 16:08
Made support for this in the UI now, @haakonnessjoen will do the rest in the backend when he's had enough sun and fresh air.

**Comment by willosof** [comment] 2018-08-05 16:09
This is more or less a duplicate of the large #150 which also is in progress.. :)

**Comment by haakonnessjoen** [comment] 2018-09-02 22:17
Fixed in f6aeb2ad2

**Closed by haakonnessjoen** 2018-09-02 22:17 UTC
Labels: enhancement, gui, internal
