### ISSUE TITLE
additional action dialogue box

### ISSUE THREAD

**Issue by Brennan-Dan** [bitfocus/companion#1134] opened 2020-06-12 14:13 UTC
**Describe the feature**
When adding another action to a button, the add action box displays the previously used action in the "dropdown" however when you click on it take you to the top of the menu. 

It would be good if, for example, you clicked the text it would apply that action that it was displaying, or if you click the arrow it would take you back to the top of the list. 

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
<img width="897" alt="Screenshot 2020-06-12 at 12 13 57" src="https://user-images.githubusercontent.com/33227703/84511542-94e4ae80-acbe-11ea-9732-799000268e91.png">

**Usecases**
If you want to mute multiple sources using a single button as well as adding multiple feedback controls/ background colors etc.

**Comment by MeestorX** [comment] 2020-06-12 14:17
Duplicate of #1039

**Closed** 2020-06-12 23:26 UTC
Labels: Enhancement
