### ISSUE TITLE
Issue when using with StreamDeck software in a multi action step

### ISSUE THREAD

**Issue by rtgarland** [bitfocus/companion#1375] opened 2021-01-15 21:16 UTC
**Describe the bug**
When I add a Companion action into a multi action step on a Stream Deck, it doesn't execute.  If I add it to a single action button it works perfectly.  I am calling the same button in Companion for both.  It just doesn't seem to work in a multi action button even if it is the only step.  I contacted Elgato and they said to contact BitFocus.  

I am running the latest version of both Stream Deck and Companion.

The action works perfectly when it is a single action button on the Stream Deck

**To Reproduce**
Add any Companion action in as a mutli action step in the Stream Deck software.

**Desktop (please complete the following information):**
 - OS:  macOS Big Sur 11.1
 - Browser: Safari
 - Companion Version 2.1.2

**Comment by Julusian** [comment] 2021-06-15 21:47
Duplicate of #1180

**Closed by Julusian** 2021-06-15 21:47 UTC
Labels: BUG

**Comment by joeyfatstat** [comment] 2022-11-11 18:41
I have same problem using 
Windows 10
Companion 2.3 or 2.4
