### ISSUE TITLE
no scroll possibility in Add by Category or Manufacturer 

### ISSUE THREAD

**Issue by arne182** [bitfocus/companion#1426] opened 2021-02-06 14:55 UTC
**Describe the bug**
Can not scroll down the list. So can not select the items below 

**To Reproduce**
1. Click on Add by Category or Add by  Manufacturer in Instances

**Expected behavior**
If the list is larger than the display allow scrolling by bar or by mouse wheel

**Screenshots**
![image](https://user-images.githubusercontent.com/844102/107121568-7659a600-6893-11eb-8dd8-446b9847067f.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Companion Version 2.1.2

**Comment by Julusian** [comment] 2021-02-06 15:00
Duplicate of https://github.com/bitfocus/companion/issues/362

**Closed by Julusian** 2021-02-06 15:00 UTC
Labels: BUG
