### ISSUE TITLE
Searchable folder organisation of Connections and Triggers

### ISSUE THREAD

**Issue by reidwwall** [bitfocus/companion#2860] opened 2024-05-09 00:24 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

As a system gets larger there are more and more connections, and more and more triggers.  
It would be awesome if you could organise your connections into searchable, user definable folders... IE: Audio, Video, Lighting etc etc.... and do similar with triggers.......Would also be able to move things between folders.  

### Usecases

When you have lots of connects and lots of triggers, being able to manage them into searchable folders would be helpful.  I currently have 40 connections and 60 triggers!

**Comment by Julusian** [comment] 2024-05-09 09:01
Duplicate of #2065

**Closed by Julusian** 2024-05-09 09:01 UTC
