### ISSUE TITLE
Show Countdown Timer Variables etc. big on web

### ISSUE THREAD

**Issue by terriblefox** [bitfocus/companion#1897] opened 2022-02-07 11:10 UTC
### Is this a feature relevant to comapnion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Show one or more buttons big on a website for video countdowns, timers etc

### Usecases

 Very useful to provide information to the hole crew in the FOH. Grab it with a video mixer and show it on screens  or in the network on websites.

**Comment by Julusian** [comment] 2022-02-07 11:24
Duplicate of https://github.com/bitfocus/companion/issues/1429
Related to https://github.com/bitfocus/companion/issues/1708

**Closed by Julusian** 2022-02-07 11:24 UTC
