### ISSUE TITLE
Add Button-Descriptions to list of buttons

### ISSUE THREAD

**Issue by henry2k** [bitfocus/companion#2538] opened 2023-07-30 01:48 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Please add name of button to dropdown-list when choosing button to press by action.

### Usecases

When you select an action to press a button you can choose the page by number and the name is displayed, but when selecting a button there are only numbers and it's hard to remember which buttons do what when you have a lot of pages with a lot of buttons without names shown in dropdown.

**Comment by Julusian** [comment] 2023-07-31 11:20
Duplicate of #1536

**Closed by Julusian** 2023-07-31 11:20 UTC
