### ISSUE TITLE
Export Triggers and schedules

### ISSUE THREAD

**Issue by desertdognl** [bitfocus/companion#2181] opened 2022-11-14 19:43 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Possibility to export (and import) Triggers and Schedules to be able to move this to another machine or clean install

**Comment by Julusian** [comment] 2022-11-14 20:05
Duplicate of #1609

**Closed by Julusian** 2022-11-14 20:05 UTC
