### ISSUE TITLE
V3 Disable and Enable Switch for V3 modules

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#2368] opened 2023-03-13 11:17 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

V3 Disable and Enable Switch for V3 modules

### Usecases

Having options to enable and disable none v3 upgraded modules.

**Comment by dnmeid** [comment] 2023-03-13 11:24
What do you mean exactly with disable?
Disable all added and  enabled connections which are not v3 or
disable the visibility of the connections in the list of all connections?

I can't see the real need in the usecase.

**Comment by dnmeid** [comment] 2023-03-13 11:35
So, the answer is: hide non v3 modules from the connections list.
Honestly I don't think this is useful. Noone scrolls thru the list thinking: what kind of gear can I control today? Let's control the xy-camera, oh no, the module is only v2, so lets use the audo console instead.
People have a setup and then they look if it is supported, don't care about v2 or v3 as long as it works. You can never know, not even with v3 upgraded modules.

**Comment by Julusian** [comment] 2023-04-23 16:15
I agree that the value of this will be very limited, especially as many of the v2 modules do work fine.

This has been suggested before and would be easy to do, but someone needs to figure out where to put the toggle on that page. I can't find where to put it without it looking bad.

**Comment by Julusian** [comment] 2023-04-23 16:21
Duplicate of #2248

**Closed by Julusian** 2023-04-23 16:21 UTC
Labels: Enhancement, Help Wanted, area/gui
