### ISSUE TITLE
Ability to disable a button?    Base this decision on a custom variable?

### ISSUE THREAD

**Issue by rofrance19** [bitfocus/companion#2076] opened 2022-07-25 01:40 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I find I'd like to be able to disable/enable buttons from within a button.    Not sure how involved it is to add an enable/disable to a button, and then allow you to set/reset its state.  Or, maybe it would be more useful to be able to set a custom variable to a value from a buton press and tehn inspect/use that value in a conditional execution.

### Usecases

My use case is that I'd like to hit the button once and then locke it out from being hit again.    I need this on "Start Stream", but also on a button that launches my DAW.    I'd like to just do that once, change the color to grey, and then prevent the button from being hit again.   Further, I'd like to be able to re-enable the button from a different button... one that I can program for "RESET".   

For conditional execution, I would hit the button to start teh stream, then set the variable to "STARTED".   Then, I woudl be able to see that variable on a status button readout, and would also be able to use the custom variable in a conditional. For example, for "START STREAM", the first action could be "If custom variable is "STARTED", exit button"

**Comment by Julusian** [comment] 2022-07-25 11:16
Duplicate of #908

**Closed by Julusian** 2022-07-25 11:16 UTC
