### ISSUE TITLE
[BUG] No Feedback-Light with XKeys

### ISSUE THREAD

**Issue by tobi-olli** [bitfocus/companion#2603] opened 2023-10-15 10:39 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since Companion 3.1 the Feedbacklight on the XKeys-Panel doesn't work anymore. In 3.0.1 it's working just fine. I'm using the CompanionPi with an Raspberry Pi 4.

### Environment (please complete the following information)

```markdown
- OS: CompanionPi
- Browser:
- Companion Version: 3.1.1
```

**Comment by Julusian** [comment] 2023-10-15 10:40
Duplicate of #2602

**Closed by Julusian** 2023-10-15 10:40 UTC
Labels: BUG
