### ISSUE TITLE
Javascript Error Companion 1.4 on MAC

### ISSUE THREAD

**Issue by Fredscape100** [bitfocus/companion#857] opened 2019-10-10 18:48 UTC
Every time the GUI is started, this message is generated
<img width="426" alt="Screenshot 2019-10-10 at 19 30 26" src="https://user-images.githubusercontent.com/38854660/66597005-eec43000-eb95-11e9-9e8a-1450795408e8.png">

**Describe the bug**
Appears to be a Javascript error

**To Reproduce**
1. Companion is started'
2. Click on 'Launch GUI'
3. See error generated

**Expected behavior**
Everytime I run Companion the attached message appears
<img width="426" alt="Companion Error" src="https://user-images.githubusercontent.com/38854660/66597162-4d89a980-eb96-11e9-9373-363c6a5b39fa.png">

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: Catalina 10.15
 - Browser: Safari

Safari
 - Version 13.0.2

.

**Comment by willosof** [comment] 2020-01-09 23:26
I can't reproduce this.. :/

**Comment by willosof** [comment] 2020-01-14 13:10
Closing this.

**Closed by willosof** 2020-01-14 13:10 UTC
Labels: BUG, GUI, Import/Export
