### ISSUE TITLE
Nested Actions if Variable meets Condition... & Matrix of Custom Variables

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#2095] opened 2022-08-18 22:55 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Currently the action "Button Press and Release if Variable meets Condition" **only presses buttons** on Page/Bank. 

It would be powerful for many matrix scenarios to **have an Action only run** if it meets a Custom Variable (or is greater/lesser/not-equal to). 

Additionally, it would be interesting to see a custom matrix where you could pair values (ie 1, 2, 3 equal Cam 1, Cam 2, Cam 3 etc, or rather, their dynamic variable counterpart).

### Usecases

Having an Action only run if it meets a Custom Variable would be helpful for many Matrix scenarios (video inputs, multiple audio channels, playlists etc), and reduce the number of pages required. 

For instance, ATEM Extreme's MultiViewer has 16 windows that can receive numerous inputs. But it means I have to replicate 16 pages in Companion in order to change inputs on all 16 MultiView Windows. 

This could be consolidated into a single page using Custom Variables: if "internal:custom_mv" = 1, then I could create a "virtual" page 1 which would be MultiView Window #1. When this Custom Variable = 1, then selecting the input "PREVIEW" would put PREVIEW into Window 1. 

![Screen Shot 2022-08-18 at 6 44 18 PM](https://user-images.githubusercontent.com/76959770/185508316-84e9aa17-8050-4b22-bd72-714125285e0b.png)

The "Internal: Check Variable Value" feedback state works well at checking a Custom Variable and then changing the button text to dynamic variable.

This would be useful for many types of equipment that have a large number of video inputs, audio channels, or repetitious variables. It could even be used for building playlists for apps like VLC.

**Comment by Julusian** [comment] 2022-09-05 14:21
This has a better written use case, but I think this is a duplicate of #1052

**Closed by Julusian** 2022-09-05 14:21 UTC
