### ISSUE TITLE
Feature Request: Basic logic implementation

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion#396] opened 2018-12-07 15:33 UTC
**Describe the feature**
Add IF, THEN, AND, etc. to Companion functionality

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
no

**Usecases**
A simple example would be a "shift" button.  **IF** this button is pressed and held, **THEN** the 2nd button would perform action XY,  **ELSE** the 2nd button performs X.

**Comment by BasilChessman** [comment] 2018-12-11 02:19
Variables would be nice also. ;)

**Comment by willosof** [comment] 2019-01-19 15:41
Unless someone else than me or håkon implements this, this won't be implemented/maintained in companion due to conflicting interests. (We'll make paid software to do this)

**Comment by jpooley-hearst** [comment] 2020-06-20 12:43
Bump, please add logic to execute a certain action only if a certain key is activated.

**Comment by Julusian** [comment] 2021-06-15 22:07
Duplicate of #1052

**Closed by Julusian** 2021-06-15 22:07 UTC
Labels: Internal
