### ISSUE TITLE
some thoughts

### ISSUE THREAD

**Issue by Kaputtnique** [bitfocus/companion#3180] opened 2024-12-15 10:20 UTC
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Heya,

- i was installing companion and want to set the initial ADMIN PW.. would it be great to toggle visibility for the password?
- another thought: edit a button -> show on which page it is.. and maybe change the page? 

![Image](https://github.com/user-attachments/assets/443ce32e-d075-4b22-8505-2e8e9aacd485)

- maybe not just press Page to get back to MAIN .. maybe press PAGE and select which page u want?
- max ROW / COLUMN set to "real" numbers.. not everyone thinks that it start with 0 instead of 1 :-D

**Comment by Julusian** [comment] 2024-12-15 14:24
> i was installing companion and want to set the initial ADMIN PW.. would it be great to toggle visibility for the password?

The password is intentionally visible as part of highlighting how insecure it is. 

> another thought: edit a button -> show on which page it is.. and maybe change the page?

You can see which page it is on here:
![Image](https://github.com/user-attachments/assets/a9aead76-f983-4b00-804d-7a2166494117)
Or do you mean something else?

> maybe not just press Page to get back to MAIN .. maybe press PAGE and select which page u want?

I think this is a duplicate of #1497

> max ROW / COLUMN set to "real" numbers.. not everyone thinks that it start with 0 instead of 1 :-D

The grid is 'infinite' in both directions, positive and negative.  
At this point, I am not a fan of changing what the default start position is, as it will result in some users having a start of 0 and some of 1, and will end up with users being confused/annoyed when they try to import something with a different start position, or that the start position on each of their machines is different.
If it is enough of a problem for you, you can change it on your companion and deal with these consequences (make sure to backup your config first, shrinking the grid is a destructive operation), which I think is a better approach as you will be 'opting-in' to this.

**Comment by Kaputtnique** [comment] 2024-12-15 15:43
> > another thought: edit a button -> show on which page it is.. and maybe change the page?
> 
> You can see which page it is on here: ![Image](https://github.com/user-attachments/assets/a9aead76-f983-4b00-804d-7a2166494117) Or do you mean something else?

i mean like, just change it inside this edit button menu. atm i have to delete or copy it to another page, right? but inside of the edit page its not possible to change the page right?



the other awnsers are ok :-)

**Comment by thedist** [comment] 2024-12-15 16:07
> maybe not just press Page to get back to MAIN .. maybe press PAGE and select which page u want?

This can easily be achieved by just create a page that has buttons that go to other pages. For example my Page 1 is always a 'menu' page, and then on my other main pages I have a home button that goes to Page 1, and from there I can go to any page I want.

**Comment by Julusian** [comment] 2024-12-15 16:43
> i mean like, just change it inside this edit button menu. atm i have to delete or copy it to another page, right? but inside of the edit page its not possible to change the page right?

True it isn't. 

Im not sure if we should allow this, I don't think it will be a quick or easy task.   
At the very least this will need some ui, so that you can see what you are about to replace by moving it to another page.  
And I feel like just moving to another page won't be enough, what people will want to do is to also pick a new location for it. (I don't know if I have ever moved a button to another page and kept the same position). Doing this with a simple text field will not be a nice experience, so should this then provide a full grid? At which point it is reimplementing so much and I don't think makes anything much simpler for anyone. 

So I see 2 options:
1) Don't do anything for this, this could be solved another way (eg, show 2 pages at the same time)
2) Have this as a simple modal that allows you to pick the new location with an input field accepting either a page number, or a 1/2/3 style location. Show a previous of just the button that will be replaced.
  And not expand the functionality of this modal, if anyone asks for anything more complex.

**Comment by Kaputtnique** [comment] 2024-12-15 16:57
well, ok.. u can close it :-)

**Comment by dnmeid** [comment] 2024-12-15 17:00
> i mean like, just change it inside this edit button menu. atm i have to delete or copy it to another page, right? but inside of the edit page its not possible to change the page right?

I'm also against a change like this. In the general workflow what you should have in mind is that you are editing whatever is in a "slot".
In the case of the buttons, you select a grid cell and you edit the content of the grid cell. If you change the location in the button editor, I'd rather expect the same effect as selecting the new cell and not moving the control.
From the UI standpopint there are some elements with dedicated functionality. The grid has the functionality of visualizing and changing the arrangement of buttons and selecting cells for editing. The button editor has the functionality of editing what is in a cell. I'd rather not mix them up.

Closing this as not planned as 3 out of 4 points are not planned and one is already possible.

**Closed by dnmeid** 2024-12-15 17:00 UTC
Labels: Question
