### ISSUE TITLE
[BUG] 3.2 Input fields in actions do not accept input

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#2681] opened 2023-12-18 11:03 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I try to change the content of input fields, the field jumps back to old content when leaving it.
Tested with generic OSC and generic http.
Works in build 6601, broken in 6604.
![grafik](https://github.com/bitfocus/companion/assets/70244400/4c59d1b0-e26c-48bb-9d5e-cae491af818f)

### Steps To Reproduce

1) Go to one of the marked input fields.
2) Change content.
3) Press tab or click on a different input field.
4) Content jumps back to previous state.

### Expected Behavior

Accept new input.

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Firefox 120, Chrome 120
- Companion Version: 3.2 6604
```

**Comment by Julusian** [comment] 2023-12-18 17:43
Duplicate of #2680
This is fixed in build 6605

**Closed by Julusian** 2023-12-18 17:43 UTC
Labels: BUG
