### ISSUE TITLE
[BUG] OSC Messages cause Javascript exception

### ISSUE THREAD

**Issue by wbirchett** [bitfocus/companion#955] opened 2020-01-12 16:08 UTC
OSC Control of Lightshark LS-Core, each button press gives javascript error. 

Put IP and Port in OSC instance
Add OSC Integer control to button
Test action
![Screen Shot 2020-01-12 at 9 55 41 AM](https://user-images.githubusercontent.com/47365869/72221795-86357800-3523-11ea-833a-5b3e361f7845.png)
![Screen Shot 2020-01-12 at 9 36 00 AM](https://user-images.githubusercontent.com/47365869/72221796-86ce0e80-3523-11ea-8140-1c11914d0b4b.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser Chrome
 - Companion Version 2.0 Build 1995

**Comment by josephdadams** [comment] 2020-01-17 17:41
@wbirchett is Lightshark sending OSC messages back to Companion? Do you have Companion listening to OSC input?

**Comment by wbirchett** [comment] 2020-01-17 17:59
@josephdadams Lightshark can send OSC on 8003, I do not have companion listening of OSC.

**Comment by josephdadams** [comment] 2020-01-17 18:14
Can you include a screenshot of your button action setup?

**Comment by wbirchett** [comment] 2020-01-19 15:27
@josephdadams 
![Screen Shot 2020-01-19 at 9 25 53 AM](https://user-images.githubusercontent.com/47365869/72683533-dc636780-3a9d-11ea-99ec-3196789151c3.png)

**Comment by wbirchett** [comment] 2020-02-07 02:53
@josephdadams is there a way to disable the read packet if that is what is causing this? i have noticed in testing that the actions will perform if after i hit Ok on error message as long as i send a zero after the press action. but i then get 2 errors, 1 for the press and 1 for the release.

**Comment by josephdadams** [comment] 2020-02-07 13:43
Do you get this error on other OSC setups? If not, then it sounds like the problem is on the Light Shark end. Can you run wireshark and see what it is sending back to Companion?

**Comment by jdzPtv** [comment] 2020-02-17 13:55
Looks like it's definitely on the Light Shark end. I was formatting my own OSC packets for sending to companion myself and I got this error when I accidentally had a wrong byte order (big-endian).

**Comment by wbirchett** [comment] 2020-02-17 14:04
I have a work around in place at the moment, I am using OSCulator to pass through to LightShark. I will do a packet capture to see if anything is coming back from a command. The LS does not have a reply to MIDI.

**Comment by josephdadams** [comment] 2020-02-17 14:06
Well, since we all know the error is not Companion related, I’ll close this issue.

**Closed by josephdadams** 2020-02-17 14:06 UTC
Labels: BUG
