### ISSUE TITLE
Howto add an internal clock (time of day) and other functions?

### ISSUE THREAD

**Issue by JayPiEs** [bitfocus/companion#870] opened 2019-10-22 16:44 UTC
Is there the possibility to have a clock (analog or digital) with the time of day from the system?

And are there more interactive internal functions?

Does a howto exist for those functions?

**Comment by josephdadams** [comment] 2019-10-22 20:44
@JayPiEs these are the current internal actions available in Companion:

- Enable or disable instance
- Set surface to page
- Trigger a device to lockout immediately
- Trigger a device to unlock immediately
- Run shell path (local)
- Trigger all devices to lockout immediately
- Trigger all devices to unlock immediately
- Increment page number
- Decrement page number
- Button press and release
- Button Press
- Button Release
- Button Text Color
- Button Background Color
- Rescan USB for devices
- Abort all delayed actions
- Kill companion
- Restart companion

These are all relatively self explanatory, but if you need help using them, let us know.

The request for a clock has been asked for in issue #389 and #845.

**Comment by JeffreyDavidsz** [comment] 2019-10-22 20:51
If I remember correctly, a variable has been added some time ago. Need to check where but system time should be there

**Comment by istnv** [comment] 2019-10-22 22:41
I think the host clock is in $(internal:time_hms) and $(internal:time_hm)

**Comment by josephdadams** [comment] 2019-10-22 23:40
Confirmed, as @istnv said, so I'll close this since it is now answered. @JayPiEs let us know if you need anything else.

**Closed by josephdadams** 2019-10-22 23:40 UTC

**Comment by JayPiEs** [comment] 2019-10-23 00:33
> I think the host clock is in $(internal:time_hms) and $(internal:time_hm)

That is great! thank you

is it also possible to have the time in analog clock?

**Comment by josephdadams** [comment] 2019-10-23 01:15
Not at this time.
