### ISSUE TITLE
Transition to another value

### ISSUE THREAD

**Issue by SimonSimCity** [bitfocus/companion#3094] opened 2024-10-20 14:32 UTC
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Many of the systems we use have only setter for values we want to change - but we want this value to be changed granularly. 

I could see a transitioning option for seeing numeric values, where I could set the number to start from (in the future, variables could be used here), the time the transition should take, and minimum time between each call to the remote system so it doesn't get flooded. The system can then calculate how many steps it needs to take and by how much each step needs to change the value so the final value is the desired one.

### Usecases

We want to control the main slider on LightShark from 255 to 0, but we don't want to do it as boom 💥 all lights of - but we rather want to transition to this value in a few steps.

**Comment by dnmeid** [comment] 2024-10-20 17:03
duplicate of #2930

**Closed by dnmeid** 2024-10-20 17:03 UTC
