### ISSUE TITLE
Hardware Button press results in 8 actions

### ISSUE THREAD

**Issue by fletch247** [bitfocus/companion#456] opened 2019-01-21 13:23 UTC
pressing the hardware button one time, results in 8 actions: 4 press and 4 release

**Comment by haakonnessjoen** [comment] 2019-01-21 14:32
The first time you use a stream deck panel, please install the stream deck application from Elgato, and upgrade to the latest firmware.

This will fix a bug that is present in earlier versions of the firmware.

After this you may use the stream deck without the stream deck application if you want.

**Comment by fletch247** [comment] 2019-01-21 15:27
i already used streamdeck, firmware should be latest.
i closed the streamdeck app and it worked as it should. sorry.
the only other thing i encountered was that the connection to localhost was not possible without any active network connection.

**Comment by willosof** [comment] 2019-01-21 23:30
I don't believe this is a companion issue. Sounds like an unhealthy stream deck device, I've experienced that, and when pressing one button, other buttons is pressed. This is usually sorted out by the dealer for free. (you get a new one). Does it only happen with companion, and not the real stream deck application?

**Comment by josephdadams** [comment] 2019-08-22 19:26
Closing this as the author said that it worked as intended after the streamdeck app was closed. Isolated issue, not a Companion problem.

**Closed by josephdadams** 2019-08-22 19:26 UTC
Labels: INVALID
