### ISSUE TITLE
"AND" or "OR" for multiple conditions in triggers

### ISSUE THREAD

**Issue by roms75** [bitfocus/companion#2561] opened 2023-08-31 15:54 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hi, 

I'd like to set two conditions for my triggers but right now my only option is to run the trigger only if the 2 conditions are true. I'd like to run it if only one of it is true. Could you had an option to choose between all conditions becoming true, or just 1?

Thx a lot

### Usecases

I want my trigger to run if my variable has a "a" value or a "b" value.

**Comment by Julusian** [comment] 2023-08-31 16:01
duplicate of #372

**Closed by Julusian** 2023-08-31 16:01 UTC

**Comment by roms75** [comment] 2023-08-31 16:05
I don’t speak about feedback, but trigger...

**Comment by Julusian** [comment] 2023-08-31 16:06
> I don’t speak about feedback, but trigger...


Internally the conditions are feedbacks, so they will share a solution
