### ISSUE TITLE
Make Custom Variables Sortable

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2312] opened 2023-02-02 13:54 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It will help to make the items of the variable list sortable like this was able for actions.

### Usecases

Sometimes you add another variable which was similar to an existing. But each new variable is on the end of the list.

**Comment by Julusian** [comment] 2023-02-02 22:39
do you mean in the table where we show the values, in the dropdown fields where you can select a variable, or in the suggestions in text input fields?

**Comment by sstaub** [comment] 2023-02-02 22:46
I mean the list of "Custom Variables" in the "$ Variables" sub tab of the Buttons tab.

**Comment by Julusian** [comment] 2023-04-26 19:55
Closing as a duplicate of #2394
This one is the original issue, but the other expands on this with further bits that should be done at the same time

**Closed by Julusian** 2023-04-26 19:55 UTC
Labels: Enhancement, area/gui
