### ISSUE TITLE
Variable for the free diskspace on disk 1 for an ATEM Television Studio HD8

### ISSUE THREAD

**Issue by MichaSchumacher** [bitfocus/companion#2873] opened 2024-05-22 15:07 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I need a variable with which I can display the free space of disk 1 on my ATEM TElevision Studio HD8 from Blackmagic Design.

**Comment by Julusian** [comment] 2024-05-22 15:08
Duplicate of https://github.com/bitfocus/companion-module-bmd-atem/issues/299

**Closed by Julusian** 2024-05-22 15:08 UTC
