### ISSUE TITLE
[newbie question] trigger some action with an key from an additional numpad

### ISSUE THREAD

**Issue by lblabr** [bitfocus/companion#2350] opened 2023-03-01 12:38 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

i would like to trigger an action from an additional keyboard

is there any hint / description how to use an connected keyboard in companion?

Thanks a lot!

### Usecases

On a headless system with obs i would like to use an numpad and/or presenter (two different keys) to trigger the save replay buffer.

There are some other action too ...

**Comment by Julusian** [comment] 2023-03-04 16:35
Duplicate of #1505 or #1734 

This could be done with some other tool which converts the keyboard presses into osc commands or something to trigger buttons in companion

**Closed by Julusian** 2023-03-04 16:35 UTC
