### ISSUE TITLE
Waves/LV1 Control

### ISSUE THREAD

**Issue by Austin-25413** [bitfocus/companion#1985] opened 2022-04-08 02:16 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be great to have companion integrate with the waves/LV1 sound software to be able to adjust faders, use mute groups and so on. 

### Usecases

it would be helpful, (especially to churches) to have companion integrate with Waves/LV1 to be able to control mute groups, buses, and adjust individual faders for different setting and scenarios.

**Comment by josephdadams** [comment] 2022-04-08 02:20
Duplicate of this: https://github.com/bitfocus/companion-module-requests/issues/754

**Closed by josephdadams** 2022-04-08 02:20 UTC
