### ISSUE TITLE
Make buttons duplicate/reference another

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#1519] opened 2021-03-24 21:11 UTC
**Describe the feature**
Add a button type: duplicate another button

**Usecases**
If you have a button, especially a very complicated one, that you need on multiple pages certainly it's possible to copy the button from page to page.  But it would be much more convenient if a button simply referenced a button on another page, so that if you have to make a change, you only need to do so once.

Nice to have, not critical:
Option to select some or all of target button's attributes
Moving the target button would automatically move the references of the buttons that copy it; or at least pop up a message saying what bank/button(s) duplicate the one being moved

**Comment by GeraldtheHippo** [comment] 2021-09-19 11:50
I'm not an admin but this should be merged with #1061 however that works

Same concept

**Comment by Julusian** [comment] 2022-10-01 19:20
duplicate of #1061

**Closed by Julusian** 2022-10-01 19:20 UTC
Labels: Enhancement
