### ISSUE TITLE
Roland V-1SDI control

### ISSUE THREAD

**Issue by stroemlund** [bitfocus/companion#501] opened 2019-02-20 08:16 UTC
Wouldn't it be possible to control this over USB-Midi if the mixer where connected to the same PC as the stream deck?

I that case could we maybe integrate the Midi controls over USB for this to work?

**Comment by dnmeid** [comment] 2019-02-26 10:26
Midi itself and Midi over USB are topics completely independent from the Roland V-1SDI or any other specific device. Midi is already requested and will be included sometimes in the future.
So this is kind of duplicate of #365

**Closed by dnmeid** 2019-02-26 10:26 UTC
Labels: DUPLICATE, Enhancement, Internal
