### ISSUE TITLE
Persistent buttons across pages

### ISSUE THREAD

**Issue by dogboy23** [bitfocus/companion#865] opened 2019-10-18 11:07 UTC
**PLEASE USE THIS PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE**

https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Makes buttons persistent/permanent from page to page

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Not applicable

**Usecases**
Having a take button or a VT button persist on each page, but different presets/cues.

**Comment by josephdadams** [comment] 2019-10-18 12:38
Duplicate of #27.

**Closed by josephdadams** 2019-10-18 12:38 UTC
