### ISSUE TITLE
Color Coding Option For Triggers - QOL Update

### ISSUE THREAD

**Issue by McWoahs** [bitfocus/companion#2348] opened 2023-02-27 16:10 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I am very excited for the updates coming in the beta version of companion with regards to the 'Triggers' portion of the software as I use Time of Day triggers extensively with my workflow. Usually 60+ per event. 

I wanted to suggest adding an option to choose a color for each trigger created. Perhaps just 5-10 basic colors to choose from. That way you can, at a glance, know what type of trigger your looking at in the trigger list. 

### Usecases

I created a crude little preview with Photoshop of what I had in mind. 

My current use case is a fitness event that I trigger a video/audio event for every new wave start, Around 40-50 per day. I also trigger a different video/audio event for the first wave of each category, and finally I trigger a slide advance after the last wave of each category. So I'm creating 3 types of triggers. I figured having an option to add a color to each trigger would help me quickly decipher what 'type' of trigger I'm looking at when moving to clone or edit a trigger. 

![Companion Triggers - Colors](https://user-images.githubusercontent.com/24812325/221616371-ca6e6f15-669c-4451-8450-b5782e1f591b.png)

**Comment by Julusian** [comment] 2023-02-27 22:41
Although this is proposing a different solution, Im going to call this a duplicate of #2065. Both of them are about organising/grouping the triggers in some way, so it would be best to have them written as one task

**Closed by Julusian** 2023-02-27 22:41 UTC
