### ISSUE TITLE
GUI new instance selector issues in Chrome

### ISSUE THREAD

**Issue by charleswwelch** [bitfocus/companion#1171] opened 2020-07-19 21:54 UTC
The add instance by manufacturer/category list is unusable in Chrome. The list is longer than the length of the webpage and it is automatically jumping back to the top of the list (audio, blue-ray etc). I cannot scroll beyond the 'L' categories to see what other hardware is supported.

![image](https://user-images.githubusercontent.com/25287599/87886181-e46a7880-c9e8-11ea-9698-c4d9a8da9714.png)

**Comment by josephdadams** [comment] 2020-07-20 02:17
Duplicate of #362

**Closed by josephdadams** 2020-07-20 02:17 UTC
Labels: BUG
