### ISSUE TITLE
[REQUEST] Conditional pre-checks before progressing to actions

### ISSUE THREAD

**Issue by BlakesHeaven** [bitfocus/companion#1253] opened 2020-10-19 09:49 UTC
**Describe the feature**
I request a new feature that allows checks to be made before proceeding on to actions.
Make use of the feedback options in whatever instance, with the action to proceed or not.
eg if Background colour green then stop
if vMix/OBS Input is LIVE then stop

Also, add action to flash alternate colours for a few seconds to indicate the "error" and maybe temp change button lable for the few seconds.

I would expect a check before both the UP action and the DOWN action.

This could of course be extended out to conditional IF/ELSE

**Usecases**

- When pressing a button to move a PTZ camera to a different preset position, check if it ok to move it else risk interfearing with a **LIVE** shot and the camera zooms across the stage to the wrong place at the wrong time; ie check it is not active.
- If  a scheduled event is about to happen (#1186 / #389 ), for example to start recording/streaming and we are already recording/streaming then do not proceed.
- If we are streaming within a specified time (#389 ), eg 10 am to 11 am then prevent the "stop stream" button from being actioned by mistake.

**Comment by TreborKutscher** [comment] 2020-11-23 20:27
the idea sounds intresting. how is your interface idea?

For  make your idea work with ptz and vmix the instance feedback could be a good approach to get data wether the cam is live.

do you imagine appending this denial with a checkbox on that instance feedback?

**Comment by BlakesHeaven** [comment] 2020-11-23 23:18
Thanks for supporting the idea.
That is exactly it; make use of whatever Instance feedbacks are available for any Instance but make available as "KEY DOWN/ON ACTIONS" and  "KEY UP/OFF ACTIONS".
For example, vMix has Instant feedback of: "Change colours **based on LIVE input**"
Make: "Check Based on LIVE input" available as action with options continue & stop.  
For Stop, Offer checkbox to flash button with "Error" and change colour.
I would guess it would be possible to capture the instance feedbacks available dynamically and make them dynamically available as "Check" actions.

**Comment by Julusian** [comment] 2021-06-15 22:04
Duplicate of #1052

**Closed by Julusian** 2021-06-15 22:04 UTC
Labels: Enhancement

**Comment by BlakesHeaven** [comment] 2021-06-17 07:58
Understand and agree with you working on a single ticket; I'll take the closure as a positive action and that #1052 is is progress. You can always refer back to this ticket. Thanks for your efforts.👍
