### ISSUE TITLE
Certain Instances with dropdown options incorrectly display after adding more than one dropdown.

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#877] opened 2019-11-02 17:16 UTC
**Describe the bug**
When editing a button, the label in the drop down menu for the source/dest of a Videohub Route command displays incorrectly if you have more than one Route command per button.

**Update**
This appears to be happening on more than just the Videohub Instance, it also appears to be affecting:
–Videohub
-ATEM
-Blackmagic Multiview 4
–Panasonic-PTZ

**To Reproduce**
–Create a new button
–Add a "Route" action
–Select a source and destination
–Add a new route command
–Notice the change in number (-1) of the original Route command
–This will also occur if you delete a route command

**Expected behavior**
Labels remain consistent. (As far as I can tell, this doesn't affect the actual routing, just the labels).

**Screenshots**
[Screen recording of issue in action.](https://www.dropbox.com/s/i0519ja398pbeaj/Screen%20Recording%202019-11-02%20at%2012.09.41%20PM.mov?dl=0)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 13.0.2

**Comment by bryce-seifert** [comment] 2019-11-03 16:25
Updated title and info since I found this isn't exclusive to one instance. Slowly testing other instances and will update if I find more.

**Comment by dnmeid** [comment] 2019-11-03 21:24
With which version of Companion do you encounter this bug?

**Comment by bryce-seifert** [comment] 2019-11-03 21:26
v2 (734cd00)

**Comment by dnmeid** [comment] 2019-11-03 21:58
I can confirm this bug has something to do with the select2 dropdowns. It doesn't occur with the native dropdowns.

**Comment by dnmeid** [comment] 2019-11-03 23:06
Found it. The modules you mentioned store their choice IDs as numbers but the database always stores values as strings. So the comparison between number and string fails and the select2 now tries to add the new string option because it can't find it in the numbers.
I now convert all IDs to strings before comparison, this should fix it for single selection dropdowns. For multiple selction dropdowns (so far we didn't use them) the module developer has to take care that the IDs are strings.
In the long term it would be best to maintain variable type in the database.

Fixed in 1d16e3522732e4a63ba97a98610205b5fb71e95d

**Closed by dnmeid** 2019-11-03 23:06 UTC
Labels: BUG, GUI
