### ISSUE TITLE
Toggle On/Off for Feedback on different buttons

### ISSUE THREAD

**Issue by Avolife** [bitfocus/companion#2750] opened 2024-02-15 22:55 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to make button 1 flash between green/black (or whatever) when pressed and when I'm pressing button 2 for an example I would like button 1 to stop flash and just be black and make button 2 flash instead. Is this possible? It seems to work if you could toggle the feedback on/off as an action for different buttons. Anyone knows?
Like if you could press a button that toggles off the feedback from another button as an action.

I have find a way to make a variable and a trigger to make a button flash with 1 sec, but can't find how to control it for one button in a time when that button is pressed.

Next step in the process i would like to achieve is when I press on "Live" I would like the button that is flashing to turn red and stop flashing to indicate that button is Live.

### Usecases

Usecases for this would be:

- To have a visual of what button that is selected in a PREVIEW window
- Have a visual of what button that is selected LIVE
- A cue that is coming next
etc.

**Comment by Julusian** [comment] 2024-02-18 13:26
I think this is asking for some of what was described in #2233. Ill summarise, the problem with this approach is how to address/identify the feedback you want to enable/disable, as well as high potential for frustration as it won't be easy to figure out what is enabling/disabling a particular feedback.

But I think this would be solved in a better way with #372. I don't know when that will be done though, I have had a quick look into it recently, but its a large chunk of work to figure out the data flows.

Closing this as it is a duplicate of one or both of the above

**Closed by Julusian** 2024-02-18 13:26 UTC
Labels: Enhancement
