### ISSUE TITLE
Page title to variables

### ISSUE THREAD

**Issue by ArthurAK** [bitfocus/companion#2285] opened 2023-01-16 23:06 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Internal variable from Page name by page number.
$(internal:name_page_1) in button text would result the button to show: "MAIN CUT"

![image](https://user-images.githubusercontent.com/44576346/212777190-0b524c03-3ab0-40ad-a92c-17dcc0fe12c9.png)

![image](https://user-images.githubusercontent.com/44576346/212777043-cc289b53-55a6-4a10-a473-f1ccae4d1f56.png)

![image](https://user-images.githubusercontent.com/44576346/212777387-b3c18918-23b9-4080-a46f-c17ac8666976.png)

Similar-ish but not; #1497  & #1536 

### Usecases

Page setup as a menu, for jumping quickly from page to page. if page gets moved or renamed, the button directing to that page will have to be manually rewritten. Also same for any button that is used to jump to page.

![image](https://user-images.githubusercontent.com/44576346/212777003-2f865a18-ea56-4466-8a5f-fdeb66286a68.png)

**Comment by Julusian** [comment] 2023-01-17 01:05
This might be a duplicate of #2071, or might not. That other task is more vague than I thought, but from the title I interpreted it to include this :shrug:

**Comment by ArthurAK** [comment] 2023-01-17 01:22
> This might be a duplicate of #2071, or might not. That other task is more vague than I thought, but from the title I interpreted it to include this 🤷

Seems that the other one doesn't say this explicitly, but this could be implemented on "the same page" (pun intended)

**Comment by MeestorX** [comment] 2023-01-20 16:06
If the page buttons could accept variables for text, would that be a fix? I think that would allow for even more possibilities than the one the OP described.

**Comment by Julusian** [comment] 2023-01-21 13:28
> If the page buttons could accept variables for text, would that be a fix? I think that would allow for even more possibilities than the one the OP described.

That would be doable, but will make anywhere the pages are listed by name be confusing, such as the page selection dropdown on internal actions/feedbacks. These names will be used in more places in 3.1 too (I am working on a right panel for the buttons view which will be a list of the pages, and will become the place to add/remove/reorder pages when that happens)

**Comment by ArthurAK** [comment] 2023-02-01 11:27
> If the page buttons could accept variables for text, would that be a fix? I think that would allow for even more possibilities than the one the OP described.

Would not solve this, as this is done with normal buttons and set surface to page [X] task. Idea is to have Page names as read variables to be used.

**Comment by Julusian** [comment] 2023-02-04 18:16
There are now variables in the format of `$(internal:page_number_1_name)`

**Closed by Julusian** 2023-02-04 18:16 UTC
Labels: Enhancement, area/internal
