### ISSUE TITLE
Save and recall profiles

### ISSUE THREAD

**Issue by mrstudiodaddy** [bitfocus/companion#897] opened 2019-11-11 14:58 UTC
**PLEASE USE THIS PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE**

https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
I would like to be able to save multiple profiles for companion. I know you are able to export the button config and reload it. However, it would be great to be able to switch between profiles. 

PS... It would also be great to be able to limit the amount of pages. I don't need all 99. 

**Is this platform dependent (windows, mac, ..)?**
no.. 

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
I have some users that would benefit from a more simpler view and I have some more advance users that need more information. So it would be great if I could more easily load a different profile with a different button config.

This could be as simple as creating a saved profile directory. Once the config has been saved have a list that point to that directory in the UI that you can see a list of the saved configs and select one. But it would be nice to be able to recall profiles like the native steamdeck has using a button.

**Comment by McHauge** [comment] 2019-11-11 15:10
Hey, some of what you are looking for is already available in V2.0, I would suggest to maybe install V2.0 on a separate machine to see what it can do.

profiles would be a great addition, but so far in V2.0 you can make smaller page loops one with 5 pages, another with maybe 10pages, and then in the web interface set what page your stream deck should be on to get into the loop, or maybe at a couple of hotkeys to jump from one loop to the other.

**Comment by josephdadams** [comment] 2019-11-11 16:38
Duplicates #586

**Comment by mrstudiodaddy** [comment] 2019-11-11 20:13
I have been using 2.0 and didn’t see the ability to reduce page numbers. Can you let me know how to do that?

**Comment by McHauge** [comment] 2019-11-11 20:20
@mrstudiodaddy  well you don't remove pages, you just replace one of the up and down page buttons in each end and replace them with a go to this page button, that way you can create smaller loops

**Comment by mrstudiodaddy** [comment] 2019-11-11 20:40
Ok that makes sense. Thanks.

**Comment by willosof** [comment] 2019-11-25 18:45
This (and a undo history per preset) will be a part of companion 3.0 :)

**Comment by mrstudiodaddy** [comment] 2019-11-25 18:47
Awesome! Thanks William!

**Comment by Julusian** [comment] 2022-05-11 13:23
Duplicate of https://github.com/bitfocus/companion/issues/586

**Closed by Julusian** 2022-05-11 13:23 UTC
Labels: Enhancement
