### ISSUE TITLE
List of Instances Does Not Scroll

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#265] opened 2018-10-01 01:43 UTC
Using: companion-1.1.1-fe5e79e-osx.zip

When using the Companion Admin page on a 1280x800 display, the list of manufacturers is too long to fit on a single screen.  Scrolling the page does not scroll the list.  However, if you reduce the horizontal size of the page so that the logs are no longer on the right hand side, the list will scroll with the page.

This happens in both Safari and Chrome.

**Comment by willosof** [comment] 2018-10-08 18:07
I'm in the middle of sorting this out. Thanks for making a ticket

**Comment by willosof** [comment] 2018-11-24 16:08
This is no longer a showstopper after adding the search filter. Postponing this!

**Comment by josephdadams** [comment] 2019-08-22 00:00
Duplicate of #636 . Closing this one.

**Closed by josephdadams** 2019-08-22 00:00 UTC
Labels: BUG, GUI, TODO
