### ISSUE TITLE
[BUG] Empty screen when saving a trigger

### ISSUE THREAD

**Issue by dseehof** [bitfocus/companion#2072] opened 2022-07-15 08:22 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When editing a trigger the page displays completely blank. URL is correct and a reload fixes the problem, but happens continuously and every time.

### Steps To Reproduce

1. Create a new trigger, content doesn't matter and save it.
2. Now go back in and edit something and hit save.
3. Screen will be blank.
4. Hit reload and page displays correctly.

### Expected Behavior

Expected would be to not having to hit reload.

### Environment (please complete the following information)

```markdown
- OS:12.4
- Browser: Safari 15.5
- Companion Version: 2.3.0 (2.3.0+4536-beta-31a14e00)
```

**Comment by Julusian** [comment] 2022-07-26 11:04
I can't reproduce this. Trying on the same version of companion of an m1 mini running latest macos 12.3.

Could you provide a screenshot of what the console looks like? (right click, inspect element. Go to the console tab)

**Comment by dseehof** [comment] 2022-07-26 11:09
I was able to reproduce, contrary to my original post not with ANY trigger (internals work fine). But added an ATEM switcher and used any feedback with the same error

<img width="2012" alt="Screenshot 2022-07-26 at 13 08 15" src="https://user-images.githubusercontent.com/4004848/180992420-d37ab8f1-103c-4a81-81f9-b9475b5bcfc6.png">
.

**Comment by Julusian** [comment] 2022-07-26 11:17
Thanks, by editing an atem based feedback I can now also reproduce this

**Comment by Julusian** [comment] 2022-07-26 11:24
This should be fixed now

**Closed by Julusian** 2022-07-26 11:24 UTC
Labels: BUG
