### ISSUE TITLE
Enable disable actions

### ISSUE THREAD

**Issue by webby123** [bitfocus/companion#1568] opened 2021-04-13 08:11 UTC
I think it is usefull to have the possibillity  to enable disable some actions if there are more actions undere a button without delete them.
The same way as qlab have the possibility to arm disarm ques in a quelist.
At this moment we need to delete an action to do this for example testing purposes, with the possibitity to disable/eneble it this is much quicker.

**Comment by josephdadams** [comment] 2021-04-17 12:51
dupe of #908

**Closed by josephdadams** 2021-04-17 12:51 UTC
