### ISSUE TITLE
Companion Crashes when Companion Satellite is running on remote device [BUG]

### ISSUE THREAD

**Issue by Cmillets** [bitfocus/companion#1857] opened 2022-01-11 22:44 UTC
- OS: [Mac 10.14.6 Both Devices]
- Browser [Chrome]
- Companion Version [2.1.4 (b03d4f0f-2714) also downgrade to 2.1.3 and had same issue]
-  @Julusian 

Upon launching Satellite, on the remote device, the local instance of Companion would it began to connect then disconnect(continuously).

It caused Companion to crash with the attached error log:
![Screen Shot 2022-01-10 at 4 04 24 PM](https://user-images.githubusercontent.com/48162499/149032008-e56bd67e-c737-417f-a1ef-3e7cde26ece6.png)

It would also hold my three local usb devices hostage:
![Screen Shot 2022-01-10 at 4 13 37 PM](https://user-images.githubusercontent.com/48162499/149032085-57f76d48-f6d3-40dc-835f-cb3faa86aaed.png)

To get local companion running normally:

- Quit Satellite on remote device
- Dismiss error message(many times)
- Quite local instance of companion
- launch local instance of companion
- Disconnect local usb devices
- Scan to reconnect local usb devices

This was my first time trying Satellite. It had never run on my remote device or any device(Mac 10.14.6) before. Ip set to Target instance of companion on local device(ie. 192.168.0.130).

Satellite device would show up in control for brief second after it kill the local usb devices then proceed to crash local instance.

**Comment by Julusian** [comment] 2022-01-13 22:24
I don't know where to begin on this... That error is weird, and I dont understand how it got itself into that state...

**Comment by Julusian** [comment] 2022-01-13 22:41
Never mind, I found the cause
This is a known issue when using the lockout/pincode feature with satellite devices.
Unfortunately, it is unlikely that 2.1 will see any more releases (it took many months to get a release to support a new hardware revision).
This bug has been long fixed in the 2.2 beta builds.

**Closed by Julusian** 2022-01-13 22:41 UTC
Labels: BUG

**Comment by Cmillets** [comment] 2022-01-14 02:23
Thank you for taking the time to look into this issue. Forgive me for the ignorant question ... are you suggesting that the beta builds of companion have this issue fixed? ie. companion-2.2.0-b177f8fb-3722.
