### ISSUE TITLE
Enable/disable buttons

### ISSUE THREAD

**Issue by sonobianca** [bitfocus/companion#1650] opened 2021-07-03 03:43 UTC
Adding a way to enable/disable buttons on command would be amazing.  I’m building a setup where a band band leader starts backing tracks to play along.  The songs are known in advance, but the play order may change last minute to accomodate the needs of the artistic directions and the availability of the guests.

The way I’m doing it is by putting every song on its own button, but to avoid confusion, I’d like to turn the buttons off once they are pressed.  A reset button would be available on another page.

I think it would be an interesting way of creating some level of state machine, when combined with custom page navigation tricks.

**Comment by bryce-seifert** [comment] 2021-07-03 13:21
One possible workflow using currently available actions is to change the button text and/or background color to gray or something upon press to indicate "used." Or, you could even change the button text to match the background color on press so that it "disappears" after use. And then your reset button could change all the colors back to default.

**Comment by obcocav** [comment] 2021-07-03 20:07
I am wanting to do a similar workflow.  Haven't thought it all the way through yet or tested but thinking about the new custom variables feature.  Thinking along the lines of adding an action to set a custom variable of "key used" to true.  Then using triggers to disable other buttons/actions somehow.  Just thinking out loud.

**Comment by Julusian** [comment] 2021-07-03 20:46
Duplicate of #908

**Closed by Julusian** 2021-07-03 20:46 UTC
