### ISSUE TITLE
Request: Folders / groups / colors for triggers

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#3001] opened 2024-08-23 21:21 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Possibility to create collapsable folders / groups to put triggers in.
Alternative: Color coding for triggers with switches to show/hide triggers of certain color.

### Usecases

The trigger list can get quite long and cluttered in some projects.
It would be helpful to group & show/hide them in some way.

**Comment by Julusian** [comment] 2024-08-23 23:49
Duplicate of #2065
That isn't asking for exactly the same solution, but theyre both the same problem

**Closed by Julusian** 2024-08-23 23:49 UTC

**Comment by Coupe70** [comment] 2024-08-24 11:17
I'm sorry, I did a search, but didn't see this one. Great to know it's in the list!
