### ISSUE TITLE
Module Request: Newtek NDIHX-PTZ1

### ISSUE THREAD

**Issue by TriplM** [bitfocus/companion#757] opened 2019-07-29 18:25 UTC
Looking for control of Newtek NDIHX-PTZ1 through Companion. Pan, Tilt, Zoom, Focus and preset scenes would be awesome.  Anyone out there working on this, or able to help out?

M

**Comment by josephdadams** [comment] 2019-08-22 00:05
Duplicate of #281 , closing this one.

**Closed by josephdadams** 2019-08-22 00:05 UTC
Labels: Module, Needs documentation, Request
