### ISSUE TITLE
[BUG] Can not move feedbacks inside internal: Logic feedbacks

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#3037] opened 2024-09-17 01:02 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The User Interface behaves as if one can move the feedbacks placed inside an internal logic feedback, but it does not work. Obviously the order does not change the logic evaluation, but it creates a confusing UI.

### Steps To Reproduce

1. Create a internal Logic AND feedback
2. Create 3 boolean feedbacks within
3. Try and change the order as per top level feedbacks.

### Expected Behavior

Either remove the UI elements for reordering these nested feedbacks, or support moving them.

If moving is supported, should it include moving out of the current logic element to the top level or into another logic element? Certainly if that is not possible, then the moving of logic elements inside the internal logic feedback is aesthetic only.

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Chrome
- Companion Version: 3.4.0 Stable
```

**Comment by Julusian** [comment] 2024-09-17 12:24
This should work, but trying it now and I am seeing that sometimes things disappear while being dragged which is odd.
But when it isn't doing that, I can drag and drop between anywhere

**Comment by phillipivan** [comment] 2024-09-17 21:11
I'll try again this morning as I had absolutely no luck yesterday, but top level feedbacks moved just fine.

**Comment by Julusian** [comment] 2024-09-17 22:24
I think I have found the cause of what you are seeing. It looks like a case of it would only let you drag a feedback if it was at the outer level, or a child of the first feedback.

And I think I found the cause of the issue I saw, it tried to move a feedback to be inside of itself.

**Comment by Julusian** [comment] 2024-09-22 21:33
@phillipivan does it behave any better for you now, or do I need to look further into this?

**Comment by phillipivan** [comment] 2024-09-22 23:55
@Julusian I have just downloaded `3.5.0 Build 7415` to test.

I am able to move feedbacks in and out of internal logic feedbacks, even if its not the top feedback.

However sometimes the movements are not very intuitive due to the way the 'background' feedback positions are shuffled. I also was just able to 'loose' 3 feedbacks (and internal logic feedback with two other internal logics inside it) when moving it. I'm not quite sure how, but will see if I can find a way to reproduce it.

**Comment by phillipivan** [comment] 2024-09-23 00:01
Ok this seems to reproduce it fairly reliably:

1. Create two top level internal logic feedbacks
2. Create two internal logic cells inside each of those
3. Grab the bottom top level feedback, and drag it to the top - it should move to the top
4. Now try again, but while holding the mouse button to move it, move back down as if you actually want to place it inside the current top level internal logic feedback cell.
5. Some of the time it dissapears - maybe all the time if you get it in the right spot.

**Comment by Julusian** [comment] 2024-09-23 19:33
Thanks, that is fixed now too.

Similar issue to the one I found, your case was the feedback was trying to be added as its own grandchild, causing it to get forgotten.

**Closed** 2024-09-30 12:49 UTC
Labels: BUG
