### ISSUE TITLE
[BUG] 2.2 Streamdeck XL not detected Windows 7

### ISSUE THREAD

**Issue by benjohnsey** [bitfocus/companion#2000] opened 2022-04-17 20:33 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a new Streamdeck XL. Version 2.2 on Windows 7 will not detect it under surfaces. 2.1.4 detects it and works fine. Installation instructions seem to indicate Windows 7 is supported. 

### Steps To Reproduce

Install Companion 2.2. 
launch GUI. 
Navigate to surfaces and Streamdeck is not detected. 
Rescan does not detect. 

### Expected Behavior

Companion 2.2 should detect the Streamdeck. 

### Environment (please complete the following information)

```markdown
- OS:Windows 7
- Browser: Chrome
- Companion Version:2.2
```

**Comment by krzyc** [comment] 2022-04-20 21:18
Confirmed on Win 7 Ultimate SP1 64bit with Companion 2.2 and Stream Deck.
Problem is also present on custom built Companion from master.
Same version works after installing on Win 10.
Version 2.1.4 (custom build) works fine on Win 7.

**Comment by Julusian** [comment] 2022-04-21 19:30
I have spent some time digging into what is happening here. Most of the time was spent getting a windows 7 install to test on..
I believe it is caused by [this commit](https://github.com/yibn2008/find-process/commit/4dd1c156ef9ef364c1fa27c3b5e28d4b4e78d2c0) coupled with [this nodejs bug](https://github.com/nodejs/node/issues/25645), which causes our check to see if the streamdeck software is running to never complete, causing the usb scan to get stuck waiting.

Looking at the commit in the lib which caused this, I don't think we can simply downgrade the lib as I expect that will instead break windows 11.

I see the following options:
1) Remove that check, maybe it isnt necessary anymore in 2.2?
2) Skip that check for windows 7
3) Try and fix the library (probably not simple)
4) Do nothing. Windows 7 was EOL over 2 years ago

Option 2 is probably pretty simple and easy to do. I think `os.release()` could be used to do that

**Comment by krzyc** [comment] 2022-04-21 20:21
@Julusian Thanks for tacking this issue down. In linked issue there is suggestion that updating Windows Power Shell is sufficient to workaround this. Have you tested it? If it works maybe we can suggest that update in docs and close this issue. Update is still available for download: https://www.microsoft.com/en-us/download/details.aspx?id=54616 I will try to test it. I think that Win7 (including Embedded) is still in use and in many cases updating to Win10/11 is not possible without updating software and/or hardware, so if it is not a big effort I would fix it and keep Win7 support at least for current version.

**Comment by krzyc** [comment] 2022-04-22 10:16
@Julusian Installing Windows Management Framework 5.1 from above link resolves this issue. So maybe adding a note to docs is sufficient?

**Closed** 2022-04-27 08:50 UTC
Labels: BUG, os/windows
