### ISSUE TITLE
BUG: Importing via Replace Current Configuration gives non functional instances

### ISSUE THREAD

**Issue by richardgatarski** [bitfocus/companion#500] opened 2019-02-18 13:14 UTC
Perhaps related only to vMix and Generic http: When importing a configuration using Replace Current Configuration neither of those two instances function. Status column remains blank, and Edit results in a Javascript error. Resetting configuration, and then importing as an Individual page (have only one) works fine.
- OS: Win10
- Browser Chrome
- Version 1.3.0 (1a7592b-1203)

**Comment by Fader-Monkey** [comment] 2019-02-25 20:34
have same problem with christe Spyder on mac and raspi

**Comment by josephdadams** [comment] 2019-08-26 01:00
This really sounds like a duplicate of #546.

**Comment by willosof** [comment] 2020-01-10 00:22
Can't reproduce in 2.0.0-801d658-1986.

**Comment by Julusian** [comment] 2022-03-29 15:56
I am pretty sure this is working now in recent versions

**Closed by Julusian** 2022-03-29 15:56 UTC
Labels: BUG, $20 REWARD, Import/Export
