### ISSUE TITLE
Add ability actually add or remove pages, not preassign 99 by default?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [bitfocus/companion#2949] opened 2024-07-12 12:46 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Having the ability to actually have 99 pages is fine.  But pre-allocation makes no sense?  It is confusing to our operators of the stream decks to page up past that last defined page, and see a blank page rather than be returned to the first page which would be logical result, skipping completely blank pages.

### Usecases

Key use case is skip completely blank pages, never allocate them in the first place.

**Comment by thedist** [comment] 2024-07-12 13:21
If your operators are confused by a page up/down button that takes them to an empty page, you can just replace that button with one that takes them to any page you want, eg if your last page is 32, replace the page up button with one with an action that goes to page 0, and on page 0 replace the page down with one that goes to 32.

Or implement a menu system where you have one or more pages that have buttons that take you to specific pages, and those specific pages just have a 'back' button to return to the menu of all the pages you use.

So there are already solutions for skipping pages that are blank if you don't like the default.

**Comment by Julusian** [comment] 2024-07-12 15:55
While this isn't exactly the same, I am calling this a duplicate of https://github.com/bitfocus/companion/issues/2003, as a solution to add pages will also mean being able to remove pages

In fact, this has already been done in the experimental builds #2689, but is waiting for a few more pieces to be done before making its way to beta and a stable release

**Closed by Julusian** 2024-07-12 15:55 UTC
