### ISSUE TITLE
If statement in press action

### ISSUE THREAD

**Issue by jalmar2000** [bitfocus/companion#2179] opened 2022-11-13 11:55 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I haven't found a way other then using triggers to sort of get the solution but I would like to be able to sort of run an if statement inside the press actions. Right now I have built a page where via a couple of buttons a selection is being made to go to a certain page. There are 3 choices which write a variable and those variables get added to give an ID number for a certain page. After the choice is made the user clicks on the start button and should be taken to the page they specified in the buttons above. Right now I have it sort of working by letting the start button write the id number to a new variable and the a trigger run the set surface to page when that variable meets a specific value. I can get up to 36 page id's which would mean 36 triggers. And when I add different streamdeck to my laptop I have to change all those triggers because in the trigger actions you can only select a specific surface instead of the "This surface" option you get on a button. 

If i could run multiple if statements in the start button on my home page and only do that action if the variable meets the condition, or use a variable in the page field of the action " Set surface with s/n to page" the this could be amazing.

### Usecases

To make a button do a specific this based on a variable
or changing a page based on a variable

**Comment by Julusian** [comment] 2022-11-13 14:08
duplicate of #1052

**Closed by Julusian** 2022-11-13 14:08 UTC
