### ISSUE TITLE
Backround Colored PNG´s

### ISSUE THREAD

**Issue by Jonas-Lorenz** [bitfocus/companion#580] opened 2019-03-29 14:08 UTC
**Describe the feature**
Give transparent PNG´s a Backround Color.
 
**Usecases**
For example when you build a Mute Button with a transparent PNG Mute sign, that it lights up Red when you press it.

**Comment by dnmeid** [comment] 2019-03-29 22:49
In the meantime you can use one of the tons of chars we provide out of the box. E.g. `&#128263;` 🔇

**Comment by fusionstream** [comment] 2020-08-04 12:47
For reference the "list" is available here:
https://github.com/bitfocus/companion/wiki/Text-input

**Comment by dnmeid** [comment] 2023-06-02 22:03
Is this request still active? I think it comes from an era when we did not have transparency in pngs at all and transparent pixels were just black.
@Jonas-Lorenz please tell if it should stay on the list, otherwise I'll close this issue.

**Comment by dnmeid** [comment] 2023-06-19 21:04
OP doesn't answer any more, so I guess the issue is solved. Transparent PNGs will show the background color at transparent pixels and I think that was the goal of this feature request.

**Closed by dnmeid** 2023-06-19 21:04 UTC
Labels: Enhancement, area/gui

**Comment by fusionstream** [comment] 2023-06-23 06:27
It should be added that this feature is already present; in case it wasn't clear from the reply 2 posts prior.

But yea. Closed is good.

**Comment by davidjoshuaford** [comment] 2023-11-28 15:13
Is there updated information on the recommended PNG sizes for v3.2?

72x72 now looks fuzzy alongside the vector text, but would like to know the optimal size and if there are any performance trade offs.
