### ISSUE TITLE
Fixed Buttons to all Pages

### ISSUE THREAD

**Issue by Jonas-Lorenz** [bitfocus/companion#577] opened 2019-03-29 11:22 UTC
**Describe the feature**
To have the possibility to fix buttons that they are displayed on all pages.

**Usecases**
To have for example Play/Go or Stop buttons or so on all Pages.

**Comment by josephdadams** [comment] 2019-08-22 21:36
Duplicate of #27 . Closing.

**Closed by josephdadams** 2019-08-22 21:36 UTC
Labels: Enhancement, Internal, Solution needed
