### ISSUE TITLE
Companion Crashing while importing configuration on new builds

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion#1561] opened 2021-04-12 21:04 UTC
Hello there !

I'm facing with a troublesome problem. Since builds #3122 I am not able to import configuration anymore. Last known version stable for me is in order to import previous configuration is "companion-2.2.0-2b3aec5a-3117-win64.exe". 

Since then, ever new build crashes on the import ("Houston, we have a problem"). So for now I'm stuck with build #3117.

I've tried several browsers (Chrome/Firefox/Edge...), several windows (OS up to date) computers with the very same result : crash at import.

Has Anybody faced this problem ?

Thanks in advance for your response...

--
Arnaud Damian
LYMPIA

**Comment by Julusian** [comment] 2021-04-12 21:12
Note: ~3118 looks to be when electron was updated to v11

**Comment by kraves-oz** [comment] 2021-04-12 21:47
Arnaud have you tried deleting the app configuration folder (take a back up)?  It might need to create a fresh db file.  In your %appdata% folder.

**Comment by LYMPIA** [comment] 2021-04-12 22:30
Hi kraves-oz! 
I just went for a new clean install. I've properly uninstalled both Companion and Companion remote and as an extra measure of precaution I've also cleaned the aforementioned %AppData% folder from any Companion entries. Also I previously (before uninstalling everything Companion related) did a full configuration reset wthin the application.
Result is - unfortunately - the same : the application crashes on importing the configuration.

As a side note. Importing the same file I am trying to import with the most recent builds with the #3117 build is working just fine. We've also generated a bunch of *.companionconfig files from our different needs and all of them are working fine (within the #3117 realm of course)

**Comment by kraves-oz** [comment] 2021-04-12 22:34
Sounds like you've covered all the usual culprits then in your testing.

**Comment by LYMPIA** [comment] 2021-04-12 22:39
Yes, indeed (but worth the try). This is why I was insterested in knowing if anyone had encountered the same problem... (as it has also - as far as I know - not surfaced/mentioned in recent issues).

**Comment by McHauge** [comment] 2021-04-14 12:42
@LYMPIA what instances/modules are loaded in the configs? and does it make a difference if you create and setup those before importing. just asking to see if that matters. I have encountered some cases where that had an effect in the past.

**Comment by Jonhug82** [comment] 2021-04-21 07:51
I'm having the same problem, I am unable to export and then import a database. I have tried deleting the old files from appdata and have tried a fresh install with no luck at all. Currently only way to load and backup is to take a copy of the db directly. Im running 3259.

**Comment by LYMPIA** [comment] 2021-04-21 08:20
@McHauge  We're using multiple instances/connections from Blackmagic (ATEMs / Hyperdecks / Videohubs / Multiviews...) Birddog, Panasonic, Behringer (X32, XAIR...), JustMacros, VLC....
We've already tested : 
1 - to import a full configuration with previsously setup instances (same as ones used in the imported configuration). Result: crash.
2 - to import a full configuration with a fresh clean slate with no instances. Result: crash.

Everything we've tried - so far - leads to a crash while importing.

Last build that allows us proper import of our previous and complex configuration: #3117

**Comment by fdebeer** [comment] 2021-04-21 09:23
I had the same here with latest build. but importing just one page worked for me. so try to import every page seperately may work for you too

**Comment by Julusian** [comment] 2021-04-21 09:26
Can someone share a config that triggers this crashing? If you dont want to do so publicly, then feel free to email it to me instead.
I've tried using my production config to reproduce this but it works fine, so Im a bit stuck without a config that I know should trigger a crash

**Comment by LYMPIA** [comment] 2021-04-21 09:41
@Julusian Here's one of our config.
[LYMPIA-MINIPC-ATEM-02_full-config_20210406-2005.zip](https://github.com/bitfocus/companion/files/6349780/LYMPIA-MINIPC-ATEM-02_full-config_20210406-2005.zip)

**Comment by LYMPIA** [comment] 2021-04-21 09:43
@fdebeer  We thought to do the same... But some of our configs are using al lot of pages (more than 55). So it wouldn't be a practical solution for us.

**Comment by Julusian** [comment] 2021-04-21 09:55
From a quick test, this isn't companion crashing, just the ui getting disconnected.

Simply the file is too large, and causes companion to drop the connection (default threshold for the protocol we use is 1MB)
On top of that, there is a timeout in the ui which gets hit due to how long companion takes to validate the file, but that only gets hit after the first one is fixed.

The simple fix would be to increase this size limit, and to increase that timeout to minimise the risk of issues, but without some work it is possible that it will still happen for edge case configs.

**Comment by Julusian** [comment] 2021-04-21 09:56
The reason it happened with your config and not mine is that I do not use images, but you have a lot of them. This means my config is 160kb compared to yours at 2.9mb

**Comment by LYMPIA** [comment] 2021-04-21 10:10
@Julusian Indeed we're using lot of images in order to get a more readable content for our Directors and AD in live production.

Regarding the limit size, is this something that was implemented after #3117 ? (importing with #3117 and prior versions works fine)

**Comment by Julusian** [comment] 2021-04-21 10:14
I think it would have broken in 3130. That version updated the connection library, and likely introduced the limit by accident, the limit looks like a recent addition to the library

**Comment by jjbutler83** [comment] 2021-05-18 01:49
Having the same issue on a fresh install of 2.2.0 build 3242 on a RPi4 box.

**Comment by LYMPIA** [comment] 2021-05-18 06:58
@jjbutler83 "Nice" to be not alone on this issue. ;)

This size limitation has become a real problem.
 
We tried to reduce drastically the use of images and pages. 
So we built up a new configuration based on our basic needs on a fresh install (2.2.0 #3310). 

After a rather long and painful process of reimporting, reassigning each keys to the proper function and instance, we thought we had overcome the issue... But it wasn't the case... 

As a second project was added at last minute, we had to import this new and light configuration on another computer and things went awry. Same issue occured while importing. So we had to roll back again to #3117. As everything went fine while building the new config, we didn't notice that the file size overpassed the limit.

As far you are building your configuration on the same computer without any needs to export or import the very same configuration elsewhere, everything's fine. Size doesn't matter at all. 
But once you're trying to import elsewhere, size becomes a real problematic issue.

Based on a Streamdeck XL, we've found that with only 3 images (1.5 Ko each) some of our pages (selecting inputs on auxes) reaches 73 Ko each (6 auxes = 6x73 Ko) ! Other pages are 59 Ko (selecting content on ME1 and ME2 multiviews) each (16 x 59 Ko). Just based on these 22 pages of useful content we're overpassing the limit size even without any images... With two simple functions as selecting inputs for auxes and routing content within 2 multiviews we've managed to, unexpectedly, render "useless" the nomadic nature of Companion. ;) ;)

**Comment by McHauge** [comment] 2021-05-18 07:03
Personally, I would just move the "%appdata%/companion" folder around if its a whole config each time. that folder stores all user data on windows machines, just close the companion copy folder and run it again, no need for import/export.

this is not a Fix, but a way around it :)

**Comment by LYMPIA** [comment] 2021-05-18 07:25
@McHauge Thanks. Will try your work around ASAP.

**Comment by McHauge** [comment] 2021-05-18 07:28
I do this before and after nearly every show, in order to same q complete backup, the only think when going from a newer version of Companion to an older version, may give some "translation" error, but for the same version and forward, I haven't had an issue with this workflow since 2019 😉

**Comment by jjbutler83** [comment] 2021-05-19 00:44
> 
> 
> Personally, I would just move the "%appdata%/companion" folder around if its a whole config each time. that folder stores all user data on windows machines, just close the companion copy folder and run it again, no need for import/export.
> 
> this is not a Fix, but a way around it :)

Thank you, but as you mention here, remedies Windows setups but not RPi4s unfortunately.
I was aiming for 2.1.3 anyway and that is what I am wanting to get to. 2.2.0 just seems to break every single bit of my config and I just don't have the energy or heart to start over from fresh or have to reprogram EVERY button. (I have a lot of pages/templates that I've been building for quite some time now.)

**Comment by istnv** [comment] 2021-05-19 01:25
@jjbutler83 you can still copy the original config file directly. I can be in a couple of different directories depending on how you installed your rPi.

**Comment by davidjoshuaford** [comment] 2021-05-27 12:12
I've had the same problem as described here, and my work around at the moment is to import my 1.8MB config file via 2.1.3, then quit and run Companion via 2.2.0. 

I've also tested and found that Instance Feedback colors are missing when a profile is imported via 2.2.0. When imported via 2.1.3, the colors are there, and remain there when opened using 2.2.0.

**Comment by LYMPIA** [comment] 2021-05-27 22:31
I did try the @McHauge workaround. And yes, it actually worked as you said it would. I have to try if everything is fine with every instances connected. 
But as previouly said, it is not ideal as a workflow. Let's hope this database size limitation gets "fixed" somehow.

**Comment by Julusian** [comment] 2021-05-28 19:40
This should be fixed in build 3343

**Closed by Julusian** 2021-05-28 19:40 UTC
Labels: BUG

**Comment by LYMPIA** [comment] 2021-05-28 23:11
@Julusian 
Great! Many many many thanks Julian !
