### ISSUE TITLE
[BUG] Waiting for Webserver and high RAM use

### ISSUE THREAD

**Issue by Cdonhou** [bitfocus/companion#2714] opened 2024-01-24 23:45 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Installed 3.2.0 over existing working 3.1.2 install. After install the app launches but it hangs at “waiting on web server”. It never loads and clicking any item in the app window causes the system to spike and use almost all available RAM. Uninstall and reinstall same version doesn’t work. Did an uninstall and rolled back to 3.1.2 and everything works again

I

### Environment (please complete the following information)

```markdown
- OS:windows 10
- Browser:
- Companion Version:3.2.0
```

**Comment by Julusian** [comment] 2024-01-24 23:51
could you export your config and sent it to me? git@julusian.co.uk
It launches fine on my windows machine, perhaps it is something specific to certain configs/modules

**Comment by Cdonhou** [comment] 2024-01-24 23:53
I can but the only module is a Black Magic hyperdeck mini HD.

**Comment by Julusian** [comment] 2024-01-24 23:55
hmm ok. still, it could be something in there that isnt being handled correctly.

I should give the release a try on some other windows machines too , maybe there is something special about mine that makes it work

**Comment by Cdonhou** [comment] 2024-01-24 23:58
I’m not the only person with the issue. There another report on the slack channel.

**Comment by giorgiodutto** [comment] 2024-01-25 08:03
Same for me, i've tested on many pc also without upgrade but directly the 3.2 version.
the log speak about fonts......
the problem is that if i unistall the 3.2 ,to reinstall the old version, alsa the old version don't work.
the temporary solution for me was to install the old version in a clean machine

**Comment by Julusian** [comment] 2024-01-25 18:21
thanks for the config, which unsurprisingly did not help to reproduce the issue.
I've tried 3.2 on 4 windows machines now, none of them had any issues with running it.

Could you send the log files? That might have some more info as to what is going wrong. There will be a folder of them at `%APPDATA%/companion/logs` I think

**Comment by premultiply** [comment] 2024-01-26 13:24
I also have got a Windows 10 LTSC system where this issue occures.

It almost instantly takes gigabytes of RAM but never come up completly.

@Julusian Maybe I can offer you a remote access to the system for further analysis if it would help.

**Comment by giorgiodutto** [comment] 2024-01-26 14:28
![2](https://github.com/bitfocus/companion/assets/99798875/c7ffa948-d185-4319-977f-a074d1bb5651)
![1](https://github.com/bitfocus/companion/assets/99798875/8d115df1-534d-41ea-b808-bd31975f4b30)

**Comment by giorgiodutto** [comment] 2024-01-26 14:29
after that the ram became full and the system crash

**Comment by giorgiodutto** [comment] 2024-01-26 15:01
after using "REVO uninstaller" I managed to install the old "companion-win64-3.0.0+6000-beta-52f8eec5" and it works perfectly

**Comment by giorgiodutto** [comment] 2024-01-26 15:08
also the v3.1.2 2023-11-01 is running

**Comment by Julusian** [comment] 2024-01-27 22:07
hmm that log is interesting as it appears that companion is getting stuck in a restart loop, but I couldn't say why that is happening from those logs, or why it results in such an agressive memory leak.

@premultiply yeah that would be really helpful. please email me or message me on slack to arrange this.

**Comment by kman1898** [comment] 2024-01-31 03:04
Having the same issue on one machine

**Comment by gravelfreeman** [comment] 2024-02-06 18:28
I would like to try the fix in 3.2.1 but there doesn't seem to be a docker image for it yet.

**Comment by Julusian** [comment] 2024-02-10 20:37
v3.2.1 is released with the fix for this.

I don't have enough data to confirm any commonality in systems, so I can't be sure it will work in every case, and I havent been able to try setting up a machine the same as the one case I know of

**Closed** 2024-02-10 20:37 UTC
Labels: BUG

**Comment by gravelfreeman** [comment] 2024-02-19 19:48
Version 3.2.1 did not fix it for me.

```python
2024-02-19T19:46:09.064Z info Log/Controller Application starting 
2024-02-19T19:46:09.067Z info Registry Build 3.2.1+6676-stable-fa981d25 
2024-02-19T19:46:09.068Z info Registry configuration directory: /companion/v3.2 
2024-02-19T19:46:09.114Z info Log/Controller Sentry error reporting configured 
2024-02-19T19:46:09.132Z info Graphics/Controller Render worker created 
2024-02-19T19:46:09.135Z info Graphics/Controller Render worker created 
2024-02-19T19:46:09.136Z info Graphics/Controller Loading fonts 
2024-02-19T19:46:09.153Z info Graphics/Controller Fonts loaded 
2024-02-19T19:46:09.162Z info Service/OscListener Listening on port 12321 
2024-02-19T19:46:09.167Z info Service/Tcp Listening on port 51234 
2024-02-19T19:46:09.169Z info Service/Udp Listening on port 51235 
2024-02-19T19:46:09.170Z info Service/ElgatoPlugin Listening on port 28492 
2024-02-19T19:46:09.171Z info Service/BonjourDiscovery Listening for Bonjour messages 
2024-02-19T19:46:09.216Z info Graphics/Controller Render worker created 
2024-02-19T19:46:09.218Z info Graphics/Controller Render worker created 
2024-02-19T19:46:09.218Z info Graphics/Controller Render worker created 
2024-02-19T19:46:09.219Z info Graphics/Controller Render worker created 
Error: bind EADDRINUSE 0.0.0.0:5353
    at node:dgram:364:20
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 5353
}
sentry error {
    "values": [
        {
            "type": "Error",
            "value": "bind EADDRINUSE 0.0.0.0:5353",
            "stacktrace": {
                "frames": [
                    {
                        "filename": "node:internal/process/task_queues",
                        "module": "task_queues",
                        "function": "process.processTicksAndRejections",
                        "lineno": 83,
                        "colno": 21,
                        "in_app": false
                    },
                    {
                        "filename": "node:dgram",
                        "module": "node:dgram",
                        "function": "<anonymous>",
                        "lineno": 364,
                        "colno": 20,
                        "in_app": false
                    }
                ]
            },
            "mechanism": {
                "type": "onuncaughtexception",
                "handled": false
            }
        }
    ]
}
2024-02-19T19:46:09.667Z info Instance/Modules Looking for extra modules in: /app/module-local-dev 
2024-02-19T19:46:09.670Z info Instance/Modules Found 0 extra modules 
2024-02-19T19:46:09.700Z info Instance/ModuleHost Starting connection: "VDO_Ninja"(***) 
2024-02-19T19:46:09.701Z info Instance/ModuleHost Starting connection: "obs"(***) 
Started
2024-02-19T19:46:09.703Z info UI/Server new url: http://0.0.0.0:8000/ 
2024-02-19T19:46:10.174Z info Instance/Wrapper/VDO_Ninja Connection opened to VDO.Ninja 
FATAL ERROR: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neon-0.10.1/src/types/promise.rs:178:22 Failed to resolve promise
 1: 0xb85bc0 node::Abort() [./node-runtime/bin/node]
 2: 0xa94749 node::OOMErrorHandler(char const*, bool) [./node-runtime/bin/node]
 3: 0xb4aa53 napi_fatal_error [./node-runtime/bin/node]
 4: 0x7f9d0d46b368  [/app/node_modules/@julusian/skia-canvas/lib/v6/index.node]
 5: 0x7f9d0d4d8805  [/app/node_modules/@julusian/skia-canvas/lib/v6/index.node]
 6: 0x7f9d0d4514ba  [/app/node_modules/@julusian/skia-canvas/lib/v6/index.node]
 7: 0xb4c362 node::ThreadPoolWork::ScheduleWork()::{lambda(uv_work_s*, int)#2}::_FUN(uv_work_s*, int) [./node-runtime/bin/node]
 8: 0x166428d  [./node-runtime/bin/node]
 9: 0x1668a76  [./node-runtime/bin/node]
10: 0x167afb4  [./node-runtime/bin/node]
11: 0x16693de uv_run [./node-runtime/bin/node]
12: 0xb0b040 node::Environment::CleanupHandles() [./node-runtime/bin/node]
13: 0xb0b0d8 node::Environment::RunCleanup() [./node-runtime/bin/node]
14: 0xac8ed7 node::FreeEnvironment(node::Environment*) [./node-runtime/bin/node]
15: 0xc5242b node::worker::Worker::Run() [./node-runtime/bin/node]
16: 0xc52958  [./node-runtime/bin/node]
17: 0x7f9d1670fea7  [/lib/x86_64-linux-gnu/libpthread.so.0]
18: 0x7f9d1662fa2f clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted
```
