### ISSUE TITLE
Instances: Backup Devices 

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#815] opened 2019-09-11 08:17 UTC
**Describe the feature**
The ability to specify backup(s) in the Instance's config.  

**Is this platform dependent (windows, mac, ..)?**
N/A

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
This would greatly simplify programming.  This would allow a single action to automatically be sent to multiple devices. (for example, Main/Backup Playback machines).  

This could also be useful for simple projector control.  One instance, one action to turn them on/off.  Right now i'm on a gig where I just want to be able to turn on and off 8 projectors, and programming was a little more tedious than it needed to be.  Seems like it would be easy to implement, and the user could easily add backups after programming is done.

Optionally a delay (user definable) could be added before backup commands are sent to ensure that the primary device gets network priority, or sometimes you want to run your backup a few seconds behind to allow for switching time if something fails.

**Comment by josephdadams** [comment] 2019-09-11 13:38
Duplicate of #642 .

**Closed by josephdadams** 2019-09-11 13:38 UTC

**Comment by josephdadams** [comment] 2019-09-11 18:22
@IanTGreenwood would you mind hopping over to #642 and giving your feedback there?

**Comment by simongroom112** [comment] 2021-09-21 11:20
was there an update to this/did it ever get implemented?
