### ISSUE TITLE
Disable buttons

### ISSUE THREAD

**Issue by 2mas4556** [bitfocus/companion#2092] opened 2022-08-17 11:58 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

A checkbox in the top-section on "edit button" where I can disable the button, so the button remain on the streamdeck but maybe dimmed 50% or so, so I see that is disabled. And when I press it nothing happens. Think this is an easier way then move the button to another page or remove it, when I don't need it. 

### Usecases

I use ATEM mixers a lot and when I do a conferance over a few days I set up my Companion day1 with all the actions I may need. But would be great to disable the VB/video button if they don't have any videos on Day1 but have some on Day2. So I have the button ready, but I have miss click on it nothing will happen when its disabled. And I can enable it again on Day2 when they have some videos.

**Comment by Julusian** [comment] 2022-08-17 13:49
Duplicate of https://github.com/bitfocus/companion/issues/908

**Closed by Julusian** 2022-08-17 13:49 UTC
