### ISSUE TITLE
[BUG] Export / Import settings does not import button topbar global value.

### ISSUE THREAD

**Issue by AJolly** [bitfocus/companion#3145] opened 2024-11-15 22:10 UTC
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Exporting an import settings does not import the top button setting" Show the topbar on each button. This can be overridden per-button"

(It also  forces you to go through the config wizard every time which is quite aggravating.)

### Steps To Reproduce

Export config, import config. 

### Expected Behavior

Setting is remembered.

### Environment (please complete the following information)

```markdown
- OS:Win 11
- Browser: All
- Companion Version:
```

**Comment by Julusian** [comment] 2024-11-15 22:19
Duplicate of #2688

**Closed by Julusian** 2024-11-15 22:19 UTC
Labels: BUG
