### ISSUE TITLE
internal: Set Button Shortcut

### ISSUE THREAD

**Issue by mdgnys** [bitfocus/companion#1189] opened 2020-08-01 23:04 UTC
**Describe the feature**
Internal button action to set a specified button as a shortcut to another specified button.
This feature could be used to change the function of a button in a simple way.  Would have the same dropdowns as "internal: Button Press", duplicated, one for source and one for target.

**Is this platform dependent (windows, mac, ..)?**
no

**Usecases**
Fairly self-evident, a user could have several buttons that allows the target button's action to be set to several options.
Could also be used to have a single button to sequence through actions by setting this action as the last action in list.

**Comment by Julusian** [comment] 2022-10-01 19:20
duplicate of #1061

**Closed by Julusian** 2022-10-01 19:20 UTC
Labels: Enhancement
