### ISSUE TITLE
Used Button Colour

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#427] opened 2019-01-04 16:15 UTC
**Describe the feature**
Unused Buttons have as default Background colour and default for used buttons.

**Is this platform dependent (windows, mac, ..)?**
Easy to select

**Usecases**
Ease of use

**Comment by willosof** [comment] 2019-01-19 15:31
used? like, for fireworks? :p

**Comment by hadphild** [comment] 2019-02-22 13:35
As is if a Button has action assigned but no PNG or Text then it goes grey (Or Random Colour of programmers choosing)

**Comment by josephdadams** [comment] 2020-03-16 21:30
Duplicate of #613

**Closed by josephdadams** 2020-03-16 21:30 UTC
Labels: Question
