### ISSUE TITLE
Improving X-KEYS Companion integration

### ISSUE THREAD

**Issue by KingKiwi** [bitfocus/companion#1983] opened 2022-04-07 11:50 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

The x-keys integration works great so far. Here are some things i came across while setting up my xkeys:

1. **the internal command "set surface to page" doesnt work**. The xkeys stay all the time on the page they started. Setting up startup offset page works.

2. **improvement of the modifier behaviour**. companion can send all modifiers (shift ctrl alt win/cmd) as single keystroke or combinations (with another command) via vicreo listener. As i set it up, pressing a modifier key on the xkeys just triggered a single keypress via companion to vicreo. To activate the option "latch/toggle" didnt help. So for now i cant tell my computer that a modifier is hold while  im pressing another key. Im unable to progamm shortcuts with modifiers in my software because of that.
I think with the original use of companion (to operate with a streamdeck) it was never a question to press 2 buttons at the same time. The workflow behaviour with the xkeys is very different in this part and it would be nice to see a solution for this in companion.
Beside that, there is a workaround with setting up the modifiers via xkeys own software macroworks 3.1. Thats fixes this question to 100%. But would be a more "full" thing to have everything running in companion. Additionally this allows to create a feedback behaviour to set LEDs based on keystrokes with modifiers.

3. **More LED - Control**. I didnt even start setting up my lights. But as i can set an incoming OSC Command for setting up the backlight, i can see endless possibilites, as my software (reaper) gives full support to this. But overall it would be good to have more control to the behaviour of the lights. Mine starts with all blue lights on and whenever a key is pressed it turns off and never comes back (beside momentary behaviour while pressing a key). 

Some ideas what would be nice to have:

- control over both colors, incl dim per key
- startup colors for every page. This helps to highlight only available keys and structure them by color
- keypress sets LED of one ore more keys. Usefull if you press a modifier and all available keys to this modifier are shown in different color 

4. **Thanks for how x-keys are implemented so far!**

**Comment by Julusian** [comment] 2022-04-07 12:06
1) This might be a bug or might be intentional due to that many models spanning multiple pages
2) This is planned to be doable in 2.3/3.0, using #1630 to simulate shift layers. I suspect limitations around pressing multiple buttons might be because of spanning multiple pages. 
3) Yeah I've noticed that colour control isnt as flexible as it could be, but as the backlights are pretty basic in xkeys it will never be completely flexible (there is only red and blue, and only on or off for each of them)

1 & 2 I think may partly be dependant on companion supporting larger grid sizes, so that we dont have to have hacks to allow the xkeys to span across multiple pages.

**Comment by KingKiwi** [comment] 2022-04-07 12:20
> 2. This is planned to be doable in 2.3/3.0, using [feat: step button type to replace latching #1630](https://github.com/bitfocus/companion/pull/1630) to simulate shift layers. I suspect limitations around pressing multiple buttons might be because of spanning multiple pages.

- Thats nice. I dont know if i understand right, but "layers" sounds like very complex. If you just "reach" the hold state of a modifier to windows, the adressed software can see it and the you can program a shortcut in the adressed software involving a key and up to 4 modifier-keys. No need to combine them in bitfocus for this scenario. 
> 3. Yeah I've noticed that colour control isnt as flexible as it could be, but as the backlights are pretty basic in xkeys it will never be completely flexible (there is only red and blue, and only on or off for each of them)

-Thats enough to work with ;)

**Comment by stevespaw** [comment] 2022-04-07 14:15
I would love just a simple way to use feedback background color to connect to xKeys. Red-Blue-Black. 
This would be a game changer for usability.

**Comment by JeffreyDavidsz** [comment] 2022-04-13 06:42
@stevespaw Feedback is in, when you select red as background the button will color red.

**Comment by stevespaw** [comment] 2022-04-13 19:47
@JeffreyDavidsz Wow, good to know! I missed that somehow - now to update my x-Key pages!  Thanks.....

**Comment by JeffreyDavidsz** [comment] 2022-04-13 19:54
There is a new update coming which use a library made with help from xkeys. But I'm testing it as we speak

**Comment by stevespaw** [comment] 2022-04-13 20:07
Nice - I will watch this space for updates Thanks again

**Comment by JeffreyDavidsz** [comment] 2022-04-15 17:41
@KingKiwi 
1) The way I set it up is that buttons count onwards, so when you go past button 32 the next page is automatically selected. In the config you can drag the slider to an offset, so the first pages you might want to use with a streamdeck are not affected.
2) I've programmed companion to do a key press and key release of vicreo-listener [alt] and a button [tab] (I'm on windows), on press and release actions. This gives me control to do a alt-tab (first holding down the alt and press tab multiple times before release). This works. Sidenote; I'm working with the latest Companion (just updated the library) and version 4.0.8 (Pro) of the Listener. Feedback on the buttons also work. I need to figure out something to get the initial coloring in (now color changes only on update so you miss the colors at startup).
3) Color matching is done with the background color of a button (so control the button in companion). However to have color feedback when you press red is always full, blue is in the mix and the intensity can be set in the config (same place where you can find the startpage or offset page

I'll think about some extended options for coloring, but of to a different project first. If there are any issues with the latest update let me know

**Comment by KingKiwi** [comment] 2022-04-18 10:31
1. I think you got me wrong about this. I have already set up the startup page of my xk-80 to 50. Keys 1-32 are counting onwards 50.1-50.32 in bitcompanion , keys 33-64 on bitcompanion 51.1-51.32 and keys 65-80 affecting bitcompanion buttons 52.1-52.16.
If i now run the internal command "set surface with s/n to page" and select "current surface" "page 60", i expect companion to receive the buttons 60.1-60.32 + 61.1-61.32 + 62.1-62.16. But the companion buttons are still linked like before: page 50-52

2. In my companion (all tried versions, official and beta), i cant set it up like that. On press actions i have all special keys available, but on press actions, only "Key release" can be set, no option for "Special key" available. Thats the reason i went with makroworks for this.

3. Thats not working here either. Setting up the brightnes via slider and momentary red feedback on keypress are the only things that are working. But maybe im missing how to set it up? If i programm a button i "add feedback", then i choose "reaper:change colors based on record status". This should change the color of the key when i press record in my daw and works fine with my streamdeck. 
In companion I set the color to hex "FF0000" which is red 255 green 0 blue 0.
When i set my daw to record, the button in companion is changing color but xkeys LED isnt doing anything.


4.companion-x64-2.2.0+4086-beta-c2a9390f
I testet the new build and things got worse with it. Im comparing it with companion-x64-2.2.0+4061-beta-914d9eb3:
a) In "Surfaces" the "ID" is not displaying the name of the xkeys-model, its showing a number. 1029-1111000040 for the xk-24.
2) The behaviour of the xk-40 is still not as it should be. 
(Start page offset is set to 60)
Top Key 1 is pressing button 60.1
Top Key 2 is pressing button 60.21
Top Key 19 is pressing button 60.2
Top Key 20 is pressing button 60.22
Bottom Key 17 is pressing button 60.3
Bottom Key 18 is pressing button 60.23
The rest of the keys is doing nothing (also not on page 61 or 62).

Should i be able to fix this via "device settings" > "Y Offset in grid"? Because here i can set the slider to only 3 different values. "0", "1" and "2".

Setting it to "1" is having follwing effect:
Bottom Key 17 is pressing button 60.11
Bottom Key 18 is pressing button 60.31
The rest of the keys is doing nothing

Setting it to "2" is having following effect:
Top Key 1 is pressing Button 60.17. 
Top Key 19 is pressing Button 60.18
The rest of the keys is doing nothing

c) The order of keys on my xkey 24 is now also wild. But here i cant set "Y offset to grid", here i can set "x offset to grid". And i have 4 values available and none of them is setting the order back to normal.

Thanks for putting your effort!

**Comment by JeffreyDavidsz** [comment] 2022-04-18 15:04
1) Yes thats true, page offset is encountered, from there each button press will calculate the page it should be. So currently the only way to change that is to change the offset. But its also hard for me to understand why you want to change pages manually.
2) Might need to send me a screenshot, as I've tested this and works, but might be a version thing (VICREO-Listener and Companion both on latest.
3&4) there is a miss-take by me in the build, I've corrected that now and tested with my own xke-24. 
You should be able to test the background/feedback by changing the background color of the button. (whit a newer build)

I need to do something about the blue LED of the keys, thinking to kill them all at startup

**Comment by KingKiwi** [comment] 2022-04-18 16:37
1. I have already different kind of needs so set my xkeys to another page ;).

a) As im getting rid of my keyboard i want to have letters on a new layer on my xk80 and numbers on xk 24. 
b) My XKE 40 is labeled with plugin names and numbers 1-40. Of most of the plugins i have 3 versions. Mono Stereo and legacy (which is kind of low cpu mode, doenst matter). For the plugins i could use 3 different layers. The labeling 1-40 can be used universal for different operations. Like recalling/editing markers 1-40, Edit track 1-40 and so on.
c) On my xkey 80+24 i want to have a copy of my starting layer, but keys that are able to be used with modifiers are set to different color. A single press on one of this keys will trigger a page with available shortcut information on my streamdeck. 

The reason why i dont want (or cant do) these things via modifier is the much easier structure by changing pages. Also im out of modifiers and dont know if i have enough characters available ;)

2. I sent you a screenshot via email.

3. Just testet. Surface ID is as it should be. Behaviour of XKEY 24 is as it should be. Vicreo Listener is opening files again! The implementation of the xke-40 is not as it should be. The first 16 keys of each row are available - so the last 4 ones in each row are missing. Also the order is not right, should i break it down for you again? Does that help?


Some ideas for the lights: 

- Its also a bit of customer afford, but it would be a dream if states of lights would be saved with pages in bitfocus. Whenever you call a page (on startup as well), only available keys will lit up. I also have spare Keys on my Mainpages that i need to be dark.
- it would be also nice if LED can not only by lit by feedback-action or pressing the corresponding key, but also by other keys (on other surfaces). One example for the use is: I press a modifier or a combination of modifiers and all keys this modifier is available for lit up in red. Great.
- Generally it would be nice to have as much control over each color as possible, there are tons of uses for people out there i cant even imagine. > If you lit up blue and red at the same time, its purple ;)

**Comment by JeffreyDavidsz** [comment] 2022-04-18 17:49
Hi again, the xke-40 is a bit special case, I put in a log into companion to see which keyindex the xke-40 produces. When you have time, could you press the buttons and let me know what which button produces? Thanks in advanced

**Comment by KingKiwi** [comment] 2022-04-18 20:42
Yes sure, this time it has a schematic. On some buttons the next page (61) in companion also gets affected.

Every second xkeys is triggering the following (next right) companion button

starting with offset page 60
top row key 1 > button 60.1; key 3 button 60.2; key 5 button 60.3;...; key 15 button 60.8
top row key 2 > button 60.21; key 4 button 60.22; key 6 button 60.23;...;key 16 button 60.28
top row key 17-20 not working

bottom row key 1 60.11; key 3 button 60.12; key 5 button 60.13;...; key 15 button 60.18
bottom row key 2 > button 60.31; key 4 button 60.32; key 6 button 61.1;...;key 16 button 61.6
bottom row key 17-20 not working

**Comment by JeffreyDavidsz** [comment] 2022-10-11 09:27
Thanks for this, but I'm actually looking for the key index so something like
First button left upper; key index 1, companion 60.1. next to that key index 2 Companion 60.1
Bottom row first key, key index 11 companion 60.11

You should be able to see that in the log with the latest version.

The problem is that on all xkeys so far, numbering goes from top to bottom left to right. This seems left to right top to bottom

Met vriendelijke groet / Kind regards,

Jeffrey Davidsz
________________________________

**Comment by Julusian** [comment] 2022-10-26 22:07
I've just been through and tested a couple of xkeys in the `develop` branch (a couple of releases away), and have some updated responses to things here:

* The 'set surface to page' not working this is a limitation due to the architecture in companion and is not simple to fix, but in 3.0 it will work as you expect.
* I have reworked how to backlight control works, so that in 3.0 the red when pressed is now optional. 
* Both red and blue backlight do work, but I did find a bug where it would not work for the last few buttons (fixed in 2.4 and 3.0)
* In 3.0 I have figured out a flow for getting the button colours when connecting a new xkeys, so that should be more seamless now.
* I haven't changed the button order, so nothing should change/break there

In my testing with a XK-24 and a XK-12 Jog-Shuttle, this all worked nicely. 
cc @JeffreyDavidsz 

I'm going to leave this issue open for visibility, and will close it once all of these changes are in beta

**Comment by Julusian** [comment] 2022-12-06 21:59
This is in the 3.0 betas

**Closed by Julusian** 2022-12-06 21:59 UTC
Labels: Enhancement, area/surface

**Comment by kmreed** [comment] 2022-12-19 03:12
> 

Seems that even in the current beta the XKE-40 is not responding properly.

Attached is a log Pressing all the buttons in order on the first row, and then all the buttons in order on the second row.

[LXXIX-Video-01_companion_log_20221218-2206.csv](https://github.com/bitfocus/companion/files/10255623/LXXIX-Video-01_companion_log_20221218-2206.csv)
