### ISSUE TITLE
Moduler Request: Widget designer (Christie/Coolux) implementation

### ISSUE THREAD

**Issue by Roeland22896** [bitfocus/companion#176] opened 2018-07-17 22:19 UTC
I was wondering if it's possible to add Widget designer from Christie/coolux on the feature list. 
Widget designer is a Windows program (runs on mac/parallels)
Would be great for me because I use this software to control a lot of devices i have at the moment (projectors, relays, media servers, even magicQ). 
The widget designer is a program that can read a lot of devices and control a lot of devices and protocols (art-net, TCP, HTTP, SMS, Excel, Control Pandoras box media server, control Christie Projectors, Spyder from Christie, MagicQ in both ways, modbus, phidget in and outputs, kinect,...). It is a very powerful tool.
For me by controlling this application with a stream deck would make things very nice and smooth.
🙂 https://www.coolux.de/products/widgetdesigner/

**Comment by PerRoine** [comment] 2018-08-03 20:56
If you could specify a selection of actions you would like us to implement taht would be great

**Comment by Roeland22896** [comment] 2018-08-03 22:16
Simulate a WD buttonpress (custom script), fadervalue to 100%, page change, 
With the buttonpress i can trigger the most scripts in W.D. so that would already be very helpful. 
And if it would be possible to say which button we can press in companion that would be great. 
There is a free version of WD that can allow creation of buttons and command or i can make a project and send it to you as a file if that would help.

**Comment by kaminskihub** [comment] 2019-01-18 11:37
Just uploaded a module to integrate Christie WD Remoting. I will add more functions in the future. For now you can send commands (WD Command/Code  like "Fader1.Value=125") and Click Buttons and Fade Faders to Values over Time. This should do most of the tricks.

**Comment by Roeland22896** [comment] 2019-04-12 16:57
Did you tested this? 
I'm trying to get a connection up and running but doesn't seem to accept the commands. 
I did set-up TCP on port 123, multiclient, in the connectionmanager in W.D., wich gives me a connected status, seems good so far. 
Once I send a command or customscript click it seems to fail.

**Comment by kaminskihub** [comment] 2019-04-12 20:32
You need to setup a remoting tcp server under "Remoting" and not under the connection Manager.
https://www.coolux.de/root/downloads/support/Documentation/Helpfile/index.html#remoting.htm

I have tested it with all kind of WD Versions incl WD 6.0.4, 6.05, 6.06
Daniel

**Comment by Roeland22896** [comment] 2019-04-14 21:42
Yes thanks a lot, it works :)
Do you also know what exact command i have to use to trigger streamdeck buttons from widget?
Do i setup a udp server in W.D., connect a single osc message node?
And what exact commands, still strugling with these, found a workaround using the webbrowser to load the command for the buttons but osc would be easier to use in scripts.

Kind regards,


Roeland

On 12 Apr 2019, at 22:32, kaminskihub <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to setup a remoting tcp server under "Remoting" and not under the connection Manager.
https://www.coolux.de/root/downloads/support/Documentation/Helpfile/index.html#remoting.htm<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.coolux.de%2Froot%2Fdownloads%2Fsupport%2FDocumentation%2FHelpfile%2Findex.html%23remoting.htm&data=02%7C01%7C%7C6b5a737fef3f4e44060008d6bf85fc21%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636906979510031968&sdata=pOp519cq4p%2FA%2BZBskkRQQu9hLlS8OfS%2FXF3F1Z6M2Gg%3D&reserved=0>

I have tested it with all kind of WD Versions incl WD 6.0.4, 6.05, 6.06
Daniel

**Comment by josephdadams** [comment] 2019-08-21 23:50
Closing because this module exists.

**Closed by josephdadams** 2019-08-21 23:50 UTC
Labels: Module, Request

**Comment by Dwvsplat** [comment] 2021-02-03 15:10
I know this is an old thread, but I am having problems getting WD to respond to companion cues. We are running an older version 4.7. I have remoting set, and am seeing the packets sent in the imput message log (but no action in WB). Do I need to set something different in a button I want clicked (I tried remote input, but that did not help). I am assuming that customscript ID would be whatever number I have for a button (customscript25 would be just 25 in companion).

**Comment by kaminskihub** [comment] 2021-02-03 15:52
Hi,
The Problem is that Version 4.7 had a different Syntax than Version 6.
What you can try is sending a CustomCommand

try: WDCustomscriptClick,<ID>

This should Trigger the CustomScript in V4.7

The Command in V6 is WDCustomScriptclick(<ID>)

Let me know if that helps, if not, I will look into Updating the Plugin to also Support V4.7. But that might take a bit, since I am busy with other projects right now.

**Comment by Dwvsplat** [comment] 2021-02-03 16:22
It looks like it is WDCustomScriptClick,ID
So this would be WDCustomScriptClick,25  (for button 25)
I am still getting nothing.....Do I need to put a check in the box remote input on the button menu.
Any other ideas (I really appreciate the help!

**Comment by Dwvsplat** [comment] 2021-02-03 16:33
This is what I am seeing in WD

![20210203_112852](https://user-images.githubusercontent.com/61527783/106778025-882d1600-6613-11eb-8125-acfac2457c5f.jpg)
![20210203_112834](https://user-images.githubusercontent.com/61527783/106778043-8c593380-6613-11eb-923f-a3b91d4fc65d.jpg)
![20210203_112824](https://user-images.githubusercontent.com/61527783/106778045-8d8a6080-6613-11eb-9bd0-765b047bf283.jpg)

**Comment by kaminskihub** [comment] 2021-02-03 18:12
OK, I have a solution for you.
![image](https://user-images.githubusercontent.com/15860472/106790011-4754f180-6653-11eb-8e7e-ec50224e99b3.png)
![image](https://user-images.githubusercontent.com/15860472/106790105-5e93df00-6653-11eb-8ea6-2b0641498e27.png)

Use the gerneral TCP UDP Node
(WDCustomScriptClick,25)
Will click CustomScriptButton 25

No need to do anything special in the CustomScriptButtons

You can also Trigger Faders or anything else.

(WDFaderUp,1,3)
This will Send Fader 1 up over 3 Secounds.
Let me know if it works

**Comment by Dwvsplat** [comment] 2021-02-03 18:46
Thank you! It worked perfectly!!!
