### ISSUE TITLE
Stream Deck XL not recognized when plugged in (pi 4) [BUG]

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion#1149] opened 2020-06-24 23:18 UTC
**Describe the bug**
When I plug in my Stream Deck XL it doesn't automatically attach, aka doesn't show up in list of Surfaces until I re-scan USB. 
Using a Pi 4 that I want to leave running all the time, but would like to remove and re-attach the stream when its in use only.  

**To Reproduce**
Plug in stream Deck.. Not listed under surfaces 

**Expected behavior**
Plug in Stream deck, wait for a minute for it to attach, Start using 

**Desktop (please complete the following information):**
 - OS: Pi 4 4gig 
 - Browse: 
 - Companion Version: 2.0.0 (ce59ecb-2424)

**Comment by josephdadams** [comment] 2020-06-25 23:57
Duplicate of #481

**Closed by josephdadams** 2020-06-25 23:57 UTC
Labels: BUG
