### ISSUE TITLE
Add internal logic and variables

### ISSUE THREAD

**Issue by sphlabs** [bitfocus/companion#496] opened 2019-02-14 13:24 UTC
**Describe the feature**
Ability to create internal variables, whose values can be set based on triggers and/or feedback. Then implement basic logic in button actions (if, else), so that a buttons behaviour can be based on an internally maintained state.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
Show control can be based on a flow of overall control logic and state, beyond what could be achieved from individual instance feedback alone.

**Comment by willosof** [comment] 2019-02-18 07:31
Duplicate of #396

**Closed** 2019-02-18 07:32 UTC
Labels: DUPLICATE, Internal
