### ISSUE TITLE
Export/Import Triggers

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#1851] opened 2022-01-09 01:50 UTC
**Describe the feature**
Provide ability to export/import trigger configuration similar to how the same for buttons/pages are implemented.

**Usecases**
Currently there is no way to backup trigger configuration.

**Comment by Julusian** [comment] 2022-01-10 09:42
Duplicate of #1609

**Closed by Julusian** 2022-01-10 09:42 UTC
