### ISSUE TITLE
[BUG] Button text does not allow white space as 1st or 2nd char of text field

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#2899] opened 2024-06-06 00:51 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can not enter the string `I am` directly as button text. I can enter it via a variable.

### Steps To Reproduce

1. Create button
2. Try to enter `I am` as the button text string
3. Can create a custom variable and set it to `I am` and display that on a button
4. Can create a a button and set the button text string to `Ia m`
![image](https://github.com/bitfocus/companion/assets/137139426/5b8631ed-cc69-4696-9bfd-588be8d77da1)

Left most button is a custom variable. Middle is standard text, can not type ' ' as 2nd char. Right button is standard text., can type ' ' as 3rd char.

### Expected Behavior

Allow white space as 1st or 2nd char in button text string.

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Chrome 120
- Companion Version: 3.4.0 Build 7040 & 3.3.1 Stable
```

**Comment by dnmeid** [comment] 2024-06-06 20:24
That is not a bug, we strip up to two white spaces at front and end of the button texts intentionally.

**Comment by dnmeid** [comment] 2024-06-06 20:26
Sorry, closed this too fast. Off course only trailing and leading spaces should be trimmed, not spaces within the string.

**Comment by Julusian** [comment] 2024-06-08 17:06
This isn't a rendering issue, its a ui issue

**Comment by Julusian** [comment] 2024-06-08 17:37
this new variable input field has been fiddly, and this was another edge case that needed some special handling

**Closed by Julusian** 2024-06-08 17:37 UTC
Labels: BUG
