### ISSUE TITLE
Dashboard output page with Webpage / NDI

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#2208] opened 2022-11-29 15:20 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Having a dashboard page for all the variables. Making a grid up of all the custom variables. 

Device disconnects
VMIX call drops
Frame drops etc

This could be output via webpage / NDI (1920 x 1080p) 

### Usecases

A show screen for all techs to see if there are any issues or show is up to.

**Comment by Julusian** [comment] 2022-11-29 19:36
I think this is a duplicate of one of https://github.com/bitfocus/companion/issues/814 or https://github.com/bitfocus/companion/issues/1429.

I don't think it worth companion being able to output this as ndi, as that adds a lot of complexity for something that can be easily be solved with an external and free tool (obs, casparcg, a spare pc and ndi tool screen capture)

**Closed by Julusian** 2022-11-29 19:36 UTC
