### ISSUE TITLE
Sleep / Wake Functionality

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2250] opened 2022-12-22 15:17 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I have just changed over from running companion locally in multiple places to running one server and multiple instances of Satellite.  I have triggers set to read a custom variable of "Active" or "Not Active" which is set by any button press and if active to set brightness to X if not Y.  This creates a sleep / wake state for all the decks.  The problem is the trigger to set the decks as active uses "any button depress".  This also presses the actual button on the deck while the decks are dimmed.  Would love some way to not execute any action except wake or a user defined action on the first press.  That way I can press any button to wake the decks, like now, but without issuing a command on that button with the first press.

### Usecases

This would be huge for the always on use case.  I understand that actually sleeping the decks is a technical limitation but setting the brightness to 0 effectively works other than undesired actions executing with buttons pressed.

**Comment by Julusian** [comment] 2022-12-22 22:11
I think this is a duplicate of https://github.com/bitfocus/companion/issues/428 and maybe partially https://github.com/bitfocus/companion/issues/1660

**Closed** 2023-04-23 16:22 UTC
