### ISSUE TITLE
Wrong Stream Deck Layout Detected[BUG]

### ISSUE THREAD

**Issue by JamesAnderson2** [bitfocus/companion#1174] opened 2020-07-22 07:45 UTC
updated to version 2.1.0 and the button layout of stream deck no longer matches my stream deck. I have a 15 button stream deck, the emulator is showing 32 button version. Consequently all my programmed buttons are in the wrong place. 

**To Reproduce**
1. Have a 15 button stream deck working
2. Install version 2.0
That's it. 

Tried rescan ports. Tried restarts etc. 

**Expected behavior**
Expect the correct stream deck config to be detected. 
![Screen Shot 2020-07-22 at 5 43 59 pm](https://user-images.githubusercontent.com/68635697/88149094-f47d9480-cc42-11ea-9c5a-7448311e4565.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser Chrome
 - Companion Version 2.0

**Comment by krocheck** [comment] 2020-07-22 12:05
@JamesAnderson2, which version did you upgrade from?

**Comment by eqmotts** [comment] 2020-07-22 15:40
I'm having the same problem

**Comment by chouvener** [comment] 2020-07-22 17:52
Me as well. Thank you Bitfocus!

**Comment by chouvener** [comment] 2020-07-22 17:52
Me as well!

**Comment by krocheck** [comment] 2020-07-22 18:05
Please let me know which version you upgraded from.  Many thanks!

**Comment by chouvener** [comment] 2020-07-22 18:07
I updated from the most recent version, I had just installed it a week ago. Sorry, I'm not sure which one exactly! Thanks so much for the help and for Bitfocus!!

**Comment by JamesAnderson2** [comment] 2020-07-22 23:59
i updated from a recent version. Only installed a few weeks ago.

**Comment by JamesAnderson2** [comment] 2020-07-23 00:00
thanks for the help

**Comment by JamesAnderson2** [comment] 2020-07-23 00:02
Actually, I've recently changed computers, so the version I installed on this new computer would only have been about a week old. I'm guessing the most recent version before this update.

**Comment by josephdadams** [comment] 2020-07-23 02:30
@JamesAnderson2 was it the beta version 2.0 before? Or the main download from the Bitfocus site, which was 1.4?

**Comment by JamesAnderson2** [comment] 2020-07-23 02:37
It would have been the main version downloaded from the website. I didn't deliberately install a beta version.

**Comment by JamesAnderson2** [comment] 2020-07-23 06:32
Joseph thanks for looking into this. 

Is it advised to move the buttons so they fit on the 15 button stream deck? This would be a work around. But I'm wondering if that's likely to cause issues when a fix is created. 

Also, I noticed in the log that the first entry after turning on the new software was 

![Screen Shot 2020-07-23 at 4 31 47 pm](https://user-images.githubusercontent.com/68635697/88257829-04a87900-cd02-11ea-83ca-6e99e2959f1d.png)

As best I can tell, nothing else was accessing the Stream Deck.

**Comment by chouvener** [comment] 2020-07-23 20:29
Would it be possible to revert to the previous version for now somehow? :) Thanks again!

**Comment by MarauderSeeker** [comment] 2020-07-23 20:36
i’m pretty sure the Web Admin always shows the 32 button layout(as of v2)

**Comment by McHauge** [comment] 2020-07-23 20:49
it only shows all the 32 buttons, but if you look you will find that it is segmented after the different types of stream decks, that way you can use the same pages on more than one device.

**Comment by JamesAnderson2** [comment] 2020-07-23 22:01
Regardless of how many buttons it shows in the Web Admin, in previous version, using the 5 row layout of the Stream Deck, button 1.7 was on the second row. It's now the 7th button the first row. Hence it still appears on the Web Admin, but not on my Stream Deck.

**Comment by josephdadams** [comment] 2020-07-23 22:09
The button layout changed with the addition of the 32 key model. Can you rearrange your buttons to accommodate?

**Comment by JamesAnderson2** [comment] 2020-07-23 22:51
Hi Joseph,
Yes, I can move the buttons as a work around. And have done this.

**Comment by JamesAnderson2** [comment] 2020-07-24 07:05
Joseph,

the update you've done is wonderful. Congratulations. Now that I'm over the initial shock of all my buttons being rearranged, I can see the functionality you've added into this version is just incredible. Thank you. Well done.

**Comment by josephdadams** [comment] 2020-07-24 13:09
Companion gets better and better every day thanks to the great community of people who contribute!

**Comment by JamesAnderson2** [comment] 2020-07-25 00:15
<img width="484" alt="Screen Shot 2020-07-25 at 10 09 30 am" src="https://user-images.githubusercontent.com/68635697/88444257-b01b1000-ce5f-11ea-9a39-ad07d3220cd4.png">

Not sure if this is related... but got this error today.

**Comment by josephdadams** [comment] 2020-07-25 02:37
@JamesAnderson2 what modules/instances are you using??

**Comment by JamesAnderson2** [comment] 2020-07-26 05:14
Just the ATEM mini pro

(QQ - I noticed in this version you can add Companion buttons to a multi action button on the stream deck, but it doesn't seem to trigger the action. Is that right?)

**Comment by JamesAnderson2** [comment] 2020-07-28 00:13
Hi Joseph, 
noticed this error message again on start up today. 

![Screen Shot 2020-07-28 at 10 08 41 am](https://user-images.githubusercontent.com/68635697/88604319-90335880-d0ba-11ea-8031-349faa619eeb.png

**Comment by haakonnessjoen** [comment] 2020-07-28 09:25
> Just the ATEM mini pro
> 
> (QQ - I noticed in this version you can add Companion buttons to a multi action button on the stream deck, but it doesn't seem to trigger the action. Is that right?)

Could you please report this as a new issue?

**Comment by haakonnessjoen** [comment] 2020-07-28 09:26
And, in regards to the error you mentioned. You seem to use the stream deck application together with Companion. Have you upgraded your companion plugin in the stream deck application lately? It should be upgraded to 2.1.0 too.

**Comment by JamesAnderson2** [comment] 2020-07-28 21:59
Thanks haakonnessjoen,
I am using stream deck with Companion.

The companion version I'm running is 2.1.0. 

These were installed a matter of weeks ago after upgrading to a new machine.

**Comment by Julusian** [comment] 2021-05-28 20:33
Duplicate of #1603

**Closed by Julusian** 2021-05-28 20:33 UTC
Labels: BUG
