### ISSUE TITLE
feedback logical expression options?

### ISSUE THREAD

**Issue by obbau** [bitfocus/companion#2548] opened 2023-08-13 00:20 UTC
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When adding feedbacks, it would be perfect to have the option to have "is NOT" instead of "is".

Ideas:

== 
!= 

etc.

### Usecases

I have some use cases (i'm sure others will also) where it would be ideal to have feedback on buttons when it's "NOT" meeting a criteria.

For example, "vmix: Tally - Program state" != "input 1"... at the moment it's only possible to do, "vmix: Tally - Program state" == "input 1".

Thank you.

**Comment by premultiply** [comment] 2023-08-13 08:27
Even more: For tally (and other digital logic true/false variables and conditions) it would be much less complex if actions for true and false could be set on a single trigger.

I always get lost if a bit more advanced tally logic needs to be setup using individual true/false triggers for each input on each device.

Or am I missing a trick?

**Comment by Julusian** [comment] 2023-08-13 10:34
> When adding feedbacks, it would be perfect to have the option to have "is NOT" instead of "is".

This is either:
* a request for something to be added to the vmix module, which should be done at https://github.com/bitfocus/companion-module-studiocoast-vmix/issues
* the same as https://github.com/bitfocus/companion/issues/2547
* the same as https://github.com/bitfocus/companion/issues/372

> For tally (and other digital logic true/false variables and conditions) it would be much less complex if actions for true and false could be set on a single trigger.

With the changes to triggers in 3.0, I am not sure how to do this anymore. Maybe https://github.com/bitfocus/companion/issues/1052 will solve it in most cases?

**Comment by premultiply** [comment] 2023-08-13 14:00
Mmmmmh. Not the right thing for the tally logic yet.

Maybe the generic trigger system needs a digital logic buddy?

**Comment by Julusian** [comment] 2024-02-25 14:35
With #2547 having been done, this is either done or the remainder is a duplicate of #372.
Either way, I don't think there is anything here not covered by another issue

**Closed by Julusian** 2024-02-25 14:35 UTC
Labels: Question
